//-
// Copyright 2017, 2018, 2026 The proptest developers
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

//! Strategies for working with bit sets.
//!
//! Besides `BitSet` itself, this also defines strategies for all the primitive
//! integer types. These strategies are appropriate for integers which are used
//! as bit flags, etc; e.g., where the most reasonable simplification of `64`
//! is `0` (clearing one bit) and not `63` (clearing one bit but setting 6
//! others). For integers treated as numeric values, see the corresponding
//! modules of the `num` module instead.

use core::error::Error;
use core::marker::PhantomData;

#[cfg(feature = "bit-set")]
use bit_set::BitSet;
#[cfg(feature = "bit-set")]
use bit_vec::BitVec;
use rand::RngExt as _;
use rand::seq::IteratorRandom as _;

use crate::collection::EmptySizeRange as CollectionEmptySizeRange;
use crate::collection::SizeRange;
use crate::num::sample_uniform_incl;
use crate::std_facade::Vec;
use crate::std_facade::fmt;
use crate::std_facade::string::ToString as _;
use crate::std_facade::vec;
use crate::strategy::NewTree;
use crate::strategy::Strategy;
use crate::strategy::ValueTree;
#[cfg(test)]
use crate::strategy::check_strategy_sanity;
use crate::test_runner::TestRunner;

/// Trait for types which can be handled with `BitSetStrategy`.
pub trait BitSetLike: Clone + fmt::Debug {
  /// Create a new value of `Self` with space for up to `max` bits, all
  /// initialised to zero.
  fn new_bitset(max: usize) -> Self;
  /// Return an upper bound on the greatest bit set _plus one_.
  fn len(&self) -> usize;
  /// Return whether the bit set contains no set bits.
  fn is_empty(&self) -> bool {
    self.count() == 0
  }
  /// Test whether the given bit is set.
  fn test(&self, ix: usize) -> bool;
  /// Set the given bit.
  fn set(&mut self, ix: usize);
  /// Clear the given bit.
  fn clear(&mut self, ix: usize);
  /// Return the number of bits set.
  ///
  /// This has a default for backwards compatibility, which simply does a
  /// linear scan through the bits. Implementations are strongly encouraged
  /// to override this.
  #[allow(
    clippy::single_call_fn,
    reason = "default bit-count implementation scanning every index via test() for BitSetLike"
  )]
  fn count(&self) -> usize {
    (0..self.len()).filter(|&i| self.test(i)).count()
  }
}

/// Implements `BitSetLike` for a primitive integer type used as bit flags.
///
/// The integer stores its bits directly: `new_bitset` yields `0`, `len` is the
/// type's bit width, and `count` uses `count_ones`.
macro_rules! int_bitset {
  ($typ:ty) => {
    impl BitSetLike for $typ {
      fn new_bitset(_: usize) -> Self {
        0
      }
      fn len(&self) -> usize {
        usize::try_from(<$typ>::BITS).unwrap_or(usize::MAX)
      }
      fn test(&self, ix: usize) -> bool {
        0 != (*self & (1 << ix))
      }
      fn set(&mut self, ix: usize) {
        *self |= 1 << ix;
      }
      fn clear(&mut self, ix: usize) {
        *self &= !(1 << ix);
      }
      fn count(&self) -> usize {
        usize::try_from(self.count_ones()).unwrap_or(usize::MAX)
      }
    }
  };
}
int_bitset!(u8);
int_bitset!(u16);
int_bitset!(u32);
int_bitset!(u64);
int_bitset!(u128);
int_bitset!(usize);
int_bitset!(i8);
int_bitset!(i16);
int_bitset!(i32);
int_bitset!(i64);
int_bitset!(i128);
int_bitset!(isize);

#[cfg(feature = "bit-set")]
#[cfg_attr(docsrs, doc(cfg(feature = "bit-set")))]
impl BitSetLike for BitSet {
  fn new_bitset(max: usize) -> Self {
    Self::with_capacity(max)
  }

  fn len(&self) -> usize {
    self.capacity()
  }

  fn test(&self, bit: usize) -> bool {
    self.contains(bit)
  }

  fn set(&mut self, bit: usize) {
    let _was_new = self.insert(bit);
  }

  fn clear(&mut self, bit: usize) {
    let _was_present = self.remove(bit);
  }

  fn count(&self) -> usize {
    Self::count(self)
  }
}

impl BitSetLike for Vec<bool> {
  fn new_bitset(max: usize) -> Self {
    vec![false; max]
  }

  fn len(&self) -> usize {
    self.len()
  }

  fn test(&self, bit: usize) -> bool {
    self.get(bit).copied().unwrap_or(false)
  }

  fn set(&mut self, bit: usize) {
    if bit >= self.len() {
      self.resize(bit.saturating_add(1), false);
    }

    if let Some(slot) = self.get_mut(bit) {
      *slot = true;
    }
  }

  fn clear(&mut self, bit: usize) {
    if let Some(slot) = self.get_mut(bit) {
      *slot = false;
    }
  }

  fn count(&self) -> usize {
    self.iter().filter(|&&bit| bit).count()
  }
}

/// Generates values as a set of bits between the two bounds.
///
/// Values are generated by uniformly setting individual bits to 0
/// or 1 between the bounds. Shrinking iteratively clears bits.
#[must_use = "strategies do nothing unless used"]
#[derive(Clone, Copy, Debug)]
pub struct BitSetStrategy<T: BitSetLike> {
  /// Lowest bit index (inclusive) that may be set.
  min:  usize,
  /// One past the highest bit index (exclusive) that may be set.
  max:  usize,
  /// When present, only bits also set in this mask may be set.
  mask: Option<T>,
}

impl<T: BitSetLike> BitSetStrategy<T> {
  /// Create a strategy which generates values where bits between `min`
  /// (inclusive) and `max` (exclusive) may be set.
  ///
  /// Due to the generics, the functions in the typed submodules are usually
  /// preferable to calling this directly.
  pub const fn new(min: usize, max: usize) -> Self {
    Self {
      min,
      max,
      mask: None,
    }
  }

  /// Create a strategy which generates values where any bits set (and only
  /// those bits) in `mask` may be set.
  pub fn masked(mask: T) -> Self {
    Self {
      min:  0,
      max:  mask.len(),
      mask: Some(mask),
    }
  }
}

impl<T: BitSetLike> Strategy for BitSetStrategy<T> {
  type Tree = BitSetValueTree<T>;
  type Value = T;

  fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
    let mut inner = T::new_bitset(self.max);
    for bit in self.min..self.max {
      if self.mask.as_ref().is_none_or(|mask| mask.test(bit)) && runner.rng().random() {
        inner.set(bit);
      }
    }

    Ok(BitSetValueTree::new(inner, 0, self.min))
  }
}

/// Generates bit sets with a particular number of bits set.
///
/// Specifically, this strategy is given both a size range and a bit range. To
/// produce a new value, it selects a size, then uniformly selects that many
/// bits from within the bit range.
///
/// Shrinking happens as with [`BitSetStrategy`](struct.BitSetStrategy.html).
#[derive(Clone, Debug)]
#[must_use = "strategies do nothing unless used"]
pub struct SampledBitSetStrategy<T: BitSetLike> {
  /// Range for how many bits a generated value has set.
  size:             SizeRange,
  /// Range of bit indices the set bits are drawn from.
  bits:             SizeRange,
  /// Construction-time validation failure, reported when generation starts.
  validation_error: Option<SampledBitsError>,
  /// Ties the strategy to the concrete `BitSetLike` type `T`.
  _marker:          PhantomData<T>,
}

/// Error returned by [`SampledBitSetStrategy::try_new`] when the requested
/// size and bit ranges cannot form a valid sampling strategy.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SampledBitsError {
  /// The requested size range is empty.
  EmptySizeRange(CollectionEmptySizeRange),
  /// The requested sample size exceeds the number of available bits.
  NotEnoughBits {
    /// Number of bits available in the bit range.
    available:     usize,
    /// Start of the requested size range.
    size_start:    usize,
    /// Exclusive end of the requested size range.
    size_end_excl: usize,
  },
}

impl fmt::Display for SampledBitsError {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    match *self {
      Self::EmptySizeRange(inner) => inner.fmt(f),
      Self::NotEnoughBits {
        available,
        size_start,
        size_end_excl,
      } => write!(
        f,
        "Illegal SampledBitSetStrategy: have {available} bits available, but requested size is {size_start}..{size_end_excl}"
      ),
    }
  }
}

impl Error for SampledBitsError {}

impl<T: BitSetLike> SampledBitSetStrategy<T> {
  /// Create a strategy which generates values where bits within the bounds
  /// given by `bits` may be set. The number of bits that are set is chosen
  /// to be in the range given by `size`.
  ///
  /// Due to the generics, the functions in the typed submodules are usually
  /// preferable to calling this directly.
  ///
  /// Invalid ranges are reported as a generation failure from
  /// [`Strategy::new_tree`]. Use [`SampledBitSetStrategy::try_new`] when the
  /// caller needs eager typed validation.
  pub fn new(size: impl Into<SizeRange>, bits: impl Into<SizeRange>) -> Self {
    let size_range = size.into();
    let bit_range = bits.into();
    let validation_error = if let Err(error) = size_range.ensure_nonempty() {
      Some(SampledBitsError::EmptySizeRange(error))
    } else {
      let available_bits = bit_range.end_excl().saturating_sub(bit_range.start());
      (size_range.end_excl() > available_bits.saturating_add(1)).then(|| SampledBitsError::NotEnoughBits {
        available:     available_bits,
        size_start:    size_range.start(),
        size_end_excl: size_range.end_excl(),
      })
    };

    Self {
      size: size_range,
      bits: bit_range,
      validation_error,
      _marker: PhantomData,
    }
  }

  /// Fallible form of [`SampledBitSetStrategy::new`]: returns a typed
  /// error instead of panicking when `size` is empty or requests more bits
  /// than `bits` makes available.
  ///
  /// ## Errors
  ///
  /// Returns [`SampledBitsError::EmptySizeRange`] when `size` is an empty
  /// range, or [`SampledBitsError::NotEnoughBits`] when `size` can demand
  /// more bits than the `bits` range makes available.
  #[allow(
    clippy::single_call_fn,
    reason = "validate size and bit ranges, then build the fallible sampled bit-set strategy"
  )]
  pub fn try_new(size: impl Into<SizeRange>, bits: impl Into<SizeRange>) -> Result<Self, SampledBitsError> {
    let strategy = Self::new(size, bits);
    strategy.validation_error.map_or(Ok(strategy), Err)
  }
}

impl<T: BitSetLike> Strategy for SampledBitSetStrategy<T> {
  type Tree = BitSetValueTree<T>;
  type Value = T;

  fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
    if let Some(error) = self.validation_error {
      return Err(error.to_string().into());
    }

    let mut bits = T::new_bitset(self.bits.end_excl());
    let count = sample_uniform_incl(runner, self.size.start(), self.size.end_incl())?;
    if bits.len() < count {
      // Reachable only when the concrete `BitSetLike` cannot represent
      // the requested bit range (e.g. sampling 20 bits from a `u8`);
      // report a generation failure instead of panicking.
      return Err("not enough bits to sample".into());
    }

    for bit in self.bits.iter().sample(runner.rng(), count) {
      bits.set(bit);
    }

    Ok(BitSetValueTree::new(bits, self.size.start(), self.bits.start()))
  }
}

/// Value tree produced by `BitSetStrategy` and `SampledBitSetStrategy`.
#[derive(Clone, Copy, Debug)]
pub struct BitSetValueTree<T: BitSetLike> {
  /// The bitset holding the currently generated value.
  inner:       T,
  /// Index of the next bit to try clearing when simplifying.
  shrink:      usize,
  /// Index of the bit cleared by the most recent `simplify()`, so
  /// `complicate()` can set it again; `None` when there is nothing to
  /// undo.
  prev_shrink: Option<usize>,
  /// Lower bound on the number of set bits; shrinking never clears bits
  /// below this count.
  min_count:   usize,
}

impl<T: BitSetLike> BitSetValueTree<T> {
  /// Shrink an existing bitset down to `min_count` by clearing bits in order,
  /// starting at `first_bit`.
  pub(crate) const fn new(inner: T, min_count: usize, first_bit: usize) -> Self {
    Self {
      inner,
      shrink: first_bit,
      prev_shrink: None,
      min_count,
    }
  }

  /// Borrow the current selection without cloning its backing storage.
  pub(crate) const fn bits(&self) -> &T {
    &self.inner
  }
}

impl<T: BitSetLike> ValueTree for BitSetValueTree<T> {
  type Value = T;

  fn current(&self) -> T {
    self.bits().clone()
  }

  fn simplify(&mut self) -> bool {
    if self.inner.count() <= self.min_count {
      return false;
    }

    while self.shrink < self.inner.len() && !self.inner.test(self.shrink) {
      self.shrink = self.shrink.saturating_add(1);
    }

    if self.shrink >= self.inner.len() {
      self.prev_shrink = None;
      false
    } else {
      self.prev_shrink = Some(self.shrink);
      self.inner.clear(self.shrink);
      self.shrink = self.shrink.saturating_add(1);
      true
    }
  }

  fn complicate(&mut self) -> bool {
    if let Some(bit) = self.prev_shrink.take() {
      self.inner.set(bit);
      true
    } else {
      false
    }
  }
}

/// Define the typed bit-set constructors, with an optional `ANY` constant for
/// representations whose full width is fixed independently of the platform.
macro_rules! bitset_api {
  ($module:ident, $typ:ty $(, $max:expr)?) => {
    #[doc = concat!(
                                                                                            "Bit-set strategies for `",
                                                                                            stringify!($typ),
                                                                                            "` values, shrinking by clearing selected bits."
                                                                                        )]
    pub mod $module {
      use super::*;

      $(
      /// Generates integers where all bits may be set.
      pub const ANY: BitSetStrategy<$typ> = BitSetStrategy {
        min:  0,
        max:  $max,
        mask: None,
      };
      )?

      /// Generates values where bits between the given bounds may be
      /// set.
      pub const fn between(min: usize, max: usize) -> BitSetStrategy<$typ> {
        BitSetStrategy::new(min, max)
      }

      /// Generates values where any bits set in `mask` (and no others)
      /// may be set.
      #[allow(
        clippy::single_call_fn,
        reason = "the typed mask constructor exposes the bit-set API for each representation"
      )]
      pub fn masked(mask: $typ) -> BitSetStrategy<$typ> {
        BitSetStrategy::masked(mask)
      }

      /// Create a strategy which generates values where bits within the
      /// bounds given by `bits` may be set. The number of bits that are
      /// set is chosen to be in the range given by `size`.
      ///
      /// Invalid ranges are reported during generation. Use
      /// [`SampledBitSetStrategy::try_new`] for eager typed validation.
      pub fn sampled(size: impl Into<SizeRange>, bits: impl Into<SizeRange>) -> SampledBitSetStrategy<$typ> {
        SampledBitSetStrategy::new(size, bits)
      }
    }
  };
}

bitset_api!(u8, u8, 8);
bitset_api!(u16, u16, 16);
bitset_api!(u32, u32, 32);
bitset_api!(u64, u64, 64);
bitset_api!(u128, u128, 128);
bitset_api!(i8, i8, 8);
bitset_api!(i16, i16, 16);
bitset_api!(i32, i32, 32);
bitset_api!(i64, i64, 64);
bitset_api!(i128, i128, 128);
bitset_api!(usize, usize);
bitset_api!(isize, isize);
#[cfg(feature = "bit-set")]
#[cfg_attr(docsrs, doc(cfg(feature = "bit-set")))]
bitset_api!(bitset, BitSet);
bitset_api!(bool_vec, Vec<bool>);

/// The crate's variable-size bit set.
///
/// [`VarBitSet`] wraps a `bit_set::BitSet` when the `bit-set` feature is on and
/// a `Vec<bool>` otherwise, giving `collection`/`sample` one bit-set type
/// regardless of the enabled features.
mod varsize {
  use core::iter::FromIterator;

  #[cfg(feature = "bit-set")]
  use super::BitSet;
  use super::BitSetLike;
  #[cfg(feature = "bit-set")]
  use super::BitVec;
  use super::usize;
  #[cfg(not(feature = "bit-set"))]
  use crate::std_facade::Vec;
  #[cfg(not(feature = "bit-set"))]
  use crate::std_facade::vec;

  /// Backing bit-set type: `BitSet` when the `bit-set` feature is enabled.
  #[cfg(feature = "bit-set")]
  type Inner = BitSet;
  /// Backing bit-set type: `Vec<bool>` without the `bit-set` feature.
  #[cfg(not(feature = "bit-set"))]
  type Inner = Vec<bool>;

  /// A bit set is a set of bit flags.
  #[derive(Debug, Clone)]
  pub struct VarBitSet(Inner);

  impl VarBitSet {
    /// Create a bit set of `len` set values.
    #[cfg(not(feature = "bit-set"))]
    #[must_use]
    pub fn saturated(len: usize) -> Self {
      Self(vec![true; len])
    }

    /// Create a bit set of `len` set values.
    #[cfg(feature = "bit-set")]
    #[must_use]
    pub fn saturated(len: usize) -> Self {
      Self(BitSet::from_bit_vec(BitVec::from_elem(len, true)))
    }

    /// Iterates the indices of the set bits in ascending order.
    #[cfg(not(feature = "bit-set"))]
    pub(crate) fn iter(&self) -> impl Iterator<Item = usize> + '_ {
      (0..self.len()).into_iter().filter(move |&ix| self.test(ix))
    }

    /// Iterates the indices of the set bits in ascending order.
    #[cfg(feature = "bit-set")]
    pub(crate) fn iter(&self) -> impl Iterator<Item = usize> + '_ {
      self.0.iter()
    }
  }

  impl BitSetLike for VarBitSet {
    fn new_bitset(max: usize) -> Self {
      Self(Inner::new_bitset(max))
    }

    fn len(&self) -> usize {
      BitSetLike::len(&self.0)
    }

    fn test(&self, bit: usize) -> bool {
      BitSetLike::test(&self.0, bit)
    }

    fn set(&mut self, bit: usize) {
      BitSetLike::set(&mut self.0, bit);
    }

    fn clear(&mut self, bit: usize) {
      BitSetLike::clear(&mut self.0, bit);
    }

    fn count(&self) -> usize {
      BitSetLike::count(&self.0)
    }
  }

  impl FromIterator<usize> for VarBitSet {
    fn from_iter<T: IntoIterator<Item = usize>>(into_iter: T) -> Self {
      let iter = into_iter.into_iter();
      let lower_bound = iter.size_hint().0;
      let mut bits = Self::new_bitset(lower_bound);
      for bit in iter {
        bits.set(bit);
      }
      bits
    }
  }

  // pub(crate) fn between(min: usize, max: usize) -> BitSetStrategy<VarBitSet> {
  // BitSetStrategy::new(min, max)
  // }
  //
  // pub(crate) fn masked(mask: VarBitSet) -> BitSetStrategy<VarBitSet> {
  // BitSetStrategy::masked(mask)
  // }
}

pub use self::varsize::VarBitSet;

/// Creates a [`SampledBitSetStrategy`] over [`VarBitSet`] selecting `size`
/// bits from within the `bits` index range.
#[allow(
  clippy::single_call_fn,
  reason = "crate-level constructor hides the private varsize module from collection sampling strategies"
)]
pub(crate) fn sampled_var_bitset(size: impl Into<SizeRange>, bits: impl Into<SizeRange>) -> SampledBitSetStrategy<VarBitSet> {
  SampledBitSetStrategy::new(size, bits)
}

#[cfg(test)]
mod test {
  use core::ops::BitOr;

  use strict_test_support::PredicateFailure;
  use strict_test_support::ensure_that;

  use super::*;
  use crate::std_facade::Box;
  use crate::strategy::trace_shrink_steps;
  use crate::test_runner::Reason;

  /// Complete native assertion subjects remain allocated on failure.
  type Check<S> = Result<(), Box<PredicateFailure<S>>>;
  /// Both rejected bitset constructor requests.
  type InvalidRequests = [Result<SampledBitSetStrategy<u32>, SampledBitsError>; 2];
  /// Mask strategy samples together with both mask insertion outcomes.
  #[cfg(feature = "bit-set")]
  type MaskSamples = (Samples<BitSetStrategy<BitSet>>, [bool; 2]);
  /// Every variable-bitset mutation and its out-of-bounds read.
  type VariableOperations = (Vec<Vec<bool>>, bool);
  /// One bitset and its simplify/complicate observations.
  type Complication = (BitSetValueTree<u32>, u32, bool, Option<bool>);

  /// Native strategy and every generated value tree or generation failure.
  type Samples<S> = (S, Vec<NewTree<S>>);
  /// A complete bit-clearing trace and its reached tree.
  type Shrink<T> = (BitSetValueTree<T>, Vec<T>);
  /// Native generation results after exercising each tree's shrink contract.
  type Shrinks<T> = Vec<Result<Shrink<T>, Reason>>;

  /// Preserve strategy parameters and generated trees under deterministic sampling.
  fn samples<S: Strategy>(strategy: S, count: usize) -> Samples<S> {
    let mut runner = TestRunner::deterministic();
    let samples = (0..count).map(|_| strategy.new_tree(&mut runner)).collect();
    (strategy, samples)
  }

  /// Observe every native bitset visited while simplifying each generated tree.
  fn shrinks<T: BitSetLike>(strategy: impl Strategy<Tree = BitSetValueTree<T>>, count: usize) -> Shrinks<T> {
    let mut runner = TestRunner::deterministic();
    (0..count)
      .map(|_| strategy.new_tree(&mut runner).map(trace_shrink_steps))
      .collect()
  }

  /// Check the union of all generated masks while preserving each failed draw.
  fn covers_mask<T: BitSetLike + BitOr<Output = T> + Default + PartialEq>(samples: &Samples<BitSetStrategy<T>>, mask: &T) -> bool {
    samples.1.iter().all(Result::is_ok)
      && samples
        .1
        .iter()
        .filter_map(|sample| sample.as_ref().ok())
        .fold(T::default(), |bits, tree| bits | tree.current())
        == *mask
  }

  #[test]
  fn zero_capacity_bitset_is_empty() -> Check<(u32, VarBitSet)> {
    ensure_that(
      (u32::new_bitset(0), VarBitSet::new_bitset(0)),
      "new primitive and variable bitsets contain no set bits",
      |observed| observed.0.is_empty() && observed.1.is_empty(),
    )
    .map(drop)
    .map_err(Box::new)
  }

  /// Construction and generation remain separate, concrete result boundaries.
  type Constructed<T> = Result<(SampledBitSetStrategy<T>, NewTree<SampledBitSetStrategy<T>>), SampledBitsError>;

  #[test]
  fn try_new_accepts_a_satisfiable_sample_request() -> Check<Constructed<u32>> {
    let mut runner = TestRunner::deterministic();
    let observed = SampledBitSetStrategy::<u32>::try_new(2..=4, 0..8).map(|strategy| {
      let tree = strategy.new_tree(&mut runner);
      (strategy, tree)
    });
    ensure_that(
      observed,
      "valid construction generates a bit count in the requested size range",
      |result| {
        result.as_ref().is_ok_and(|reached| {
          reached
            .1
            .as_ref()
            .is_ok_and(|tree| (2..=4).contains(&tree.current().count_ones()))
        })
      },
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn try_new_rejects_unsatisfiable_sample_requests() -> Check<InvalidRequests> {
    ensure_that(
      [
        SampledBitSetStrategy::try_new(4..4, 0..8),
        SampledBitSetStrategy::try_new(0..=9, 0..8),
      ],
      "invalid sizes retain the precise empty-range and available-bit errors",
      |results| {
        matches!(*results, [
          Err(SampledBitsError::EmptySizeRange(_)),
          Err(SampledBitsError::NotEnoughBits {
            available:     8,
            size_start:    0,
            size_end_excl: 10,
          })
        ])
      },
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn undersized_bitset_reports_generation_failure() -> Check<Constructed<u8>> {
    let mut runner = TestRunner::deterministic();
    let observed = SampledBitSetStrategy::<u8>::try_new(16..=16, 0..20).map(|strategy| {
      let tree = strategy.new_tree(&mut runner);
      (strategy, tree)
    });
    ensure_that(
      observed,
      "a constructible request reports the concrete type's capacity shortfall during generation",
      |result| {
        result.as_ref().is_ok_and(|reached| {
          reached
            .1
            .as_ref()
            .is_err_and(|reason| reason.message() == "not enough bits to sample")
        })
      },
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn generates_values_in_range() -> Check<Samples<BitSetStrategy<u32>>> {
    ensure_that(
      samples(u32::between(4, 8), 256),
      "generated bits stay within the requested range",
      |observed| {
        observed
          .1
          .iter()
          .all(|sample| sample.as_ref().is_ok_and(|tree| tree.current() & !0xf0_u32 == 0))
      },
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn generates_values_in_mask() -> Check<Samples<BitSetStrategy<u32>>> {
    ensure_that(
      samples(u32::masked(0xdead_beef), 1024),
      "every masked bit is eventually generated and no unmasked bit appears",
      |observed| covers_mask(observed, &0xdead_beef),
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[cfg(feature = "bit-set")]
  #[test]
  fn mask_bounds_for_bitset_correct() -> Check<MaskSamples> {
    let mut mask = BitSet::new();
    let insertions = [mask.insert(0), mask.insert(2)];
    ensure_that(
      (samples(bitset::masked(mask), 32), insertions),
      "each requested mask bit is generated",
      |observed| {
        observed.1 == [true, true]
          && observed.0.1.iter().all(Result::is_ok)
          && [0, 2].into_iter().all(|bit| {
            observed
              .0
              .1
              .iter()
              .any(|sample| sample.as_ref().is_ok_and(|tree| tree.current().contains(bit)))
          })
      },
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[cfg(feature = "bit-set")]
  #[test]
  fn bitset_set_and_clear_are_idempotent() -> Check<(BitSet, BitSet)> {
    let mut bits = BitSet::new();
    BitSetLike::set(&mut bits, 7);
    BitSetLike::set(&mut bits, 7);
    let set = bits.clone();
    BitSetLike::clear(&mut bits, 7);
    BitSetLike::clear(&mut bits, 7);
    ensure_that(
      (set, bits),
      "repeated set stores one bit and repeated clear removes it",
      |observed| observed.0.count() == 1 && observed.0.contains(7) && observed.1.is_empty(),
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn mask_bounds_for_vecbool_correct() -> Check<Samples<BitSetStrategy<Vec<bool>>>> {
    ensure_that(
      samples(bool_vec::masked(vec![true, false, true, false]), 32),
      "the mask length is preserved and both mask bits are generated",
      |observed| {
        observed
          .1
          .iter()
          .all(|sample| sample.as_ref().is_ok_and(|tree| tree.current().len() == 4))
          && [0, 2].into_iter().all(|bit| {
            observed
              .1
              .iter()
              .any(|sample| sample.as_ref().is_ok_and(|tree| tree.current().test(bit)))
          })
      },
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn shrinks_to_zero() -> Check<Shrinks<u32>> {
    let clears_one_bit = |sample: &Result<Shrink<u32>, Reason>| {
      let Ok(ref reached) = *sample else {
        return false;
      };
      reached.0.current() == 0
        && reached
          .1
          .array_windows::<2>()
          .all(|&[before, after]| (before & !after).is_power_of_two())
    };
    ensure_that(
      shrinks(u32::between(4, 24), 256),
      "each simplification clears exactly one bit until reaching zero",
      |samples| samples.iter().all(clears_one_bit),
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn complicates_to_previous() -> Check<Vec<Result<Complication, Reason>>> {
    let (_, generated) = samples(u32::between(4, 24), 256);
    let observations = generated
      .into_iter()
      .map(|sample| {
        sample.map(|mut tree| {
          let original = tree.current();
          let simplified = tree.simplify();
          let complicated = simplified.then(|| tree.complicate());
          (tree, original, simplified, complicated)
        })
      })
      .collect();
    let restores_original = |sample: &Result<Complication, Reason>| {
      let Ok(ref reached) = *sample else {
        return false;
      };
      (reached.2 && reached.3 == Some(true) && reached.0.current() == reached.1) || (!reached.2 && reached.3.is_none())
    };
    ensure_that(
      observations,
      "a successful simplification complicates back to the original value",
      |samples: &Vec<Result<_, Reason>>| samples.iter().all(restores_original),
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn sampled_selects_correct_sizes_and_bits() -> Check<Samples<SampledBitSetStrategy<u32>>> {
    let valid_bits = |value: u32| (4..8).contains(&value.count_ones()) && value & !0x000f_fc00 == 0;
    ensure_that(
      samples(u32::sampled(4..8, 10..20), 2048),
      "sampled sizes and bits obey their ranges with roughly uniform selection",
      |observed| {
        let valid = observed
          .1
          .iter()
          .all(|sample| sample.as_ref().is_ok_and(|tree| valid_bits(tree.current())));
        let counts = [4, 5, 6, 7].map(|width| {
          observed
            .1
            .iter()
            .filter(|sample| sample.as_ref().is_ok_and(|tree| tree.current().count_ones() == width))
            .count()
        });
        let bits: Vec<_> = (10..20)
          .map(|bit| {
            observed
              .1
              .iter()
              .filter(|sample| sample.as_ref().is_ok_and(|tree| tree.current().test(bit)))
              .count()
          })
          .collect();
        valid
          && counts.iter().all(|count| (256..1024).contains(count))
          && bits
            .iter()
            .min()
            .zip(bits.iter().max())
            .is_some_and(|(min, max)| max.checked_div(*min) == Some(1))
      },
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn sampled_doesnt_shrink_below_min_size() -> Check<Shrinks<u32>> {
    ensure_that(
      shrinks(u32::sampled(4..8, 10..20), 256),
      "shrinking stops at four set bits",
      |samples| {
        samples.iter().all(|sample| {
          sample
            .as_ref()
            .is_ok_and(|reached| reached.0.current().count_ones() == 4 && reached.1.iter().all(|value| value.count_ones() >= 4))
        })
      },
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn test_sanity() -> Result<(), Reason> {
    check_strategy_sanity(u32::masked(0xdead_beef), None)
  }

  #[test]
  fn u128_generates_values_in_range() -> Check<Samples<BitSetStrategy<u128>>> {
    ensure_that(
      samples(u128::between(64, 128), 256),
      "generated u128 values have no low bits set",
      |observed| {
        observed
          .1
          .iter()
          .all(|sample| sample.as_ref().is_ok_and(|tree| tree.current() & u128::from(u64::MAX) == 0))
      },
    )
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn u128_shrinks_to_zero() -> Check<Shrinks<u128>> {
    ensure_that(shrinks(u128::between(64, 128), 256), "u128 bitsets shrink to zero", |samples| {
      samples
        .iter()
        .all(|sample| sample.as_ref().is_ok_and(|reached| reached.0.current() == 0))
    })
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn i128_generates_values_in_mask() -> Check<Samples<BitSetStrategy<i128>>> {
    let mask = 0x0123_4567_89ab_cdef_0123_4567_89ab_cdef_i128;
    ensure_that(samples(i128::masked(mask), 1024), "every i128 mask bit is generated", |observed| {
      covers_mask(observed, &mask)
    })
    .map(drop)
    .map_err(Box::new)
  }

  #[test]
  fn u128_test_sanity() -> Result<(), Reason> {
    check_strategy_sanity(u128::masked(0xdead_beef_cafe_babe_1234_5678_9abc_def0), None)
  }

  #[test]
  fn vec_bool_bitset_ops_are_bounds_checked() -> Check<VariableOperations> {
    let mut bits = vec![false; 4];
    BitSetLike::set(&mut bits, 2);
    let mut observed = vec![bits.clone()];
    BitSetLike::clear(&mut bits, 2);
    observed.push(bits.clone());
    let outside = BitSetLike::test(&bits, 100);
    BitSetLike::clear(&mut bits, 100);
    observed.push(bits.clone());
    BitSetLike::set(&mut bits, 6);
    observed.push(bits);
    ensure_that(
      (observed, outside),
      "clear and reads are bounds checked while set grows the bit vector",
      |subject| {
        !subject.1
          && matches!(*subject.0.as_slice(), [ref set, ref cleared, ref outside_cleared, ref grown]
        if set == &[false, false, true, false] && cleared == &[false; 4] && outside_cleared == cleared
          && grown == &[false, false, false, false, false, false, true])
      },
    )
    .map(drop)
    .map_err(Box::new)
  }
}
