[package]
name = "proptest-state-machine"
version.workspace = true
authors = ["Tomáš Zemanovič", "Takumi Shimada <hello@takumi.earth>"]
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords = ["property", "testing", "quickcheck", "fuzz", "state-machine"]
categories.workspace = true
description = """
State machine based testing support for proptest.
"""

[lints]
workspace = true

[features]
default = ["std"]

# Enables the use of standard-library dependent features
std = ["proptest/std"]

[dependencies]
proptest = { workspace = true, features = [
    "fork",
    "timeout",
    "bit-set",
] }

[dev-dependencies]
message-io = { workspace = true, features = ["tcp", "udp", "websocket"] }
strict-test-support = { workspace = true }
