[workspace]
members = [
    "proptest",
    "proptest-derive",
    "proptest-state-machine",
    "proptest-macro",
]

resolver = "3"
exclude = ["proptest/test-persistence-location/*"]

[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/proptest-rs/proptest"
categories = ["development-tools::testing"]
edition = "2024"
rust-version = "1.96"

[workspace.dependencies]

# Internal deps
proptest = { version = "1.11.0", path = "proptest" }
proptest-macro = { version = "0.5.0", path = "proptest-macro" }

# External deps
bit-set = "0.8.0"
bit-vec = "0.8.0"
bitflags = "2.13"
compiletest_rs = "0.11"
convert_case = "0.11"
criterion = "0.8"
insta = "1"
message-io = { version = "0.19.0", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
prettyplease = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
rand = { version = "0.10", default-features = false }
rand_chacha = { version = "0.10", default-features = false }
rand_xorshift = "0.5"
regex = "1.12"
regex-syntax = "0.8"
rusty-fork = { version = "0.3.1", default-features = false }
serde_json = "1.0"
syn = "2.0.118"
tempfile = "3.27"
trybuild = "=1.0.115"
unarray = "0.1.4"
x86 = "0.52.0"
