[package]
name = "proptest-derive"
version = "0.8.0"
authors = ["Mazdak Farrokhzad <twingoow@gmail.com>"]
license.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
documentation = "https://proptest-rs.github.io/proptest/proptest-derive/index.html"
keywords = ["derive", "arbitrary", "proptest", "testing", "quickcheck"]
categories.workspace = true
description = """
Custom-derive for the Arbitrary trait of proptest.
"""
homepage = "https://proptest-rs.github.io/proptest/proptest-derive/index.html"

[lib]
proc-macro = true

[dev-dependencies]
proptest = { workspace = true }
strict-test-support = { workspace = true }
# We don't actually run the tests on stable since some of them use nightly
# features. However, due to
# https://github.com/laumann/compiletest-rs/issues/166, the default features of
# compiletest-rs fail to compile, but the stable fallback works fine.
compiletest_rs = { workspace = true, features = ["tmp", "stable"] }
# criterion is used for benchmarks.
criterion = { workspace = true }
serde_json = { workspace = true }

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["visit", "extra-traits", "full"] }
quote = { workspace = true }

[features]
# Don't generate TupleUnion structs in #[derive(Arbitrary)] code
boxed_union = []

[[bench]]
name = "large_enum"
harness = false
