[package]
name = "proptest-derive"
version.workspace = true
authors = ["Mazdak Farrokhzad <twingoow@gmail.com>", "Takumi Shimada <hello@takumi.earth>"]
license.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
documentation.workspace = true
keywords = ["derive", "arbitrary", "proptest", "testing", "quickcheck"]
categories.workspace = true
description = """
Custom-derive for the Arbitrary trait of proptest.
"""
homepage.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dev-dependencies]
proptest = { workspace = true }
strict-test-support = { workspace = true }
# We don't actually run the tests on stable since some of them use nightly
# features. However, due to
# https://github.com/laumann/compiletest-rs/issues/166, the default features of
# compiletest-rs fail to compile, but the stable fallback works fine.
compiletest_rs = { workspace = true, features = ["tmp", "stable"] }
# criterion is used for benchmarks.
criterion = { workspace = true }
serde_json = { workspace = true }

[dependencies]
proptest-derive-internal = { workspace = true }
proc-macro2 = { workspace = true }

[features]
# Don't generate TupleUnion structs in #[derive(Arbitrary)] code
boxed_union = ["proptest-derive-internal/boxed_union"]

[[bench]]
name = "large_enum"
harness = false
