//-
// Copyright 2022 The proptest developers
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

//! Alternative uniform float samplers.
//! These samplers are used over the ones from `rand` because the ones provided by the
//! rand crate are prone to overflow. In addition, these are 'high precision' samplers
//! that are more appropriate for test data.
//! The samplers work by splitting the range into equally sized intervals and selecting
//! an iterval at random. That interval is then itself split and a new interval is
//! selected at random. The process repeats until the interval only contains two
//! floating point values at the bounds. At that stage, one is selected at random and
//! returned.

#[cfg(feature = "f16")]
pub(super) use self::f16::F16U;
pub(super) use self::f32::F32U;
pub(super) use self::f64::F64U;
use num_traits::ToPrimitive as _;

/// Convert the sampler's unsigned interval index into its float type.
trait IntoSamplerFloat<F> {
    /// Perform the integer-to-float conversion used by the sampler math.
    fn into_sampler_float(self) -> F;
}

/// Convert between a sampler's float and integer index spaces.
trait SamplerIndex<F>: Sized {
    /// Convert an integral float value into the sampler's integer index.
    fn from_sampler_float(float: F) -> Self;

    /// Convert a `usize` generated by an index strategy into the sampler index.
    #[cfg(test)]
    fn from_usize_index(index: usize) -> Self;

    /// Convert a sampler interval count into a `usize` range bound.
    #[cfg(test)]
    fn into_usize_count(self) -> usize;
}

#[cfg(feature = "f16")]
impl IntoSamplerFloat<f16> for u16 {
    fn into_sampler_float(self) -> f16 {
        f16_from_u16(self)
    }
}

#[cfg(feature = "f16")]
impl SamplerIndex<f16> for u16 {
    fn from_sampler_float(float: f16) -> Self {
        u16_from_f16_integer(float)
    }

    #[cfg(test)]
    fn from_usize_index(index: usize) -> Self {
        Self::try_from(index).unwrap_or(Self::MAX)
    }

    #[cfg(test)]
    fn into_usize_count(self) -> usize {
        usize::from(self)
    }
}

impl IntoSamplerFloat<f32> for u32 {
    fn into_sampler_float(self) -> f32 {
        self.to_f32().unwrap_or(f32::INFINITY)
    }
}

impl SamplerIndex<f32> for u32 {
    fn from_sampler_float(float: f32) -> Self {
        float.to_u32().unwrap_or(Self::MAX)
    }

    #[cfg(test)]
    fn from_usize_index(index: usize) -> Self {
        Self::try_from(index).unwrap_or(Self::MAX)
    }

    #[cfg(test)]
    fn into_usize_count(self) -> usize {
        usize::try_from(self).unwrap_or(usize::MAX)
    }
}

impl IntoSamplerFloat<f64> for u64 {
    fn into_sampler_float(self) -> f64 {
        self.to_f64().unwrap_or(f64::INFINITY)
    }
}

impl SamplerIndex<f64> for u64 {
    fn from_sampler_float(float: f64) -> Self {
        float.to_u64().unwrap_or(Self::MAX)
    }

    #[cfg(test)]
    fn from_usize_index(index: usize) -> Self {
        Self::try_from(index).unwrap_or(Self::MAX)
    }

    #[cfg(test)]
    fn into_usize_count(self) -> usize {
        usize::try_from(self).unwrap_or(usize::MAX)
    }
}

#[cfg(feature = "f16")]
/// Convert a nonnegative sampler index into an IEEE 754 half-precision value.
#[allow(
    clippy::single_call_fn,
    reason = "name the half-precision sampler-index to f16 bit-layout conversion used by the f16 sampler trait impl"
)]
fn f16_from_u16(sampler_index: u16) -> f16 {
    const SIGNIFICAND_BITS: u32 = 10;
    const EXPONENT_BIAS: u32 = 15;
    const EXPONENT_MASK: u16 = 0x7c00;
    const MANTISSA_MASK: u16 = 0x03ff;
    const HIDDEN_BIT: u16 = 0x0400;

    if sampler_index == 0 {
        return f16::from_bits(0);
    }

    let highest_bit = u16::BITS
        .saturating_sub(1)
        .saturating_sub(sampler_index.leading_zeros());
    let mut exponent = highest_bit.saturating_add(EXPONENT_BIAS);
    let mantissa = if highest_bit <= SIGNIFICAND_BITS {
        let shift = SIGNIFICAND_BITS.saturating_sub(highest_bit);
        sampler_index.checked_shl(shift).unwrap_or(0) & MANTISSA_MASK
    } else {
        let shift = highest_bit.saturating_sub(SIGNIFICAND_BITS);
        let significand = sampler_index >> shift;
        let base = significand.checked_shl(shift).unwrap_or(0);
        let remainder = sampler_index.saturating_sub(base);
        let halfway = 1_u16.checked_shl(shift.saturating_sub(1)).unwrap_or(0);
        let rounds_to_even = remainder == halfway && significand & 1 != 0;
        let round_up = remainder > halfway || rounds_to_even;
        let rounded = significand.saturating_add(u16::from(round_up));
        if rounded == HIDDEN_BIT.checked_shl(1).unwrap_or(0) {
            exponent = exponent.saturating_add(1);
            0
        } else {
            rounded & MANTISSA_MASK
        }
    };

    if exponent >= 0x1f {
        return f16::from_bits(EXPONENT_MASK);
    }

    let exponent_bits = u16::try_from(exponent)
        .unwrap_or(0)
        .checked_shl(SIGNIFICAND_BITS)
        .unwrap_or(0);
    f16::from_bits(exponent_bits | mantissa)
}

#[cfg(feature = "f16")]
/// Convert a nonnegative integral half-precision value into a sampler index.
#[allow(
    clippy::single_call_fn,
    reason = "name the f16 bit-layout to sampler-index conversion used by the f16 sampler trait impl"
)]
fn u16_from_f16_integer(float: f16) -> u16 {
    const SIGNIFICAND_BITS: u32 = 10;
    const EXPONENT_BIAS: i32 = 15;
    const EXPONENT_MASK: u16 = 0x1f;
    const MANTISSA_MASK: u16 = 0x03ff;
    const HIDDEN_BIT: u16 = 0x0400;
    const SIGN_BIT: u16 = 0x8000;

    let bits = float.to_bits();
    if bits & SIGN_BIT != 0 {
        return 0;
    }

    let exponent_bits = (bits >> SIGNIFICAND_BITS) & EXPONENT_MASK;
    if exponent_bits == 0 {
        return 0;
    }
    if exponent_bits == EXPONENT_MASK {
        return u16::MAX;
    }

    let exponent = i32::from(exponent_bits)
        .checked_sub(EXPONENT_BIAS)
        .unwrap_or(i32::MIN);
    if exponent < 0 {
        return 0;
    }

    let significand = u32::from(HIDDEN_BIT | (bits & MANTISSA_MASK));
    let magnitude = if exponent >= i32::try_from(SIGNIFICAND_BITS).unwrap_or(0)
    {
        let shift = u32::try_from(exponent)
            .unwrap_or(0)
            .saturating_sub(SIGNIFICAND_BITS);
        significand.checked_shl(shift).unwrap_or(u32::MAX)
    } else {
        let shift = SIGNIFICAND_BITS
            .saturating_sub(u32::try_from(exponent).unwrap_or(0));
        significand >> shift
    };

    u16::try_from(magnitude).unwrap_or(u16::MAX)
}

/// Convert an integral float value into its sampler integer index.
fn sampler_index_from_float<F, I>(float: F) -> I
where
    I: SamplerIndex<F>,
{
    I::from_sampler_float(float)
}

#[cfg(test)]
fn sampler_index_from_usize<F, I>(index: usize) -> I
where
    I: SamplerIndex<F>,
{
    I::from_usize_index(index)
}

#[cfg(test)]
fn sampler_count_to_usize<F, I>(value: I) -> usize
where
    I: SamplerIndex<F>,
{
    value.into_usize_count()
}

#[cfg(test)]
fn sampler_round_trip_integer<F, I>(value: I) -> I
where
    I: IntoSamplerFloat<F> + SamplerIndex<F>,
{
    I::from_sampler_float(value.into_sampler_float())
}

/// Defines a high-precision uniform float sampler module for one float type.
///
/// Emits a `pub mod` (named after `$typ`) providing a `FloatUniform`
/// (`impl UniformSampler`) and the `$wrapper` newtype (`F32U`/`F64U`/`F16U`)
/// that `num` samples through. The sampler recursively splits the range into
/// equal-width intervals and descends until a single ULP remains, avoiding the
/// overflow and precision loss of `rand`'s float `Uniform`.
macro_rules! float_sampler {
    (
        $typ: ident,
        $int_typ: ident,
        $wrapper: ident
        $(, no_std_trait = $no_std_trait:path)?
    ) => {
        mod $typ {
            use super::{IntoSamplerFloat, sampler_index_from_float};
            use rand::prelude::*;
            use rand::distr::uniform::{
                SampleBorrow, SampleUniform, UniformSampler,
            };
            $(
                #[cfg(not(feature = "std"))]
                use $no_std_trait;
            )?
            #[must_use]
            fn float_equal(left: $typ, right: $typ) -> bool {
                matches!(
                    left.partial_cmp(&right),
                    Some(core::cmp::Ordering::Equal)
                )
            }

            #[must_use]
            fn float_greater(left: $typ, right: $typ) -> bool {
                matches!(
                    left.partial_cmp(&right),
                    Some(core::cmp::Ordering::Greater)
                )
            }

            #[must_use]
            const fn float_is_zero(float: $typ) -> bool {
                matches!(float.classify(), core::num::FpCategory::Zero)
            }

            #[cfg(test)]
            #[must_use]
            const fn float_bits_equal(left: $typ, right: $typ) -> bool {
                left.to_bits() == right.to_bits()
            }

            #[must_use]
            // Returns the previous float value. In other words the greatest value representable
            // as a float such that `next_down(float) < float`. `-0.` is treated as `0.`.
            fn next_down(float: $typ) -> $typ {
                if !float.is_finite() {
                    return float;
                }
                if float <= $typ::MIN {
                    return $typ::MIN;
                }
                if float_is_zero(float) {
                    core::ops::Neg::neg($typ::from_bits(1))
                } else if float < 0. {
                    $typ::from_bits(float.to_bits().wrapping_add(1))
                } else {
                    $typ::from_bits(float.to_bits().wrapping_sub(1))
                }
            }

            #[must_use]
            // Returns the unit in last place using the definition by John Harrison.
            // This is the distance between `a` and the next closest float. Note that
            // `ulp(1) = $typ::EPSILON/2`.
            #[allow(clippy::single_call_fn, reason = "compute one unit-in-last-place step for the float uniform sampler's interval split")]
            fn ulp(float: $typ) -> $typ {
                if !float.is_finite() || float <= $typ::MIN {
                    return 0.;
                }
                core::ops::Sub::sub(float.abs(), next_down(float.abs()))
            }

            #[derive(Copy, Clone, Debug)]
            pub struct $wrapper($typ);

            impl From<$typ> for $wrapper {
                fn from(x: $typ) -> Self {
                    $wrapper(x)
                }
            }
            impl From<$wrapper> for $typ {
                fn from(x: $wrapper) -> Self {
                    x.0
                }
            }

            #[derive(Clone, Copy, Debug)]
            pub struct FloatUniform {
                low: $typ,
                high: $typ,
                intervals: Option<IntervalCollection>,
                inclusive: bool,
            }

            impl UniformSampler for FloatUniform {

                type X = $wrapper;

                fn new<B1, B2>(low: B1, high: B2) -> Result<Self, rand::distr::uniform::Error>
                where
                    B1: SampleBorrow<Self::X> + Sized,
                    B2: SampleBorrow<Self::X> + Sized,
                {
                    let low = low.borrow().0;
                    let high = high.borrow().0;
                    if !(low.is_finite() && high.is_finite()) {
                        return Err(rand::distr::uniform::Error::NonFinite);
                    }
                    if !float_greater(core::ops::Sub::sub(high, low), 0.) {
                        return Err(rand::distr::uniform::Error::EmptyRange);
                    }
                    Ok(FloatUniform {
                        low,
                        high,
                        intervals: Some(split_interval([low, high])),
                        inclusive: false,
                    })
                }

                fn new_inclusive<B1, B2>(low: B1, high: B2) -> Result<Self, rand::distr::uniform::Error>
                where
                    B1: SampleBorrow<Self::X> + Sized,
                    B2: SampleBorrow<Self::X> + Sized,
                {
                    let low = low.borrow().0;
                    let high = high.borrow().0;
                    if !(low.is_finite() && high.is_finite()) {
                        return Err(rand::distr::uniform::Error::NonFinite);
                    }
                    if low > high {
                        return Err(rand::distr::uniform::Error::EmptyRange);
                    }

                    // A single-point inclusive range is well-defined and yields `low`.
                    let intervals = if float_equal(low, high) {
                        None
                    } else {
                        Some(split_interval([low, high]))
                    };

                    Ok(FloatUniform {
                        low,
                        high,
                        intervals,
                        inclusive: true,
                    })
                }

                fn sample<R: Rng + ?Sized>(&self, rng: &mut R) -> Self::X {
                    let Some(initial) = self.intervals else {
                        return $wrapper(self.low);
                    };
                    let mut intervals = initial;
                    while intervals.count > 1 {
                        let new_interval = intervals.get(rng.random_range(0..intervals.count));
                        intervals = split_interval(new_interval);
                    }
                    let [lower_candidate, upper_candidate] = intervals.get(0);
                    let result = if rng.random_range(0..2) == 0 {
                        lower_candidate
                    } else {
                        upper_candidate
                    };

                    // These results could happen because the first split might
                    // overshoot one of the bounds. We could resample in this
                    // case but for testing data this is not a problem.
                    let clamped_result = if result < self.low {
                        self.low
                    } else if result > self.high{
                        self.high
                    } else {
                        result
                    };

                    if !self.inclusive && float_equal(clamped_result, self.high) {
                        return $wrapper(next_down(self.high));
                    };

                    $wrapper(clamped_result)
                }
            }

            impl SampleUniform for $wrapper {
                type Sampler = FloatUniform;
            }

            // Divides the range [low, high] into intervals of size epsilon * max(abs(low, high));
            // Note that the one interval may extend out of the range.
            #[derive(Clone, Copy, Debug)]
            struct IntervalCollection {
                start: $typ,
                step: $typ,
                count: $int_typ,
            }

            fn split_interval([low, high]: [$typ; 2]) -> IntervalCollection {
                    if !(low.is_finite() && high.is_finite())
                        || !float_greater(core::ops::Sub::sub(high, low), 0.)
                    {
                        return IntervalCollection {
                            start: low,
                            step: 0.,
                            count: 1,
                        };
                    }

                    let min_abs = $typ::min(low.abs(), high.abs());
                    let max_abs = $typ::max(low.abs(), high.abs());

                    let gap = ulp(max_abs);

                    let (start, step) = if low.abs() < high.abs() {
                        (high, core::ops::Neg::neg(gap))
                    } else {
                        (low, gap)
                    };

                    let min_gaps = core::ops::Div::div(min_abs, gap);
                    let max_gaps =
                        core::ops::Div::div(max_abs, gap).floor();

                    let count = if low.is_sign_negative() == high.is_sign_negative() {
                        sampler_index_from_float::<$typ, $int_typ>(
                            max_gaps,
                        )
                        .saturating_sub(sampler_index_from_float::<$typ, $int_typ>(
                            min_gaps.floor(),
                        ))
                    } else {
                        // `step` is a power of two so `min_gaps` won't be rounded
                        // except possibly to 0.
                        if float_is_zero(min_gaps) && min_abs > 0. {
                            sampler_index_from_float::<$typ, $int_typ>(
                                max_gaps,
                            ).saturating_add(1)
                        } else {
                            sampler_index_from_float::<$typ, $int_typ>(
                                max_gaps,
                            ).saturating_add(sampler_index_from_float::<$typ, $int_typ>(
                                min_gaps.ceil(),
                            ))
                        }
                    };

                    IntervalCollection {
                        start,
                        step,
                        count,
                    }
            }


            impl IntervalCollection {
                fn get(&self, index: $int_typ) -> [$typ; 2] {
                    let bounded_index =
                        index.min(self.count.saturating_sub(1));

                    // `index` might be greater that `MAX_PERCISE_INT`
                    // which means `MAX_PRECIST_INT as $typ` would round
                    // to a different number. Fortunately, `index` will
                    // never be larger than `2 * MAX_PRECISE_INT` (as
                    // asserted above).
                    let x = bounded_index.div_euclid(2).into_sampler_float().mul_add(
                        core::ops::Mul::mul(2., self.step),
                        bounded_index
                            .rem_euclid(2)
                            .into_sampler_float()
                            .mul_add(self.step, self.start),
                    );

                    let y = core::ops::Add::add(x, self.step);

                    if self.step > 0. {
                        [x, y]
                    } else {
                        [y, x]
                    }
                }
            }


            #[cfg(test)]
            // Values greater than MAX_PRECISE_INT may be rounded when converted to float.
            const MAX_PRECISE_INT: $int_typ =
                <$int_typ>::pow(2, $typ::MANTISSA_DIGITS);

            #[cfg(test)]
            mod test {

                use strict_test_support::{
                    TestFailure, ensure, ensure_eq, ensure_ok, ensure_some,
                };

                use super::*;
                use super::super::{
                    sampler_count_to_usize, sampler_index_from_usize,
                    sampler_round_trip_integer,
                };
                use crate::prelude::*;
                use crate::test_runner::test_runner_without_persistence;

                #[test]
                fn uniform_constructors_accept_valid_ranges()
                -> Result<(), TestFailure> {
                    ensure(
                        FloatUniform::new($wrapper(1.), $wrapper(2.)).is_ok(),
                        "new accepts a finite non-empty range",
                    )?;
                    ensure(
                        FloatUniform::new_inclusive(
                            $wrapper(1.),
                            $wrapper(1.),
                        )
                        .is_ok(),
                        "new_inclusive accepts a single-point range",
                    )
                }

                #[test]
                fn uniform_constructors_reject_invalid_ranges()
                -> Result<(), TestFailure> {
                    ensure(
                        matches!(
                            FloatUniform::new($wrapper(2.), $wrapper(1.)),
                            Err(rand::distr::uniform::Error::EmptyRange)
                        ),
                        "new rejects a reversed range as empty",
                    )?;
                    ensure(
                        matches!(
                            FloatUniform::new($wrapper(1.), $wrapper(1.)),
                            Err(rand::distr::uniform::Error::EmptyRange)
                        ),
                        "new rejects a single-point exclusive range as empty",
                    )?;
                    ensure(
                        matches!(
                            FloatUniform::new(
                                $wrapper($typ::NAN),
                                $wrapper(1.),
                            ),
                            Err(rand::distr::uniform::Error::NonFinite)
                        ),
                        "new rejects a non-finite bound",
                    )?;
                    ensure(
                        matches!(
                            FloatUniform::new_inclusive(
                                $wrapper(2.),
                                $wrapper(1.),
                            ),
                            Err(rand::distr::uniform::Error::EmptyRange)
                        ),
                        "new_inclusive rejects a reversed range as empty",
                    )
                }

                #[allow(clippy::single_call_fn, reason = "test-only helper ordering a float pair before the uniform sampler round-trip check")]
                fn sort((left, right): ($typ, $typ)) -> [$typ; 2] {
                    if left < right {
                        [left, right]
                    } else {
                        [right, left]
                    }
                }

                fn finite() -> impl Strategy<Value = $typ> {
                    prop::num::$typ::NEGATIVE
                    | prop::num::$typ::POSITIVE
                    | prop::num::$typ::NORMAL
                    | prop::num::$typ::SUBNORMAL
                    | prop::num::$typ::ZERO
                }

                fn finite_above_min() -> impl Strategy<Value = $typ> {
                    // The legacy tests rejected `MIN` with `prop_assume!`;
                    // the precondition lives in the strategy instead.
                    finite().prop_filter(
                        "value must be above the type minimum",
                        |val| *val > $typ::MIN,
                    )
                }

                fn bounds() -> impl Strategy<Value = [$typ; 2]> {
                    (finite(), finite())
                        .prop_filter("Bounds can't be equal", |&(left, right)| {
                            !float_equal(left, right)
                        })
                        .prop_map(sort)
                }

                #[test]
                fn range_test() -> Result<(), TestFailure> {
                    use crate::test_runner::{RngAlgorithm, TestRng};

                    let mut test_rng = TestRng::deterministic_rng(RngAlgorithm::default());
                    let (low, high) = (-1., 10.);
                    let uniform = ensure_ok(
                        FloatUniform::new($wrapper(low), $wrapper(high)),
                        "the bounds form a uniform sampler",
                    )?;

                    let samples = (0..100)
                        .map(|_| $typ::from(uniform.sample(&mut test_rng)));
                    for sample in samples {
                        ensure(
                            low <= sample && sample < high,
                            "every sample stays within the half-open range",
                        )?;
                    }
                    Ok(())
                }

                #[test]
                fn range_end_bound_test() -> Result<(), TestFailure> {
                    use crate::test_runner::{RngAlgorithm, TestRng};

                    let mut test_rng = TestRng::deterministic_rng(RngAlgorithm::default());
                    let (low, high) = (1., 1. + $typ::EPSILON);
                    let uniform = ensure_ok(
                        FloatUniform::new($wrapper(low), $wrapper(high)),
                        "the bounds form a uniform sampler",
                    )?;

                    let mut samples = (0..100)
                        .map(|_| $typ::from(uniform.sample(&mut test_rng)));
                    ensure(
                        samples.all(|x| float_bits_equal(x, 1.)),
                        "a one-ulp half-open range only yields its base",
                    )
                }

                #[test]
                fn inclusive_range_test() -> Result<(), TestFailure> {
                    use crate::test_runner::{RngAlgorithm, TestRng};

                    let mut test_rng = TestRng::deterministic_rng(RngAlgorithm::default());
                    let (low, high) = (-1., 10.);
                    let uniform = ensure_ok(
                        FloatUniform::new_inclusive($wrapper(low), $wrapper(high)),
                        "the bounds form a uniform sampler",
                    )?;

                    let samples = (0..100)
                        .map(|_| $typ::from(uniform.sample(&mut test_rng)));
                    for sample in samples {
                        ensure(
                            low <= sample && sample <= high,
                            "every sample stays within the inclusive range",
                        )?;
                    }
                    Ok(())
                }

                #[test]
                fn inclusive_range_end_bound_test() -> Result<(), TestFailure> {
                    use crate::test_runner::{RngAlgorithm, TestRng};

                    let mut test_rng = TestRng::deterministic_rng(RngAlgorithm::default());
                    let (low, high) = (1., 1. + $typ::EPSILON);
                    let uniform = ensure_ok(
                        FloatUniform::new_inclusive($wrapper(low), $wrapper(high)),
                        "the bounds form a uniform sampler",
                    )?;

                    let mut samples = (0..100)
                        .map(|_| $typ::from(uniform.sample(&mut test_rng)));
                    ensure(
                        samples.any(|x| {
                            float_bits_equal(x, 1. + $typ::EPSILON)
                        }),
                        "the inclusive end bound is sampled",
                    )
                }

                #[test]
                fn inclusive_range_single_point() -> Result<(), TestFailure> {
                    use crate::test_runner::{RngAlgorithm, TestRng};

                    let mut test_rng = TestRng::deterministic_rng(RngAlgorithm::default());
                    let point: $typ = 0.0;
                    let uniform = ensure_ok(
                        FloatUniform::new_inclusive($wrapper(point), $wrapper(point)),
                        "a single-point range forms a uniform sampler",
                    )?;
                    for _ in 0..16 {
                        ensure_eq(
                            &$typ::from(uniform.sample(&mut test_rng)),
                            &point,
                            "a single-point range always yields its point",
                        )?;
                    }
                    Ok(())
                }

                #[test]
                fn inclusive_range_single_point_strategy() -> Result<(), TestFailure> {
                    use crate::strategy::{Strategy, ValueTree};

                    let mut runner = test_runner_without_persistence();
                    let mid: $typ = 1.5;
                    let tree = ensure_some(
                        (mid..=mid).new_tree(&mut runner).ok(),
                        "a single-point inclusive range generates a value tree",
                    )?;
                    ensure_eq(
                        &tree.current(),
                        &mid,
                        "the single-point strategy yields its point",
                    )
                }

                #[test]
                fn all_floats_in_range_are_possible_1() -> Result<(), TestFailure> {
                    use crate::test_runner::{RngAlgorithm, TestRng};

                    let mut test_rng = TestRng::deterministic_rng(RngAlgorithm::default());
                    let (low, high) = (1. - $typ::EPSILON, 1. + $typ::EPSILON);
                    let uniform = ensure_ok(
                        FloatUniform::new_inclusive($wrapper(low), $wrapper(high)),
                        "the bounds form a uniform sampler",
                    )?;

                    let mut samples = (0..100)
                        .map(|_| $typ::from(uniform.sample(&mut test_rng)));
                    ensure(
                        samples.any(|x| {
                            float_bits_equal(x, 1. - $typ::EPSILON / 2.)
                        }),
                        "an interior float of the range is sampled",
                    )
                }

                #[test]
                fn all_floats_in_range_are_possible_2() -> Result<(), TestFailure> {
                    use crate::test_runner::{RngAlgorithm, TestRng};

                    let mut test_rng = TestRng::deterministic_rng(RngAlgorithm::default());
                    let (low, high) =
                        (0., MAX_PRECISE_INT.into_sampler_float());
                    let uniform = ensure_ok(
                        FloatUniform::new_inclusive($wrapper(low), $wrapper(high)),
                        "the bounds form a uniform sampler",
                    )?;

                    let mut samples = (0..100)
                        .map(|_| $typ::from(uniform.sample(&mut test_rng)))
                        .map(|x| x.fract());

                    ensure(
                        samples.any(|x| !float_is_zero(x)),
                        "fractional values are sampled across the range",
                    )
                }

                #[test]
                fn max_precise_int_plus_one_is_rounded_down() -> Result<(), TestFailure> {
                    ensure_eq(
                        &sampler_round_trip_integer::<$typ, $int_typ>(
                            MAX_PRECISE_INT + 1,
                        ),
                        &MAX_PRECISE_INT,
                        "the first imprecise integer rounds back down",
                    )
                }

                #[test]
                fn next_down_less_than_float() -> Result<(), TestFailure> {
                    crate::strict::ensure_property(
                        &finite_above_min(),
                        "next_down is strictly below its input",
                        |val| {
                            ensure(
                                next_down(val) < val,
                                "next_down yields a smaller float",
                            )
                        },
                    )
                }

                #[test]
                fn no_value_between_float_and_next_down() -> Result<(), TestFailure> {
                    crate::strict::ensure_property(
                        &finite_above_min(),
                        "next_down is the immediate predecessor",
                        |val| {
                            let prev = next_down(val);
                            let avg = prev / 2. + val / 2.;
                            ensure(
                                float_bits_equal(avg, prev) ||
                                    float_bits_equal(avg, val),
                                "no float lies between a value and its \
                                 next_down",
                            )
                        },
                    )
                }

                #[test]
                fn values_less_than_or_equal_to_max_precise_int_are_not_rounded() -> Result<(), TestFailure> {
                    crate::strict::ensure_property(
                        &(0..=MAX_PRECISE_INT),
                        "precise integers survive a float round trip",
                        |i| {
                            ensure_eq(
                                &sampler_round_trip_integer::<$typ, $int_typ>(i),
                                &i,
                                "the round-tripped integer is unchanged",
                            )
                        },
                    )
                }

                #[test]
                fn indivisible_intervals_are_split_to_self() -> Result<(), TestFailure> {
                    crate::strict::ensure_property(
                        &finite_above_min(),
                        "a one-ulp interval is indivisible",
                        |val| {
                            let prev = next_down(val);
                            let intervals = split_interval([prev, val]);
                            ensure_eq(
                                &intervals.count,
                                &1,
                                "the indivisible interval splits to itself",
                            )
                        },
                    )
                }

                #[test]
                fn split_intervals_are_the_same_size() -> Result<(), TestFailure> {
                    // The legacy test `prop_assume!`d a non-trivial split;
                    // the precondition lives in the strategy filter instead.
                    let inputs = (bounds(), any::<[prop::sample::Index; 32]>())
                        .prop_filter(
                            "the bounds must split into at least two \
                             intervals",
                            |&(bounds, _)| {
                                split_interval(bounds).count > 1
                            },
                        );
                    crate::strict::ensure_property(
                        &inputs,
                        "split intervals share one width",
                        |(bounds, indices)| {
                            let intervals = split_interval(bounds);
                            let size = sampler_count_to_usize::<$typ, $int_typ>(
                                intervals.count - 1,
                            );

                            let (first_index, remaining_indices) = ensure_some(
                                indices.split_first(),
                                "at least one interval is sampled",
                            )?;
                            let first_index = ensure_some(
                                first_index.index(size),
                                "the first sampled split index is in range",
                            )?;
                            let [low, high] = intervals.get(
                                sampler_index_from_usize::<$typ, $int_typ>(
                                    first_index,
                                ),
                            );
                            let interval_size = high - low;

                            for index in remaining_indices {
                                let index = ensure_some(
                                    index.index(size),
                                    "the sampled split index is in range",
                                )?;
                                let [low, high] = intervals.get(
                                    sampler_index_from_usize::<$typ, $int_typ>(
                                        index,
                                    ),
                                );
                                let width = high - low;
                                ensure(
                                    float_bits_equal(width, interval_size),
                                    "every sampled interval has the same \
                                     width",
                                )?;
                            }
                            Ok(())
                        },
                    )
                }

                #[test]
                fn split_intervals_are_consecutive() -> Result<(), TestFailure> {
                    let inputs = (bounds(), any::<[prop::sample::Index; 32]>())
                        .prop_filter(
                            "the bounds must split into at least three \
                             intervals",
                            |&(bounds, _)| {
                                split_interval(bounds).count > 2
                            },
                        );
                    crate::strict::ensure_property(
                        &inputs,
                        "split intervals are consecutive",
                        |(bounds, indices)| {
                            let intervals = split_interval(bounds);
                            let size = sampler_count_to_usize::<$typ, $int_typ>(
                                intervals.count - 1,
                            );

                            let mut ascending = true;
                            let mut descending = true;
                            for index in &indices {
                                let index = ensure_some(
                                    index.index(size - 1),
                                    "the sampled adjacent split index is in \
                                     range",
                                )?;
                                let index =
                                    sampler_index_from_usize::<$typ, $int_typ>(
                                        index,
                                    );
                                let [l1, h1] = intervals.get(index);
                                let [l2, h2] = intervals.get(index + 1);
                                ascending &= float_bits_equal(h1, l2);
                                descending &= float_bits_equal(l1, h2);
                            }

                            ensure(
                                ascending || descending,
                                "adjacent intervals share a bound in one \
                                 direction",
                            )
                        },
                    )
                }

                #[test]
                fn first_split_might_slightly_overshoot_one_bound() -> Result<(), TestFailure> {
                    crate::strict::ensure_property(
                        &bounds(),
                        "the first split covers the bounds with at most one \
                         overshoot",
                        |bounds| {
                            let [low, high] = bounds;
                            let intervals = split_interval(bounds);
                            let start = intervals.get(0);
                            let end = intervals.get(intervals.count - 1);
                            let (low_interval, high_interval) = if start[0] < end[0] {
                                (start, end)
                            } else {
                                (end, start)
                            };
                            let lower_bound_matches =
                                float_bits_equal(low, low_interval[0]) &&
                                    high_interval[0] < high &&
                                    high <= high_interval[1];
                            let upper_bound_matches =
                                low_interval[0] <= low &&
                                    low < low_interval[1] &&
                                    float_bits_equal(high, high_interval[1]);

                            ensure(
                                lower_bound_matches || upper_bound_matches,
                                "exactly one bound may overshoot",
                            )
                        },
                    )
                }

                #[test]
                fn subsequent_splits_always_match_bounds() -> Result<(), TestFailure> {
                    crate::strict::ensure_property(
                        &(bounds(), any::<prop::sample::Index>()),
                        "recursive splits stay within their interval",
                        |(bounds, index)| {
                            // This property is true because the distances of split intervals of
                            // are powers of two so the smaller one always divides the larger.

                            let intervals = split_interval(bounds);
                            let size = sampler_count_to_usize::<$typ, $int_typ>(
                                intervals.count - 1,
                            );

                            let index = ensure_some(
                                index.index(size),
                                "the sampled recursive split index is in \
                                 range",
                            )?;
                            let interval = intervals.get(
                                sampler_index_from_usize::<$typ, $int_typ>(
                                    index,
                                ),
                            );
                            let small_intervals = split_interval(interval);

                            let start = small_intervals.get(0);
                            let end = small_intervals.get(small_intervals.count - 1);
                            let (low_interval, high_interval) = if start[0] < end[0] {
                                (start, end)
                            } else {
                                (end, start)
                            };

                            ensure(
                                float_bits_equal(interval[0], low_interval[0]) &&
                                float_bits_equal(interval[1], high_interval[1]),
                                "the sub-split spans exactly its parent \
                                 interval",
                            )
                        },
                    )
                }
            }
        }
    };
}

#[cfg(feature = "f16")]
float_sampler!(f16, u16, F16U);
float_sampler!(f32, u32, F32U, no_std_trait = num_traits::float::Float);
float_sampler!(f64, u64, F64U, no_std_trait = num_traits::float::Float);
