//-
// Copyright 2022 The proptest developers
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

//! Alternative uniform float samplers.
//! These samplers are used over the ones from `rand` because the ones provided by the
//! rand crate are prone to overflow. In addition, these are 'high precision' samplers
//! that are more appropriate for test data.
//! The samplers work by splitting the range into equally sized intervals and selecting
//! an iterval at random. That interval is then itself split and a new interval is
//! selected at random. The process repeats until the interval only contains two
//! floating point values at the bounds. At that stage, one is selected at random and
//! returned.

use num_traits::ToPrimitive as _;

#[cfg(all(feature = "f16", not(feature = "alt-stable")))]
pub(super) use self::f16::F16U;
pub(super) use self::f32::F32U;
pub(super) use self::f64::F64U;
#[cfg(feature = "alt-stable")]
pub(super) use self::half_f16::HalfF16U;

/// Convert the sampler's unsigned interval index into its float type.
trait IntoSamplerFloat<F> {
  /// Perform the integer-to-float conversion used by the sampler math.
  fn into_sampler_float(self) -> F;
}

/// Convert between a sampler's float and integer index spaces.
trait SamplerIndex<F>: Sized {
  /// Convert an integral float value into the sampler's integer index.
  fn from_sampler_float(float: F) -> Self;

  /// Convert a `usize` generated by an index strategy into the sampler index.
  #[cfg(all(test, feature = "strict-test"))]
  fn from_usize_index(index: usize) -> Self;

  /// Convert a sampler interval count into a `usize` range bound.
  #[cfg(all(test, feature = "strict-test"))]
  fn into_usize_count(self) -> usize;
}

/// Share conversion trait wiring while preserving each float's rounding and
/// each integer's checked or infallible count conversion.
macro_rules! sampler_conversions {
  ($float:ty, $integer:ty; $index:ident => $to_float:expr; $value:ident => $to_index:expr; $count:ident => $to_count:expr) => {
    impl IntoSamplerFloat<$float> for $integer {
      fn into_sampler_float(self) -> $float {
        let $index = self;
        $to_float
      }
    }

    impl SamplerIndex<$float> for $integer {
      fn from_sampler_float($value: $float) -> Self {
        $to_index
      }

      #[cfg(all(test, feature = "strict-test"))]
      fn from_usize_index(index: usize) -> Self {
        Self::try_from(index).unwrap_or(Self::MAX)
      }

      #[cfg(all(test, feature = "strict-test"))]
      fn into_usize_count(self) -> usize {
        let $count = self;
        $to_count
      }
    }
  };
}

#[cfg(all(feature = "f16", not(feature = "alt-stable")))]
sampler_conversions!(f16, u16;
  index => f16::from_bits(f16_bits_from_sampler_index(index));
  float => sampler_index_from_f16_bits(float.to_bits());
  count => usize::from(count)
);

#[cfg(feature = "alt-stable")]
sampler_conversions!(half::f16, u16;
  index => half::f16::from_bits(f16_bits_from_sampler_index(index));
  float => sampler_index_from_f16_bits(float.to_bits());
  count => usize::from(count)
);

sampler_conversions!(f32, u32;
  index => index.to_f32().unwrap_or(f32::INFINITY);
  float => float.to_u32().unwrap_or(Self::MAX);
  count => usize::try_from(count).unwrap_or(usize::MAX)
);

sampler_conversions!(f64, u64;
  index => index.to_f64().unwrap_or(f64::INFINITY);
  float => float.to_u64().unwrap_or(Self::MAX);
  count => usize::try_from(count).unwrap_or(usize::MAX)
);

/// Convert a nonnegative sampler index into an IEEE 754 half-precision value.
#[cfg(any(all(feature = "f16", not(feature = "alt-stable")), feature = "alt-stable"))]
#[allow(
  clippy::single_call_fn,
  reason = "name the half-precision sampler-index to f16 bit-layout conversion used by the f16 sampler trait impl"
)]
fn f16_bits_from_sampler_index(sampler_index: u16) -> u16 {
  const SIGNIFICAND_BITS: u32 = 10;
  const EXPONENT_BIAS: u32 = 15;
  const EXPONENT_MASK: u16 = 0x7c00;
  const MANTISSA_MASK: u16 = 0x03ff;
  const HIDDEN_BIT: u16 = 0x0400;

  if sampler_index == 0 {
    return 0;
  }

  let highest_bit = u16::BITS.saturating_sub(1).saturating_sub(sampler_index.leading_zeros());
  let mut exponent = highest_bit.saturating_add(EXPONENT_BIAS);
  let mantissa = if highest_bit <= SIGNIFICAND_BITS {
    let shift = SIGNIFICAND_BITS.saturating_sub(highest_bit);
    sampler_index.checked_shl(shift).unwrap_or(0) & MANTISSA_MASK
  } else {
    let shift = highest_bit.saturating_sub(SIGNIFICAND_BITS);
    let significand = sampler_index >> shift;
    let base = significand.checked_shl(shift).unwrap_or(0);
    let remainder = sampler_index.saturating_sub(base);
    let halfway = 1_u16.checked_shl(shift.saturating_sub(1)).unwrap_or(0);
    let rounds_to_even = remainder == halfway && significand & 1 != 0;
    let round_up = remainder > halfway || rounds_to_even;
    let rounded = significand.saturating_add(u16::from(round_up));
    if rounded == HIDDEN_BIT.checked_shl(1).unwrap_or(0) {
      exponent = exponent.saturating_add(1);
      0
    } else {
      rounded & MANTISSA_MASK
    }
  };

  if exponent >= 0x1f {
    return EXPONENT_MASK;
  }

  let exponent_bits = u16::try_from(exponent).unwrap_or(0).checked_shl(SIGNIFICAND_BITS).unwrap_or(0);
  exponent_bits | mantissa
}

/// Convert a nonnegative integral half-precision value into a sampler index.
#[cfg(any(all(feature = "f16", not(feature = "alt-stable")), feature = "alt-stable"))]
#[allow(
  clippy::single_call_fn,
  reason = "name the f16 bit-layout to sampler-index conversion used by the f16 sampler trait impl"
)]
fn sampler_index_from_f16_bits(bits: u16) -> u16 {
  const SIGNIFICAND_BITS: u32 = 10;
  const EXPONENT_BIAS: i32 = 15;
  const EXPONENT_MASK: u16 = 0x1f;
  const MANTISSA_MASK: u16 = 0x03ff;
  const HIDDEN_BIT: u16 = 0x0400;
  const SIGN_BIT: u16 = 0x8000;

  if bits & SIGN_BIT != 0 {
    return 0;
  }

  let exponent_bits = (bits >> SIGNIFICAND_BITS) & EXPONENT_MASK;
  if exponent_bits == 0 {
    return 0;
  }
  if exponent_bits == EXPONENT_MASK {
    return u16::MAX;
  }

  let exponent = i32::from(exponent_bits).checked_sub(EXPONENT_BIAS).unwrap_or(i32::MIN);
  if exponent < 0 {
    return 0;
  }

  let significand = u32::from(HIDDEN_BIT | (bits & MANTISSA_MASK));
  let magnitude = if exponent >= i32::try_from(SIGNIFICAND_BITS).unwrap_or(0) {
    let shift = u32::try_from(exponent).unwrap_or(0).saturating_sub(SIGNIFICAND_BITS);
    significand.checked_shl(shift).unwrap_or(u32::MAX)
  } else {
    let shift = SIGNIFICAND_BITS.saturating_sub(u32::try_from(exponent).unwrap_or(0));
    significand >> shift
  };

  u16::try_from(magnitude).unwrap_or(u16::MAX)
}

/// Convert an integral float value into its sampler integer index.
fn sampler_index_from_float<F, I>(float: F) -> I
where
  I: SamplerIndex<F>,
{
  I::from_sampler_float(float)
}

#[cfg(all(test, feature = "strict-test"))]
fn sampler_index_from_usize<F, I>(index: usize) -> I
where
  I: SamplerIndex<F>,
{
  I::from_usize_index(index)
}

#[cfg(all(test, feature = "strict-test"))]
fn sampler_count_to_usize<F, I>(index_count: I) -> usize
where
  I: SamplerIndex<F>,
{
  index_count.into_usize_count()
}

#[cfg(test)]
fn sampler_round_trip_integer<F, I>(value: I) -> I
where
  I: IntoSamplerFloat<F> + SamplerIndex<F>,
{
  I::from_sampler_float(value.into_sampler_float())
}

/// Defines a high-precision uniform float sampler module for one float type.
///
/// Emits a `pub mod` (named after `$typ`) providing a `FloatUniform`
/// (`impl UniformSampler`) and the `$wrapper` newtype (`F32U`/`F64U`/`F16U`)
/// that `num` samples through. The sampler recursively splits the range into
/// equal-width intervals and descends until a single ULP remains, avoiding the
/// overflow and precision loss of `rand`'s float `Uniform`.
macro_rules! float_sampler {
    (
        module = $module: ident,
        type = $typ: ident
        $(, type_path = $type_path:path)?,
        int = $int_typ: ident,
        wrapper = $wrapper: ident,
        neg_one = $neg_one: expr,
        zero = $zero: expr,
        one = $one: expr,
        two = $two: expr,
        ten = $ten: expr,
        one_point_five = $one_point_five: expr,
        half = $half: expr
        $(, always_trait = $always_trait:path)?
    ) => {
        mod $module {
            use super::{IntoSamplerFloat, sampler_index_from_float};
            use rand::prelude::*;
            use rand::distr::uniform::{
                SampleBorrow, SampleUniform, UniformSampler,
            };
            $(
                use $type_path as $typ;
            )?
            $(
                use $always_trait as _;
            )?
            const ZERO: $typ = $zero;
            const TWO: $typ = $two;
            #[cfg(test)]
            const NEG_ONE: $typ = $neg_one;
            #[cfg(test)]
            const ONE: $typ = $one;
            #[cfg(test)]
            const TEN: $typ = $ten;
            #[cfg(test)]
            const ONE_POINT_FIVE: $typ = $one_point_five;
            #[cfg(test)]
            const HALF: $typ = $half;

            #[must_use]
            fn float_equal(left: $typ, right: $typ) -> bool {
                matches!(
                    left.partial_cmp(&right),
                    Some(core::cmp::Ordering::Equal)
                )
            }

            #[must_use]
            fn float_greater(left: $typ, right: $typ) -> bool {
                matches!(
                    left.partial_cmp(&right),
                    Some(core::cmp::Ordering::Greater)
                )
            }

            #[must_use]
            const fn float_is_zero(float: $typ) -> bool {
                matches!(float.classify(), core::num::FpCategory::Zero)
            }

            #[cfg(test)]
            #[must_use]
            const fn float_bits_equal(left: $typ, right: $typ) -> bool {
                left.to_bits() == right.to_bits()
            }

            #[must_use]
            // Returns the previous float value. In other words the greatest value representable
            // as a float such that `next_down(float) < float`. `-0.` is treated as `0.`.
            fn next_down(float: $typ) -> $typ {
                if !float.is_finite() {
                    return float;
                }
                if float <= $typ::MIN {
                    return $typ::MIN;
                }
                if float_is_zero(float) {
                    core::ops::Neg::neg($typ::from_bits(1))
                } else if float < ZERO {
                    $typ::from_bits(float.to_bits().wrapping_add(1))
                } else {
                    $typ::from_bits(float.to_bits().wrapping_sub(1))
                }
            }

            #[must_use]
            // Returns the unit in last place using the definition by John Harrison.
            // This is the distance between `a` and the next closest float. Note that
            // `ulp(1) = $typ::EPSILON/2`.
            #[allow(clippy::single_call_fn, reason = "compute one unit-in-last-place step for the float uniform sampler's interval split")]
            fn ulp(float: $typ) -> $typ {
                if !float.is_finite() || float <= $typ::MIN {
                    return ZERO;
                }
                core::ops::Sub::sub(float.abs(), next_down(float.abs()))
            }

            #[derive(Copy, Clone, Debug)]
            pub struct $wrapper($typ);

            impl From<$typ> for $wrapper {
                fn from(x: $typ) -> Self {
                    $wrapper(x)
                }
            }
            impl From<$wrapper> for $typ {
                fn from(x: $wrapper) -> Self {
                    x.0
                }
            }

            #[derive(Clone, Copy, Debug)]
            pub struct FloatUniform {
                low: $typ,
                high: $typ,
                intervals: Option<IntervalCollection>,
                inclusive: bool,
            }

            impl FloatUniform {
                /// Validate bounds and retain the selected endpoint semantics.
                fn from_bounds(low: $typ, high: $typ, inclusive: bool) -> Result<Self, rand::distr::uniform::Error> {
                    if !(low.is_finite() && high.is_finite()) {
                        return Err(rand::distr::uniform::Error::NonFinite);
                    }
                    let empty = if inclusive {
                        low > high
                    } else {
                        !float_greater(core::ops::Sub::sub(high, low), ZERO)
                    };
                    if empty {
                        return Err(rand::distr::uniform::Error::EmptyRange);
                    }
                    // Equal inclusive bounds preserve the exact lower value,
                    // including its sign when the endpoints are signed zeros.
                    let intervals = if inclusive && float_equal(low, high) {
                        None
                    } else {
                        Some(split_interval([low, high]))
                    };
                    Ok(Self { low, high, intervals, inclusive })
                }
            }

            impl UniformSampler for FloatUniform {

                type X = $wrapper;

                fn new<B1, B2>(low: B1, high: B2) -> Result<Self, rand::distr::uniform::Error>
                where
                    B1: SampleBorrow<Self::X> + Sized,
                    B2: SampleBorrow<Self::X> + Sized,
                {
                    Self::from_bounds(low.borrow().0, high.borrow().0, false)
                }

                fn new_inclusive<B1, B2>(low: B1, high: B2) -> Result<Self, rand::distr::uniform::Error>
                where
                    B1: SampleBorrow<Self::X> + Sized,
                    B2: SampleBorrow<Self::X> + Sized,
                {
                    Self::from_bounds(low.borrow().0, high.borrow().0, true)
                }

                fn sample<R: Rng + ?Sized>(&self, rng: &mut R) -> Self::X {
                    let Some(initial) = self.intervals else {
                        return $wrapper(self.low);
                    };
                    let mut intervals = initial;
                    while intervals.count > 1 {
                        let new_interval = intervals.get(rng.random_range(0..intervals.count));
                        intervals = split_interval(new_interval);
                    }
                    let [lower_candidate, upper_candidate] = intervals.get(0);
                    let result = if rng.random_range(0..2) == 0 {
                        lower_candidate
                    } else {
                        upper_candidate
                    };

                    // These results could happen because the first split might
                    // overshoot one of the bounds. We could resample in this
                    // case but for testing data this is not a problem.
                    let clamped_result = if result < self.low {
                        self.low
                    } else if result > self.high{
                        self.high
                    } else {
                        result
                    };

                    if !self.inclusive && float_equal(clamped_result, self.high) {
                        return $wrapper(next_down(self.high));
                    };

                    $wrapper(clamped_result)
                }
            }

            impl SampleUniform for $wrapper {
                type Sampler = FloatUniform;
            }

            // Divides the range [low, high] into intervals of size epsilon * max(abs(low, high));
            // Note that the one interval may extend out of the range.
            #[derive(Clone, Copy, Debug)]
            struct IntervalCollection {
                start: $typ,
                step: $typ,
                count: $int_typ,
            }

            fn split_interval([low, high]: [$typ; 2]) -> IntervalCollection {
                    if !(low.is_finite() && high.is_finite())
                        || !float_greater(core::ops::Sub::sub(high, low), ZERO)
                    {
                        return IntervalCollection {
                            start: low,
                            step: ZERO,
                            count: 1,
                        };
                    }

                    let min_abs = $typ::min(low.abs(), high.abs());
                    let max_abs = $typ::max(low.abs(), high.abs());

                    let gap = ulp(max_abs);

                    let (start, step) = if low.abs() < high.abs() {
                        (high, core::ops::Neg::neg(gap))
                    } else {
                        (low, gap)
                    };

                    let min_gaps = core::ops::Div::div(min_abs, gap);
                    let max_gaps =
                        core::ops::Div::div(max_abs, gap).floor();

                    let count = if low.is_sign_negative() == high.is_sign_negative() {
                        sampler_index_from_float::<$typ, $int_typ>(
                            max_gaps,
                        )
                        .saturating_sub(sampler_index_from_float::<$typ, $int_typ>(
                            min_gaps.floor(),
                        ))
                    } else {
                        // `step` is a power of two so `min_gaps` won't be rounded
                        // except possibly to 0.
                        if float_is_zero(min_gaps) && min_abs > ZERO {
                            sampler_index_from_float::<$typ, $int_typ>(
                                max_gaps,
                            ).saturating_add(1)
                        } else {
                            sampler_index_from_float::<$typ, $int_typ>(
                                max_gaps,
                            ).saturating_add(sampler_index_from_float::<$typ, $int_typ>(
                                min_gaps.ceil(),
                            ))
                        }
                    };

                    IntervalCollection {
                        start,
                        step,
                        count,
                    }
            }


            impl IntervalCollection {
                fn get(&self, index: $int_typ) -> [$typ; 2] {
                    let bounded_index =
                        index.min(self.count.saturating_sub(1));

                    // `index` might be greater that `MAX_PERCISE_INT`
                    // which means `MAX_PRECIST_INT as $typ` would round
                    // to a different number. Fortunately, `index` will
                    // never be larger than `2 * MAX_PRECISE_INT` (as
                    // asserted above).
                    let x = bounded_index.div_euclid(2).into_sampler_float().mul_add(
                        core::ops::Mul::mul(TWO, self.step),
                        bounded_index
                            .rem_euclid(2)
                            .into_sampler_float()
                            .mul_add(self.step, self.start),
                    );

                    let y = core::ops::Add::add(x, self.step);

                    if self.step > ZERO {
                        [x, y]
                    } else {
                        [y, x]
                    }
                }
            }


            #[cfg(test)]
            // Values greater than MAX_PRECISE_INT may be rounded when converted to float.
            const MAX_PRECISE_INT: $int_typ =
                <$int_typ>::pow(2, $typ::MANTISSA_DIGITS);

            #[cfg(test)]
            mod test {
                use strict_test_support::{ComparisonFailure, PredicateFailure, ensure_eq, ensure_that};
                use super::*;
                use super::super::sampler_round_trip_integer;
                #[cfg(feature = "strict-test")]
                use super::super::{sampler_count_to_usize, sampler_index_from_usize};
                #[cfg(feature = "strict-test")]
                use crate::prelude::*;
                use crate::std_facade::{Box, Vec};
                use crate::strategy::{Strategy, ValueTree};
                use crate::test_runner::{Reason, RngAlgorithm, TestRng, test_runner_without_persistence};
                #[cfg(feature = "strict-test")]
                use crate::test_runner::PropertyResult;

                /// Native constructor outcomes are retained even for invalid bounds.
                type Constructor = Result<FloatUniform, rand::distr::uniform::Error>;
                /// The sampler remains available alongside every native sample.
                type Samples = Result<(FloatUniform, Vec<$typ>), rand::distr::uniform::Error>;
                /// Requested endpoints paired with their constructed sampler and samples.
                type SampledRange = (($typ, $typ), Samples);
                /// Typed outcomes of the float properties using whole-subject predicates.
                #[cfg(feature = "strict-test")]
                type Property<V, A> = PropertyResult<V, A, Box<PredicateFailure<A>>>;
                /// A concrete allocation preserves a complete assertion subject.
                type Check<S> = Result<(), Box<PredicateFailure<S>>>;

                /// Sample a constructed distribution without projecting construction errors.
                fn samples(constructor: Constructor, count: usize) -> Samples {
                    constructor.map(|uniform| {
                        let mut rng = TestRng::deterministic_rng(RngAlgorithm::default());
                        let values = (0..count).map(|_| $typ::from(uniform.sample(&mut rng))).collect();
                        (uniform, values)
                    })
                }

                #[test]
                fn uniform_constructors_accept_valid_ranges() -> Check<[Constructor; 2]> {
                    ensure_that([
                        FloatUniform::new($wrapper(ONE), $wrapper(TWO)),
                        FloatUniform::new_inclusive($wrapper(ONE), $wrapper(ONE)),
                    ], "finite nonempty and inclusive single-point ranges construct samplers", |results| {
                        results.iter().all(Result::is_ok)
                    }).map_err(Box::new).map(drop)
                }

                #[test]
                fn uniform_constructors_reject_invalid_ranges() -> Check<[Constructor; 5]> {
                    use rand::distr::uniform::Error::{EmptyRange, NonFinite};
                    ensure_that([
                        FloatUniform::new($wrapper(TWO), $wrapper(ONE)),
                        FloatUniform::new($wrapper(ONE), $wrapper(ONE)),
                        FloatUniform::new($wrapper($typ::NAN), $wrapper(ONE)),
                        FloatUniform::new_inclusive($wrapper(TWO), $wrapper(ONE)),
                        FloatUniform::new_inclusive($wrapper(ONE), $wrapper($typ::INFINITY)),
                    ], "invalid ranges preserve the native constructor errors", |results| {
                        matches!(*results, [Err(EmptyRange), Err(EmptyRange), Err(NonFinite), Err(EmptyRange), Err(NonFinite)])
                    }).map_err(Box::new).map(drop)
                }

                #[cfg(feature = "strict-test")]
                #[allow(clippy::single_call_fn, reason = "sorting finite endpoints names the range invariant before constructing a sampler")]
                fn sort((left, right): ($typ, $typ)) -> [$typ; 2] {
                    if left < right { [left, right] } else { [right, left] }
                }

                #[cfg(feature = "strict-test")]
                fn finite() -> impl Strategy<Value = $typ> {
                    prop::num::$module::NEGATIVE | prop::num::$module::POSITIVE
                        | prop::num::$module::NORMAL | prop::num::$module::SUBNORMAL | prop::num::$module::ZERO
                }

                #[cfg(feature = "strict-test")]
                fn finite_above_min() -> impl Strategy<Value = $typ> {
                    finite().prop_filter("value must be above the type minimum", |value| *value > $typ::MIN)
                }

                #[cfg(feature = "strict-test")]
                fn bounds() -> impl Strategy<Value = [$typ; 2]> {
                    (finite(), finite()).prop_filter("Bounds can't be equal", |&(left, right)| !float_equal(left, right)).prop_map(sort)
                }

                #[test]
                fn range_test() -> Check<Samples> {
                    ensure_that(samples(FloatUniform::new($wrapper(NEG_ONE), $wrapper(TEN)), 100),
                        "every sample stays within the half-open range", |result| result.as_ref().is_ok_and(|observed| {
                            observed.1.iter().all(|value| observed.0.low <= *value && *value < observed.0.high)
                        })).map_err(Box::new).map(drop)
                }

                #[test]
                fn range_end_bound_test() -> Check<Samples> {
                    ensure_that(samples(FloatUniform::new($wrapper(ONE), $wrapper(ONE + $typ::EPSILON)), 100),
                        "a one-ulp half-open range only yields its base", |result| result.as_ref().is_ok_and(|observed| {
                            observed.1.iter().all(|value| float_bits_equal(*value, ONE))
                        })).map_err(Box::new).map(drop)
                }

                #[test]
                fn inclusive_range_test() -> Check<Samples> {
                    ensure_that(samples(FloatUniform::new_inclusive($wrapper(NEG_ONE), $wrapper(TEN)), 100),
                        "every sample stays within the inclusive range", |result| result.as_ref().is_ok_and(|observed| {
                            observed.1.iter().all(|value| observed.0.low <= *value && *value <= observed.0.high)
                        })).map_err(Box::new).map(drop)
                }

                #[test]
                fn inclusive_range_end_bound_test() -> Check<Samples> {
                    ensure_that(samples(FloatUniform::new_inclusive($wrapper(ONE), $wrapper(ONE + $typ::EPSILON)), 100),
                        "the inclusive end bound is sampled", |result| result.as_ref().is_ok_and(|observed| {
                            observed.1.iter().any(|value| float_bits_equal(*value, observed.0.high))
                        })).map_err(Box::new).map(drop)
                }

                #[test]
                fn inclusive_range_single_point() -> Check<[SampledRange; 3]> {
                    let negative_zero = core::ops::Neg::neg(ZERO);
                    let observed = [(ZERO, ZERO), (negative_zero, ZERO), (ZERO, negative_zero)]
                        .map(|bounds| (bounds, samples(FloatUniform::new_inclusive($wrapper(bounds.0), $wrapper(bounds.1)), 16)));
                    ensure_that(observed,
                        "a single-point range preserves the exact lower value, including signed zero", |results| {
                            results.iter().all(|&(ref bounds, ref result)| result.as_ref().is_ok_and(|samples| {
                                samples.1.iter().all(|value| float_bits_equal(*value, bounds.0))
                            }))
                        }).map_err(Box::new).map(drop)
                }

                #[test]
                fn inclusive_range_single_point_strategy()
                    -> Check<Result<crate::num::$module::BinarySearch, Reason>> {
                    let mut runner = test_runner_without_persistence();
                    ensure_that((ONE_POINT_FIVE..=ONE_POINT_FIVE).new_tree(&mut runner),
                        "the single-point strategy yields its point", |result| result.as_ref().is_ok_and(|tree| {
                            float_bits_equal(tree.current(), ONE_POINT_FIVE)
                        })).map_err(Box::new).map(drop)
                }

                #[test]
                fn all_floats_in_range_are_possible_1() -> Check<Samples> {
                    ensure_that(samples(FloatUniform::new_inclusive($wrapper(ONE - $typ::EPSILON), $wrapper(ONE + $typ::EPSILON)), 100),
                        "an interior float of the range is sampled", |result| result.as_ref().is_ok_and(|observed| {
                            observed.1.iter().any(|value| float_bits_equal(*value, ONE - $typ::EPSILON * HALF))
                        })).map_err(Box::new).map(drop)
                }

                #[test]
                fn all_floats_in_range_are_possible_2() -> Check<Samples> {
                    ensure_that(samples(FloatUniform::new_inclusive($wrapper(ZERO), $wrapper(MAX_PRECISE_INT.into_sampler_float())), 100),
                        "fractional values are sampled across the range", |result| result.as_ref().is_ok_and(|observed| {
                            observed.1.iter().any(|value| !float_is_zero(value.fract()))
                        })).map_err(Box::new).map(drop)
                }

                #[test]
                fn max_precise_int_plus_one_is_rounded_down() -> Result<(), ComparisonFailure<$int_typ, $int_typ>> {
                    ensure_eq(sampler_round_trip_integer::<$typ, $int_typ>(MAX_PRECISE_INT.saturating_add(1)), MAX_PRECISE_INT,
                        "the first imprecise integer rounds back down").map(drop)
                }

                #[cfg(feature = "strict-test")]
                #[test]
                fn next_down_less_than_float() -> Property<$typ, ($typ, $typ)> {
                    crate::strict::ensure_property(&finite_above_min(), "next_down is strictly below its input", |value| {
                        ensure_that((value, next_down(value)), "next_down yields a smaller float", |observed| observed.1 < observed.0).map_err(Box::new)
                    })
                }

                #[cfg(feature = "strict-test")]
                #[test]
                fn no_value_between_float_and_next_down() -> Property<$typ, ($typ, $typ, $typ)> {
                    crate::strict::ensure_property(&finite_above_min(), "next_down is the immediate predecessor", |value| {
                        let previous = next_down(value);
                        let average = previous * HALF + value * HALF;
                        ensure_that((value, previous, average), "no float lies between a value and its next_down", |observed| {
                            float_bits_equal(observed.2, observed.1) || float_bits_equal(observed.2, observed.0)
                        }).map_err(Box::new)
                    })
                }

                #[cfg(feature = "strict-test")]
                #[test]
                fn values_less_than_or_equal_to_max_precise_int_are_not_rounded()
                    -> PropertyResult<$int_typ, ($int_typ, $int_typ), ComparisonFailure<$int_typ, $int_typ>> {
                    crate::strict::ensure_property(&(0..=MAX_PRECISE_INT), "precise integers survive a float round trip", |value| {
                        ensure_eq(sampler_round_trip_integer::<$typ, $int_typ>(value), value, "the round-tripped integer is unchanged")
                    })
                }

                #[cfg(feature = "strict-test")]
                #[test]
                fn indivisible_intervals_are_split_to_self() -> Property<$typ, ([$typ; 2], IntervalCollection)> {
                    crate::strict::ensure_property(&finite_above_min(), "a one-ulp interval is indivisible", |value| {
                        let bounds = [next_down(value), value];
                        ensure_that((bounds, split_interval(bounds)), "the indivisible interval splits to itself", |observed| observed.1.count == 1).map_err(Box::new)
                    })
                }

                /// All sampled intervals retain their native index and endpoints.
                #[cfg(feature = "strict-test")]
                type IntervalSamples<T> = ([$typ; 2], [prop::sample::Index; 32], IntervalCollection, [Option<T>; 32]);
                /// Concrete input of interval-sampling properties.
                #[cfg(feature = "strict-test")]
                type IntervalInput = ([$typ; 2], [prop::sample::Index; 32]);

                /// Draw indices only from bounds with enough intervals for the observation.
                #[cfg(feature = "strict-test")]
                fn interval_inputs(minimum_count: $int_typ, context: &'static str) -> impl Strategy<Value = IntervalInput> {
                    (bounds(), any::<[prop::sample::Index; 32]>())
                        .prop_filter(context, move |&(bounds, _)| split_interval(bounds).count > minimum_count)
                }

                /// Retain the requested bounds and indices alongside each sampled interval.
                #[cfg(feature = "strict-test")]
                fn sample_intervals<T>(
                    (bounds, indices): IntervalInput,
                    reserved_tail: usize,
                    observe: impl Fn([$typ; 2], &IntervalCollection, $int_typ) -> T,
                ) -> IntervalSamples<T> {
                    let intervals = split_interval(bounds);
                    let size = sampler_count_to_usize::<$typ, $int_typ>(intervals.count.saturating_sub(1))
                        .saturating_sub(reserved_tail);
                    let sampled = indices.map(|index| index.index(size).map(|index| {
                        let sampler_index = sampler_index_from_usize::<$typ, $int_typ>(index);
                        observe(intervals.get(sampler_index), &intervals, sampler_index)
                    }));
                    (bounds, indices, intervals, sampled)
                }

                #[cfg(feature = "strict-test")]
                #[test]
                fn split_intervals_are_the_same_size() -> Property<IntervalInput, IntervalSamples<[$typ; 2]>> {
                    let inputs = interval_inputs(1, "the bounds must split into at least two intervals");
                    crate::strict::ensure_property(&inputs, "split intervals share one width", |input| {
                        ensure_that(sample_intervals(input, 0, |interval, _, _| interval), "every sampled interval has the same width", |observed| {
                            observed.3.first().copied().flatten().is_some_and(|[low, high]| observed.3.iter().all(|sample| {
                                sample.is_some_and(|[other_low, other_high]| float_bits_equal(high - low, other_high - other_low))
                            }))
                        }).map_err(Box::new)
                    })
                }

                #[cfg(feature = "strict-test")]
                #[test]
                fn split_intervals_are_consecutive() -> Property<IntervalInput, IntervalSamples<[[$typ; 2]; 2]>> {
                    let inputs = interval_inputs(2, "the bounds must split into at least three intervals");
                    crate::strict::ensure_property(&inputs, "split intervals are consecutive", |input| {
                        let observed = sample_intervals(input, 1, |interval, intervals, index| {
                            [interval, intervals.get(index.saturating_add(1))]
                        });
                        ensure_that(observed, "adjacent intervals share a bound in one direction", |observed| {
                            observed.3.iter().all(|sample| sample.is_some_and(|[[_, high], [low, _]]| float_bits_equal(high, low)))
                                || observed.3.iter().all(|sample| sample.is_some_and(|[[low, _], [_, high]]| float_bits_equal(low, high)))
                        }).map_err(Box::new)
                    })
                }

                /// Requested interval, its subdivision, and both extreme subintervals.
                #[cfg(feature = "strict-test")]
                type Split = ([$typ; 2], IntervalCollection, [$typ; 2], [$typ; 2]);

                #[cfg(feature = "strict-test")]
                #[test]
                fn first_split_might_slightly_overshoot_one_bound() -> Property<[$typ; 2], Split> {
                    crate::strict::ensure_property(&bounds(), "the first split covers the bounds with at most one overshoot", |bounds| {
                        let intervals = split_interval(bounds);
                        let start = intervals.get(0);
                        let end = intervals.get(intervals.count.saturating_sub(1));
                        let (low_interval, high_interval) = if start[0] < end[0] { (start, end) } else { (end, start) };
                        ensure_that((bounds, intervals, low_interval, high_interval), "exactly one bound may overshoot",
                            |observed| {
                                let [low, high] = observed.0;
                                let [low_start, low_end] = observed.2;
                                let [high_start, high_end] = observed.3;
                                (float_bits_equal(low, low_start) && high_start < high && high <= high_end)
                                    || (low_start <= low && low < low_end && float_bits_equal(high, high_end))
                            }).map_err(Box::new)
                    })
                }

                /// A recursive split retains both the parent and its sampled child.
                #[cfg(feature = "strict-test")]
                type RecursiveSplit = ([$typ; 2], prop::sample::Index, IntervalCollection, Option<Split>);

                #[cfg(feature = "strict-test")]
                #[test]
                fn subsequent_splits_always_match_bounds() -> Property<([$typ; 2], prop::sample::Index), RecursiveSplit> {
                    crate::strict::ensure_property(&(bounds(), any::<prop::sample::Index>()), "recursive splits stay within their interval", |(bounds, index)| {
                        let intervals = split_interval(bounds);
                        let size = sampler_count_to_usize::<$typ, $int_typ>(intervals.count.saturating_sub(1));
                        let sampled = index.index(size).map(|index| {
                            let interval = intervals.get(sampler_index_from_usize::<$typ, $int_typ>(index));
                            let small_intervals = split_interval(interval);
                            let start = small_intervals.get(0);
                            let end = small_intervals.get(small_intervals.count.saturating_sub(1));
                            let (low_interval, high_interval) = if start[0] < end[0] { (start, end) } else { (end, start) };
                            (interval, small_intervals, low_interval, high_interval)
                        });
                        ensure_that((bounds, index, intervals, sampled), "the sub-split spans exactly its parent interval", |observed| {
                            observed.3.as_ref().is_some_and(|reached| {
                                float_bits_equal(reached.0[0], reached.2[0]) && float_bits_equal(reached.0[1], reached.3[1])
                            })
                        }).map_err(Box::new)
                    })
                }
            }
        }
    };
}

#[cfg(all(feature = "f16", not(feature = "alt-stable")))]
float_sampler!(
    module = f16,
    type = f16,
    int = u16,
    wrapper = F16U,
    neg_one = f16::from_bits(0xBC00),
    zero = 0.0,
    one = 1.0,
    two = 2.0,
    ten = 10.0,
    one_point_five = 1.5,
    half = 0.5
);
#[cfg(feature = "alt-stable")]
float_sampler!(
    module = half_f16,
    type = HalfF16,
    type_path = half::f16,
    int = u16,
    wrapper = HalfF16U,
    neg_one = HalfF16::NEG_ONE,
    zero = HalfF16::ZERO,
    one = HalfF16::ONE,
    two = HalfF16::from_f32_const(2.0),
    ten = HalfF16::from_f32_const(10.0),
    one_point_five = HalfF16::from_f32_const(1.5),
    half = HalfF16::from_f32_const(0.5),
    always_trait = num_traits::float::Float
);
float_sampler!(
    module = f32,
    type = f32,
    int = u32,
    wrapper = F32U,
    neg_one = f32::from_bits(0xBF80_0000),
    zero = 0.0,
    one = 1.0,
    two = 2.0,
    ten = 10.0,
    one_point_five = 1.5,
    half = 0.5
);
float_sampler!(
    module = f64,
    type = f64,
    int = u64,
    wrapper = F64U,
    neg_one = f64::from_bits(0xBFF0_0000_0000_0000),
    zero = 0.0,
    one = 1.0,
    two = 2.0,
    ten = 10.0,
    one_point_five = 1.5,
    half = 0.5
);
