//! Procedural macros for the `proptest` crate.
//!
//! The crate currently provides one macro: [`macro@property_test`], an
//! attribute that rewrites an annotated test function into a strict property
//! test — the generated `#[test]` wrapper returns
//! `proptest::strict::TestResult` and drives the body through
//! `proptest::strict::ensure_property`.

use proc_macro::TokenStream;

/// Token streams for one `#[property_test]` expansion.
struct PropertyTestInput {
    /// The attribute body supplied to `#[property_test(...)]`.
    attr: proc_macro2::TokenStream,
    /// The function annotated with `#[property_test]`.
    annotated_fn: proc_macro2::TokenStream,
}

/// Expands a parsed `#[property_test]` invocation.
trait ExpandPropertyTest {
    /// Rewrite the annotated function into the generated strict property test.
    fn expand(self) -> proc_macro2::TokenStream;
}

/// The parse / validate / options / codegen pipeline that rewrites an
/// annotated function into the generated strict property test.
mod property_test;

/// The `property_test` procedural macro simplifies the creation of
/// property-based tests using the `proptest` crate.
///
/// This macro provides a more concise syntax for writing tests that
/// automatically generate test cases based on properties.
///
/// The annotated function must return `proptest::strict::TestResult`
/// (`Result<(), TestFailure>`); a unit (`()`) body is rejected at compile
/// time. The macro rewrites the function into a `#[test]` wrapper returning
/// `proptest::strict::TestResult` that runs the body through
/// `proptest::strict::ensure_property`, so a falsified property surfaces as
/// a returned `TestFailure` carrying the shrunk minimal failing input,
/// rather than as a panic.
///
/// # Example
///
/// Using the `property_test` macro:
///
/// ```
/// # use proptest_macro::property_test;
/// #[property_test]
/// fn foo(x: i32) -> proptest::strict::TestResult {
///     // Real bodies check invariants with the `ensure*` helpers from
///     // `strict-test-support` and propagate failures with `?`; a passing
///     // property returns `Ok(())`.
///     let _ = x;
///     Ok(())
/// }
/// ```
///
/// is roughly equivalent to:
///
/// ```ignore
/// #[test]
/// fn foo() -> proptest::strict::TestResult {
///     proptest::strict::ensure_property(
///         &any::<i32>(),
///         concat!(module_path!(), "::foo"),
///         |x| {
///             let _ = x;
///             Ok(())
///         },
///     )
/// }
/// ```
///
/// # Details
///
/// The `property_test` macro is used to define property-based tests, where the parameters
/// of the test function are automatically generated by `proptest`. The macro takes care
/// of setting up the strict runner and generating input values, allowing the user to focus
/// on writing the test logic.
///
/// ## Attributes
///
/// All attributes mentioned here are optional.
///
/// The `property_test` macro can take a `config` attribute, which allows you to customize the
/// configuration of the `proptest` runner; the property then runs through
/// `proptest::strict::ensure_property_with_config`, which uses the given
/// config verbatim apart from `test_name`/`source_file`, which the macro
/// forces so failure reports name the annotated test. If `config` is not
/// provided, the strict defaults apply: deterministic seeding selected by the
/// `STRICT_TEST_SEED` environment variable, failure persistence disabled (no
/// `proptest-regressions/` files), and the ordinary `PROPTEST_*` environment
/// variables honored through `Config::default()`.
///
/// E.g. running 100 cases:
///
/// ```rust,ignore
/// #[property_test(config = ProptestConfig { cases: 100, .. ProptestConfig::default() })]
/// fn foo(x: i32) -> proptest::strict::TestResult {
///     ensure_eq(&x, &x, "x equals itself")
/// }
/// ```
///
/// You can also provide `proptest_path = ::path::to::proptest`, which tells the macro not to
/// assume that the `proptest` crate is available. This is useful if, for example, you are using a
/// re-exported version of proptest, such as `my_library::proptest`. The strict runner is reached
/// through that same path (`::path::to::proptest::strict::...`).
///
/// ## Custom strategies
///
/// By default, [`property_test`] will use the `Arbitrary` impl for parameters. However, you can
/// provide a custom `Strategy` with `#[strategy = <expr>]` on an argument:
///
/// ```
/// # use proptest_macro::property_test;
/// #[property_test]
/// fn foo(#[strategy = "[0-9]*"] s: String) -> proptest::strict::TestResult {
///     // Real bodies verify with the `ensure*` helpers from
///     // `strict-test-support`; a passing property returns `Ok(())`.
///     let _all_numeric = s.chars().all(|c| c.is_numeric());
///     Ok(())
/// }
/// ```
/// Multiple `#[strategy = <expr>]` attributes on an argument are not allowed.
///
/// ## Semver guarantees of generated code
///
/// This macro generates a struct with a name derived from the name of the test function. Details
/// of this struct, such as its name, field names, or even whether it exists are considered
/// implementation details, and may change without a major version bump. The generated wrapper
/// function returning `proptest::strict::TestResult` and running through
/// `proptest::strict::ensure_property` is, however, part of the documented contract.
#[proc_macro_attribute]
#[allow(
    clippy::single_call_fn,
    reason = "proc_macro_attribute entry point that bridges proc_macro tokens into the internal pipeline"
)]
pub fn property_test(
    attr: TokenStream,
    annotated_fn: TokenStream,
) -> TokenStream {
    PropertyTestInput {
        attr: attr.into(),
        annotated_fn: annotated_fn.into(),
    }
    .expand()
    .into()
}
