//-
// Copyright 2017, 2018 The proptest developers
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

use crate::std_facade::Arc;
use crate::std_facade::Box;
use crate::std_facade::Rc;
use crate::std_facade::fmt;
use crate::std_facade::format;
use crate::std_facade::vec;
use crate::strategy::Filter;
use crate::strategy::FilterMap;
use crate::strategy::Flatten;
use crate::strategy::IndFlatten;
use crate::strategy::IndFlattenMap;
use crate::strategy::Map;
use crate::strategy::MapInto;
use crate::strategy::Perturb;
use crate::strategy::Recursive;
use crate::strategy::Shuffle;
use crate::strategy::Shuffleable;
use crate::strategy::Union;
use crate::test_runner::Config;
use crate::test_runner::Reason;
use crate::test_runner::TestRng;
use crate::test_runner::TestRunner;

//==============================================================================
// Traits
//==============================================================================

/// The result of building a [`ValueTree`] from a [`Strategy`].
///
/// This is [`Ok`] carrying the new value tree, or [`Err`] when one cannot be
/// produced for some reason, such as filtering with a predicate which always
/// returns false. You should pass in your strategy as the type parameter.
///
/// [`Strategy`]: trait.Strategy.html
/// [`ValueTree`]: trait.ValueTree.html
/// [`Ok`]: https://doc.rust-lang.org/nightly/std/result/enum.Result.html#variant.Ok
/// [`Err`]: https://doc.rust-lang.org/nightly/std/result/enum.Result.html#variant.Err
pub type NewTree<S> = Result<<S as Strategy>::Tree, Reason>;

/// A strategy for producing arbitrary values of a given type.
///
/// `fmt::Debug` is a hard requirement for all strategies currently due to
/// `prop_flat_map()`. This constraint will be removed when specialisation
/// becomes stable.
#[must_use = "strategies do nothing unless used"]
pub trait Strategy: fmt::Debug {
  /// The value tree generated by this `Strategy`.
  type Tree: ValueTree<Value = Self::Value>;

  /// The type of value used by functions under test generated by this Strategy.
  ///
  /// This corresponds to the same type as the associated type `Value`
  /// in `Self::Tree`. It is provided here to simplify usage particularly
  /// in conjunction with `-> impl Strategy<Value = MyType>`.
  type Value: fmt::Debug;

  /// Generate a new value tree from the given runner.
  ///
  /// This method is generally expected to be deterministic. That is, given a
  /// `TestRunner` with its RNG in a particular state, this should produce an
  /// identical `ValueTree` every time. Non-deterministic strategies do not
  /// cause problems during normal operation, but they do break failure
  /// persistence since it is implemented by simply saving the seed used to
  /// generate the test case.
  ///
  /// ## Errors
  ///
  /// Returns `Err` if there are constraints on the generated value that the
  /// generator cannot satisfy, for instance a `prop_filter` predicate that
  /// rejects every candidate. Any such failure is wrapped in
  /// `TestError::Abort`.
  fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self>;

  /// Returns a strategy which produces values transformed by the function
  /// `fun`.
  ///
  /// There is no need (or possibility, for that matter) to define how the
  /// output is to be shrunken. Shrinking continues to take place in terms of
  /// the source value.
  ///
  /// `fun` should be a deterministic function. That is, for a given input
  /// value, it should produce an equivalent output value on every call.
  /// Proptest assumes that it can call the function as many times as needed
  /// to generate as many identical values as needed. For this reason, `F` is
  /// `Fn` rather than `FnMut`.
  fn prop_map<O: fmt::Debug, F: Fn(Self::Value) -> O>(self, fun: F) -> Map<Self, F>
  where
    Self: Sized,
  {
    Map {
      source: self,
      fun:    Arc::new(fun),
    }
  }

  /// Returns a strategy which produces values of type `O` by transforming
  /// `Self` with `Into<O>`.
  ///
  /// You should always prefer this operation instead of `prop_map` when
  /// you can as it is both clearer and also currently more efficient.
  ///
  /// There is no need (or possibility, for that matter) to define how the
  /// output is to be shrunken. Shrinking continues to take place in terms of
  /// the source value.
  fn prop_map_into<O: fmt::Debug>(self) -> MapInto<Self, O>
  where
    Self: Sized,
    Self::Value: Into<O>,
  {
    MapInto::new(self)
  }

  /// Returns a strategy which produces values transformed by the function
  /// `fun`, which is additionally given a random number generator.
  ///
  /// This is exactly like `prop_map()` except for the addition of the second
  /// argument to the function. This allows introducing chaotic variations to
  /// generated values that are not easily expressed otherwise while allowing
  /// shrinking to proceed reasonably.
  ///
  /// During shrinking, `fun` is always called with an identical random
  /// number generator, so if it is a pure function it will always perform
  /// the same perturbation.
  ///
  /// ## Example
  ///
  /// ```
  /// // The prelude also gets us the `Rng` trait.
  /// use proptest::prelude::*;
  ///
  /// proptest! {
  ///   # /*
  ///   #[test]
  ///   # */
  ///   fn test_something(a in (0_i32..10).prop_perturb(
  ///       // Perturb the integer `a` (range 0..10) to a pair of that
  ///       // integer and another that's ± 10 of it.
  ///       // Note that this particular case would be better implemented as
  ///       // `(0_i32..10, -10_i32..10).prop_map(|(a, b)| (a, a + b))`
  ///       // but is shown here for simplicity.
  ///       |centre, mut rng| (centre, centre + rng.random_range(-10..10))))
  ///   {
  ///       // Test stuff
  ///   }
  /// }
  /// # fn main() { }
  /// ```
  fn prop_perturb<O: fmt::Debug, F: Fn(Self::Value, TestRng) -> O>(self, fun: F) -> Perturb<Self, F>
  where
    Self: Sized,
  {
    Perturb {
      source: self,
      fun:    Arc::new(fun),
    }
  }

  /// Maps values produced by this strategy into new strategies and picks
  /// values from those strategies.
  ///
  /// `fun` is used to transform the values produced by this strategy into
  /// other strategies. Values are then chosen from the derived strategies.
  /// Shrinking proceeds by shrinking individual values as well as shrinking
  /// the input used to generate the internal strategies.
  ///
  /// ## Shrinking
  ///
  /// In the case of test failure, shrinking will not only shrink the output
  /// from the combinator itself, but also the input, i.e., the strategy used
  /// to generate the output itself. Doing this requires searching the new
  /// derived strategy for a new failing input. The combinator will generate
  /// up to `Config::cases` values for this search.
  ///
  /// As a result, nested `prop_flat_map`/`Flatten` combinators risk
  /// exponential run time on this search for new failing values. To ensure
  /// that test failures occur within a reasonable amount of time, all of
  /// these combinators share a single "flat map regen" counter, and will
  /// stop generating new values if it exceeds `Config::max_flat_map_regens`.
  ///
  /// ## Example
  ///
  /// Generate two integers, where the second is always less than the first,
  /// without using filtering:
  ///
  /// ```
  /// use proptest::prelude::*;
  ///
  /// proptest! {
  ///   # /*
  ///   #[test]
  ///   # */
  ///   fn test_two(
  ///     // Pick integers in the 1..65536 range, and derive a strategy
  ///     // which emits a tuple of that integer and another one which is
  ///     // some value less than it.
  ///     (a, b) in (1..65536).prop_flat_map(|a| (Just(a), 0..a))
  ///   ) {
  ///     prop_assert!(b < a);
  ///   }
  /// }
  /// #
  /// # fn main() { test_two(); }
  /// ```
  ///
  /// ## Choosing the right flat-map
  ///
  /// `Strategy` has three "flat-map" combinators. They look very similar at
  /// first, and can be used to produce superficially identical test results.
  /// For example, the following three expressions all produce inputs which
  /// are 2-tuples `(a,b)` where the `b` component is less than `a`.
  ///
  /// ```no_run
  /// # #![allow(unused_variables)]
  /// use proptest::prelude::*;
  ///
  /// let flat_map = (1..10).prop_flat_map(|a| (Just(a), 0..a));
  /// let ind_flat_map = (1..10).prop_ind_flat_map(|a| (Just(a), 0..a));
  /// let ind_flat_map2 = (1..10).prop_ind_flat_map2(|a| 0..a);
  /// ```
  ///
  /// The three do differ however in terms of how they shrink.
  ///
  /// For `flat_map`, both `a` and `b` will shrink, and the invariant that
  /// `b < a` is maintained. This is a "dependent" or "higher-order" strategy
  /// in that it remembers that the strategy for choosing `b` is dependent on
  /// the value chosen for `a`.
  ///
  /// For `ind_flat_map`, the invariant `b < a` is maintained, but only
  /// because `a` does not shrink. This is due to the fact that the
  /// dependency between the strategies is not tracked; `a` is simply seen as
  /// a constant.
  ///
  /// Finally, for `ind_flat_map2`, the invariant `b < a` is _not_
  /// maintained, because `a` can shrink independently of `b`, again because
  /// the dependency between the two variables is not tracked, but in this
  /// case the derivation of `a` is still exposed to the shrinking system.
  ///
  /// The use-cases for the independent flat-map variants is pretty narrow.
  /// For the majority of cases where invariants need to be maintained and
  /// you want all components to shrink, `prop_flat_map` is the way to go.
  /// `prop_ind_flat_map` makes the most sense when the input to the map
  /// function is not exposed in the output and shrinking across strategies
  /// is not expected to be useful. `prop_ind_flat_map2` is useful for using
  /// related values as starting points while not constraining them to that
  /// relation.
  fn prop_flat_map<S: Strategy, F: Fn(Self::Value) -> S>(self, fun: F) -> Flatten<Map<Self, F>>
  where
    Self: Sized,
  {
    Flatten::new(Map {
      source: self,
      fun:    Arc::new(fun),
    })
  }

  /// Maps values produced by this strategy into new strategies and picks
  /// values from those strategies while considering the new strategies to be
  /// independent.
  ///
  /// This is very similar to `prop_flat_map()`, but shrinking will *not*
  /// attempt to shrink the input that produces the derived strategies. This
  /// is appropriate for when the derived strategies already fully shrink in
  /// the desired way.
  ///
  /// In most cases, you want `prop_flat_map()`.
  ///
  /// See `prop_flat_map()` for a more detailed explanation on how the
  /// three flat-map combinators differ.
  fn prop_ind_flat_map<S: Strategy, F: Fn(Self::Value) -> S>(self, fun: F) -> IndFlatten<Map<Self, F>>
  where
    Self: Sized,
  {
    IndFlatten(Map {
      source: self,
      fun:    Arc::new(fun),
    })
  }

  /// Similar to `prop_ind_flat_map()`, but produces 2-tuples with the input
  /// generated from `self` in slot 0 and the derived strategy in slot 1.
  ///
  /// See `prop_flat_map()` for a more detailed explanation on how the
  /// three flat-map combinators differ.
  fn prop_ind_flat_map2<S: Strategy, F: Fn(Self::Value) -> S>(self, fun: F) -> IndFlattenMap<Self, F>
  where
    Self: Sized,
  {
    IndFlattenMap {
      source: self,
      fun:    Arc::new(fun),
    }
  }

  /// Returns a strategy which only produces values accepted by `fun`.
  ///
  /// This results in a very naïve form of rejection sampling and should only
  /// be used if (a) relatively few values will actually be rejected; (b) it
  /// isn't easy to express what you want by using another strategy and/or
  /// `map()`.
  ///
  /// There are a lot of downsides to this form of filtering. It slows
  /// testing down, since values must be generated but then discarded.
  /// Proptest only allows a limited number of rejects this way (across the
  /// entire `TestRunner`). Rejection can interfere with shrinking;
  /// particularly, complex filters may largely or entirely prevent shrinking
  /// from substantially altering the original value.
  ///
  /// Local rejection sampling is still preferable to rejecting the entire
  /// input to a test (via `TestCaseError::Reject`), however, and the default
  /// number of local rejections allowed is much higher than the number of
  /// whole-input rejections.
  ///
  /// `whence` is used to record where and why the rejection occurred.
  #[allow(
    clippy::single_call_fn,
    reason = "forward the Strategy::prop_filter trait method to the Filter combinator constructor"
  )]
  fn prop_filter<R: Into<Reason>, F: Fn(&Self::Value) -> bool>(self, whence: R, fun: F) -> Filter<Self, F>
  where
    Self: Sized,
  {
    Filter::new(self, whence.into(), fun)
  }

  /// Returns a strategy which only produces transformed values where `fun`
  /// returns `Some(value)` and rejects those where `fun` returns `None`.
  ///
  /// Using this method is preferable to using `.prop_map(..).prop_filter(..)`.
  ///
  /// This results in a very naïve form of rejection sampling and should only
  /// be used if (a) relatively few values will actually be rejected; (b) it
  /// isn't easy to express what you want by using another strategy and/or
  /// `map()`.
  ///
  /// There are a lot of downsides to this form of filtering. It slows
  /// testing down, since values must be generated but then discarded.
  /// Proptest only allows a limited number of rejects this way (across the
  /// entire `TestRunner`). Rejection can interfere with shrinking;
  /// particularly, complex filters may largely or entirely prevent shrinking
  /// from substantially altering the original value.
  ///
  /// Local rejection sampling is still preferable to rejecting the entire
  /// input to a test (via `TestCaseError::Reject`), however, and the default
  /// number of local rejections allowed is much higher than the number of
  /// whole-input rejections.
  ///
  /// The mapped output must be cloneable so rejected shrink attempts can keep
  /// reporting the most recent accepted output and keep
  /// `ValueTree::current()` infallible.
  ///
  /// `whence` is used to record where and why the rejection occurred.
  #[allow(
    clippy::single_call_fn,
    reason = "forward the Strategy::prop_filter_map trait method to the FilterMap combinator constructor"
  )]
  fn prop_filter_map<F: Fn(Self::Value) -> Option<O>, O: Clone + fmt::Debug>(self, whence: impl Into<Reason>, fun: F) -> FilterMap<Self, F>
  where
    Self: Sized,
  {
    FilterMap::new(self, whence.into(), fun)
  }

  /// Returns a strategy which picks uniformly from `self` and `other`.
  ///
  /// When shrinking, if a value from `other` was originally chosen but that
  /// value can be shrunken no further, it switches to a value from `self`
  /// and starts shrinking that.
  ///
  /// Be aware that chaining `prop_union` calls will result in a very
  /// right-skewed distribution. If this is not what you want, you can call
  /// the `.or()` method on the `Union` to add more values to the same union,
  /// or directly call `Union::new()`.
  ///
  /// Both `self` and `other` must be of the same type. To combine
  /// heterogeneous strategies, call the `boxed()` method on both `self` and
  /// `other` to erase the type differences before calling `prop_union()`.
  fn prop_union(self, other: Self) -> Union<Self>
  where
    Self: Sized,
  {
    Union::new(vec![self, other])
  }

  /// Generate a recursive structure with `self` items as leaves.
  ///
  /// `recurse` is applied to various strategies that produce the same type
  /// as `self` with nesting depth _n_ to create a strategy that produces the
  /// same type with nesting depth _n+1_. Generated structures will have a
  /// depth between 0 and `depth` and will usually have up to `desired_size`
  /// total elements, though they may have more. `expected_branch_size` gives
  /// the expected maximum size for any collection which may contain
  /// recursive elements and is used to control branch probability to achieve
  /// the desired size. Passing a too small value can result in trees vastly
  /// larger than desired.
  ///
  /// Note that `depth` only counts branches; i.e., `depth = 0` is a single
  /// leaf, and `depth = 1` is a leaf or a branch containing only leaves.
  ///
  /// In practise, generated values usually have a lower depth than `depth`
  /// (but `depth` is a hard limit) and almost always under
  /// `expected_branch_size` (though it is not a hard limit) since the
  /// underlying code underestimates probabilities.
  ///
  /// Shrinking shrinks both the inner values and attempts switching from
  /// recursive to non-recursive cases.
  ///
  /// ## Example
  ///
  /// ```rust,no_run
  /// # #![allow(unused_variables)]
  /// use std::collections::HashMap;
  ///
  /// use proptest::prelude::*;
  ///
  /// /// Define our own JSON AST type
  /// #[derive(Debug, Clone)]
  /// enum JsonNode {
  ///   Null,
  ///   Bool(bool),
  ///   Number(f64),
  ///   String(String),
  ///   Array(Vec<JsonNode>),
  ///   Map(HashMap<String, JsonNode>),
  /// }
  ///
  /// # fn main() {
  /// #
  /// // Define a strategy for generating leaf nodes of the AST
  /// let json_leaf = prop_oneof![
  ///   Just(JsonNode::Null),
  ///   prop::bool::ANY.prop_map(JsonNode::Bool),
  ///   prop::num::f64::ANY.prop_map(JsonNode::Number),
  ///   ".*".prop_map(JsonNode::String),
  /// ];
  ///
  /// // Now define a strategy for a whole tree
  /// let json_tree = json_leaf.prop_recursive(
  ///   4,  // No more than 4 branch levels deep
  ///   64, // Target around 64 total elements
  ///   16, // Each collection is up to 16 elements long
  ///   |element| {
  ///     prop_oneof![
  ///       // NB `element` is an `Arc` and we'll need to reference it twice,
  ///       // so we clone it the first time.
  ///       prop::collection::vec(element.clone(), 0..16).prop_map(JsonNode::Array),
  ///       prop::collection::hash_map(".*", element, 0..16).prop_map(JsonNode::Map)
  ///     ]
  ///   },
  /// );
  /// # }
  /// ```
  fn prop_recursive<R: Strategy<Value = Self::Value> + 'static, F: Fn(BoxedStrategy<Self::Value>) -> R>(
    self,
    depth: u32,
    desired_size: u32,
    expected_branch_size: u32,
    recurse: F,
  ) -> Recursive<Self::Value, F>
  where
    Self: Sized + 'static,
  {
    Recursive::new(self, depth, desired_size, expected_branch_size, recurse)
  }

  /// Shuffle the contents of the values produced by this strategy.
  ///
  /// That is, this modifies a strategy producing a `Vec`, slice, etc, to
  /// shuffle the contents of that `Vec`/slice/etc.
  ///
  /// Initially, the value is fully shuffled. During shrinking, the input
  /// value will initially be unchanged while the result will gradually be
  /// restored to its original order. Once de-shuffling either completes or
  /// is cancelled by calls to `complicate()` pinning it to a particular
  /// permutation, the inner value will be simplified.
  ///
  /// ## Example
  ///
  /// ```
  /// use proptest::prelude::*;
  ///
  /// static VALUES: &'static [u32] = &[0, 1, 2, 3, 4];
  ///
  /// fn is_permutation(orig: &[u32], mut actual: Vec<u32>) -> bool {
  ///   actual.sort();
  ///   orig == &actual[..]
  /// }
  ///
  /// proptest! {
  ///   # /*
  ///   #[test]
  ///   # */
  ///   fn test_is_permutation(
  ///       ref perm in Just(VALUES.to_owned()).prop_shuffle()
  ///   ) {
  ///       assert!(is_permutation(VALUES, perm.clone()));
  ///   }
  /// }
  /// #
  /// # fn main() { test_is_permutation(); }
  /// ```
  fn prop_shuffle(self) -> Shuffle<Self>
  where
    Self: Sized,
    Self::Value: Shuffleable,
  {
    Shuffle(self)
  }

  /// Erases the type of this `Strategy` so it can be passed around as a
  /// simple trait object.
  ///
  /// See also `sboxed()` if this `Strategy` is `Send` and `Sync` and you
  /// want to preserve that information.
  ///
  /// Strategies of this type afford cheap shallow cloning via reference
  /// counting by using an `Arc` internally.
  fn boxed(self) -> BoxedStrategy<Self::Value>
  where
    Self: Sized + 'static,
  {
    BoxedStrategy(Arc::new(BoxedStrategyWrapper(self)))
  }

  /// Erases the type of this `Strategy` so it can be passed around as a
  /// simple trait object.
  ///
  /// Unlike `boxed()`, this conversion retains the `Send` and `Sync` traits
  /// on the output.
  ///
  /// Strategies of this type afford cheap shallow cloning via reference
  /// counting by using an `Arc` internally.
  #[allow(
    clippy::single_call_fn,
    reason = "public Send + Sync type-erasure strategy combinator retained for the Strategy API"
  )]
  fn sboxed(self) -> SBoxedStrategy<Self::Value>
  where
    Self: Sized + Send + Sync + 'static,
  {
    SBoxedStrategy(Arc::new(BoxedStrategyWrapper(self)))
  }

  /// Wraps this strategy to prevent values from being subject to shrinking.
  ///
  /// Suppressing shrinking is useful when testing things like linear
  /// approximation functions. Ordinarily, proptest will tend to shrink the
  /// input to the function until the result is just barely outside the
  /// acceptable range whereas the original input may have produced a result
  /// far outside of it. Since this makes it harder to see what the actual
  /// problem is, making the input `NoShrink` allows learning about inputs
  /// that produce more incorrect results.
  fn no_shrink(self) -> NoShrink<Self>
  where
    Self: Sized,
  {
    NoShrink(self)
  }
}

/// A generated value and its associated shrinker.
///
/// Conceptually, a `ValueTree` represents a spectrum between a "minimally
/// complex" value and a starting, randomly-chosen value. For values such as
/// numbers, this can be thought of as a simple binary search, and this is how
/// the `ValueTree` state machine is defined.
///
/// The `ValueTree` state machine notionally has three fields: low, current,
/// and high. Initially, low is the "minimally complex" value for the type, and
/// high and current are both the initially chosen value. It can be queried for
/// its current state. When shrinking, the controlling code tries simplifying
/// the value one step. If the test failure still happens with the simplified
/// value, further simplification occurs. Otherwise, the code steps back up
/// towards the prior complexity.
///
/// The main invariants here are that the "high" value always corresponds to a
/// failing test case, and that repeated calls to `complicate()` will return
/// `false` only once the "current" value has returned to what it was before
/// the last call to `simplify()`.
///
/// While it would be possible for default do-nothing implementations of
/// `simplify()` and `complicate()` to be provided, this was not done
/// deliberately since the majority of strategies will want to define their own
/// shrinking anyway, and the minority that do not must call it out explicitly
/// by their own implementation.
pub trait ValueTree {
  /// The type of the value produced by this `ValueTree`.
  type Value: fmt::Debug;

  /// Returns the current value.
  fn current(&self) -> Self::Value;
  /// Attempts to simplify the current value. Notionally, this sets the
  /// "high" value to the current value, and the current value to a "halfway
  /// point" between high and low, rounding towards low.
  ///
  /// Returns whether any state changed as a result of this call. This does
  /// not necessarily imply that the value of `current()` has changed, since
  /// in the most general case, it is not possible for an implementation to
  /// determine this.
  ///
  /// This call needs to correctly handle being called even immediately after
  /// it had been called previously and returned `false`.
  fn simplify(&mut self) -> bool;
  /// Attempts to partially undo the last simplification. Notionally, this
  /// sets the "low" value to one plus the current value, and the current
  /// value to a "halfway point" between high and the new low, rounding
  /// towards low.
  ///
  /// Returns whether any state changed as a result of this call. This does
  /// not necessarily imply that the value of `current()` has changed, since
  /// in the most general case, it is not possible for an implementation to
  /// determine this.
  ///
  /// It is usually expected that, immediately after a call to `simplify()`
  /// which returns true, this call will itself return true. However, this is
  /// not always the case; in some strategies, particularly those that use
  /// some form of rejection sampling, the act of trying to simplify may
  /// change the state such that `simplify()` returns true, yet ultimately
  /// left the resulting value unchanged, in which case there is nothing left
  /// to complicate.
  ///
  /// This call does not need to gracefully handle being called before
  /// `simplify()` was ever called, but does need to correctly handle being
  /// called even immediately after it had been called previously and
  /// returned `false`.
  fn complicate(&mut self) -> bool;
}

//==============================================================================
// NoShrink
//==============================================================================

/// Wraps a `Strategy` or `ValueTree` to suppress shrinking of generated
/// values.
///
/// See `Strategy::no_shrink()` for more details.
#[derive(Clone, Copy, Debug)]
#[must_use = "strategies do nothing unless used"]
pub struct NoShrink<T>(T);

impl<T: Strategy> Strategy for NoShrink<T> {
  type Tree = NoShrink<T::Tree>;
  type Value = T::Value;

  fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
    self.0.new_tree(runner).map(NoShrink)
  }
}

impl<T: ValueTree> ValueTree for NoShrink<T> {
  type Value = T::Value;

  fn current(&self) -> T::Value {
    self.0.current()
  }

  fn simplify(&mut self) -> bool {
    false
  }
  fn complicate(&mut self) -> bool {
    false
  }
}

//==============================================================================
// Trait objects
//==============================================================================

/// Blanket-implement `Strategy` for a pointer-like wrapper (`Box`, `Rc`,
/// `Arc`, `&`, `&mut`) around a strategy by delegating `new_tree` to the
/// pointee.
macro_rules! proxy_strategy {
  ($typ:ty) => {
    impl<S: Strategy + ?Sized> Strategy for $typ {
      type Tree = S::Tree;
      type Value = S::Value;

      fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
        (**self).new_tree(runner)
      }
    }
  };
}
proxy_strategy!(Box<S>);
proxy_strategy!(&S);
proxy_strategy!(&mut S);
proxy_strategy!(Rc<S>);
proxy_strategy!(Arc<S>);

impl<T: ValueTree + ?Sized> ValueTree for Box<T> {
  type Value = T::Value;
  fn current(&self) -> Self::Value {
    (**self).current()
  }
  fn simplify(&mut self) -> bool {
    (**self).simplify()
  }
  fn complicate(&mut self) -> bool {
    (**self).complicate()
  }
}

/// A boxed `ValueTree`.
type BoxedVT<T> = Box<dyn ValueTree<Value = T>>;

/// A boxed `Strategy` trait object as produced by `Strategy::boxed()`.
///
/// Strategies of this type afford cheap shallow cloning via reference
/// counting by using an `Arc` internally.
#[derive(Debug)]
#[must_use = "strategies do nothing unless used"]
pub struct BoxedStrategy<T>(Arc<dyn Strategy<Value = T, Tree = BoxedVT<T>>>);

/// A boxed `Strategy` trait object which is also `Sync` and
/// `Send`, as produced by `Strategy::sboxed()`.
///
/// Strategies of this type afford cheap shallow cloning via reference
/// counting by using an `Arc` internally.
#[derive(Debug)]
#[must_use = "strategies do nothing unless used"]
pub struct SBoxedStrategy<T>(Arc<dyn Strategy<Value = T, Tree = BoxedVT<T>> + Sync + Send>);

impl<T> Clone for BoxedStrategy<T> {
  fn clone(&self) -> Self {
    Self(Arc::clone(&self.0))
  }
}

impl<T> Clone for SBoxedStrategy<T> {
  fn clone(&self) -> Self {
    Self(Arc::clone(&self.0))
  }
}

impl<T: fmt::Debug> Strategy for BoxedStrategy<T> {
  type Tree = BoxedVT<T>;
  type Value = T;

  fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
    self.0.new_tree(runner)
  }

  // Optimization: Don't rebox the strategy.

  fn boxed(self) -> BoxedStrategy<Self::Value>
  where
    Self: Sized + 'static,
  {
    self
  }
}

impl<T: fmt::Debug> Strategy for SBoxedStrategy<T> {
  type Tree = BoxedVT<T>;
  type Value = T;

  fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
    self.0.new_tree(runner)
  }

  // Optimization: Don't rebox the strategy.

  fn sboxed(self) -> SBoxedStrategy<Self::Value>
  where
    Self: Sized + Send + Sync + 'static,
  {
    self
  }

  fn boxed(self) -> BoxedStrategy<Self::Value>
  where
    Self: Sized + 'static,
  {
    BoxedStrategy(self.0)
  }
}

/// Internal adapter that boxes an inner strategy's `ValueTree` into
/// `BoxedVT`, so `boxed()`/`sboxed()` can erase the concrete tree type.
#[derive(Debug)]
struct BoxedStrategyWrapper<T>(T);
impl<T: Strategy> Strategy for BoxedStrategyWrapper<T>
where
  T::Tree: 'static,
{
  type Tree = Box<dyn ValueTree<Value = T::Value>>;
  type Value = T::Value;

  fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
    Ok(Box::new(self.0.new_tree(runner)?))
  }
}

//==============================================================================
// Sanity checking
//==============================================================================

/// Options passed to `check_strategy_sanity()`.
#[derive(Clone, Copy, Debug)]
pub struct CheckStrategySanityOptions {
  /// If true (the default), require that `complicate()` return `true` at
  /// least once after any call to `simplify()` which itself returns once.
  ///
  /// This property is not required by contract, but many strategies are
  /// designed in a way that this is expected to hold.
  pub strict_complicate_after_simplify: bool,

  /// If true, cause local rejects to return an error instead of retrying.
  /// Defaults to false. Useful for testing behaviors around error handling.
  pub error_on_local_rejects: bool,

  /// Hidden extension slot that keeps struct update syntax available while
  /// allowing more sanity-check options to be added later.
  #[doc(hidden)]
  pub _non_exhaustive: (),
}

impl Default for CheckStrategySanityOptions {
  fn default() -> Self {
    Self {
      strict_complicate_after_simplify: true,
      error_on_local_rejects:           false,
      _non_exhaustive:                  (),
    }
  }
}

/// Drive a fresh clone of `state` to its shrink fixed point.
#[allow(
  clippy::single_call_fn,
  reason = "drive a cloned value tree to its shrink fixed point, panicking on a runaway loop"
)]
fn assert_shrink_converges<V: ValueTree + Clone + fmt::Debug>(state: &V) -> Result<(), Reason> {
  let mut shrink_state = state.clone();
  let mut count = 0_u32;
  while shrink_state.simplify() || shrink_state.complicate() {
    count = count.saturating_add(1);
    if count > 65_536 {
      return Err(format!("Failed to converge on any value. State:\n{shrink_state:#?}").into());
    }
  }
  Ok(())
}

/// Complicate `complicated` until it reports no further change, returning
/// the last state that still reported a change and the number of
/// complications applied.
#[allow(
  clippy::single_call_fn,
  reason = "repeatedly complicate a value tree to its ceiling, returning the last stable state"
)]
fn complicate_to_fixed_point<V: ValueTree + Clone + fmt::Debug>(complicated: &mut V, full_state: &V) -> Result<(V, u32), Reason> {
  let mut prev_complicated = complicated.clone();
  let mut num_complications = 0_u32;
  loop {
    if !complicated.complicate() {
      break;
    }
    prev_complicated = complicated.clone();
    num_complications = num_complications.saturating_add(1);

    if num_complications > 65_536 {
      return Err(
        format!(
          "complicate() returned true over 65536 times in a row; aborting due to possible infinite loop. If this is not an infinite loop, \
           it may be necessary to reconsider how shrinking is implemented or use a simpler test strategy. Internal state:\n{full_state:#?}"
        )
        .into(),
      );
    }
  }
  Ok((prev_complicated, num_complications))
}

/// Return whether `candidate` is not equal to itself, as with floating-point
/// NaN.
fn is_non_reflexive<T: PartialEq>(candidate: &T) -> bool {
  !candidate.eq(candidate)
}

/// Compare two generated values, accepting the NaN-like case where both sides
/// are non-reflexive.
fn sanity_values_match<T: PartialEq>(left: &T, right: &T) -> bool {
  left == right || (is_non_reflexive(left) && is_non_reflexive(right))
}

/// Generate one strategy value tree for the sanity checker.
#[allow(
  clippy::single_call_fn,
  reason = "name the generation phase of check_strategy_sanity and its retry contract"
)]
fn generate_sanity_state<S: Strategy>(strategy: &S, runner: &mut TestRunner) -> Result<S::Tree, Reason> {
  let mut gen_tries = 0_u32;
  loop {
    let err = match strategy.new_tree(runner) {
      Ok(tree) => return Ok(tree),
      Err(reason) => reason,
    };

    gen_tries = gen_tries.saturating_add(1);
    if gen_tries > 100 {
      return Err(
        format!("Strategy passed to check_strategy_sanity failed to generate a value over 100 times in a row; last failure reason: {err}")
          .into(),
      );
    }
  }
}

/// Check one generated value tree against the simplify/complicate contract.
#[allow(
  clippy::single_call_fn,
  reason = "name the per-state simplify and complicate contract checked by check_strategy_sanity"
)]
fn check_sanity_state<V>(mut state: V, sanity_options: CheckStrategySanityOptions) -> Result<(), Reason>
where
  V: ValueTree + Clone + fmt::Debug,
  V::Value: PartialEq,
{
  macro_rules! ensure_same {
        ($a:expr, $b:expr, $($stuff:tt)*) => {{
            let left = $a;
            let right = $b;
            if !sanity_values_match(&left, &right) {
                return Err(format!($($stuff)*).into());
            }
        }};
    }

  assert_shrink_converges(&state)?;

  let mut num_simplifies = 0_u32;
  let mut before_simplified;
  loop {
    before_simplified = state.clone();
    if !state.simplify() {
      break;
    }

    let mut complicated = state.clone();
    let before_complicated = state.clone();
    if sanity_options.strict_complicate_after_simplify && !complicated.complicate() {
      return Err(
        format!(
          "complicate() returned false immediately after simplify() returned true. internal state after {num_simplifies} calls to \
           simplify():\n{before_simplified:#?}\nsimplified to:\n{state:#?}\ncomplicated to:\n{complicated:#?}"
        )
        .into(),
      );
    }

    let (prev_complicated, num_complications) = complicate_to_fixed_point(&mut complicated, &state)?;
    let total_complications = num_complications.saturating_add(1);

    ensure_same!(
      before_simplified.current(),
      complicated.current(),
      "Calling simplify(), then complicate() until it returned false, did not return to the value before simplify. Internal state after \
       {num_simplifies} calls to simplify:\n{before_simplified:#?}\nInternal state after another call to \
       simplify:\n{before_complicated:#?}\nInternal state after {total_complications} subsequent calls to complicate:\n{complicated:#?}"
    );

    verify_complicate_fixed_point(&mut complicated, &prev_complicated)?;

    num_simplifies = num_simplifies.saturating_add(1);
    if num_simplifies > 65_536 {
      return Err(
        format!(
          "simplify() returned true over 65536 times in a row, aborting due to possible infinite loop. If this is not an infinite loop, \
           it may be necessary to reconsider how shrinking is implemented or use a simpler test strategy. Internal state:\n{state:#?}"
        )
        .into(),
      );
    }
  }

  verify_simplify_fixed_point(&mut state, &before_simplified)
}

/// Verify that repeated `complicate()` calls stay fixed after reaching the
/// fixed point.
#[allow(
  clippy::single_call_fn,
  reason = "name the complicate fixed-point rule enforced by check_strategy_sanity"
)]
fn verify_complicate_fixed_point<V>(complicated: &mut V, prev_complicated: &V) -> Result<(), Reason>
where
  V: ValueTree + Clone + fmt::Debug,
  V::Value: PartialEq,
{
  for iter in 1_u32..16 {
    let left = prev_complicated.current();
    let right = complicated.current();
    if !sanity_values_match(&left, &right) {
      return Err(
        format!(
          "complicate() returned false but changed the output value anyway. Old internal state:\n{prev_complicated:#?}\nNew internal \
           state after {iter} calls to complicate:\n{complicated:#?}"
        )
        .into(),
      );
    }

    let attempts = iter.saturating_add(1);
    if complicated.complicate() {
      return Err(
        format!(
          "complicate() returned true after having returned false;\nInternal state before:\n{prev_complicated:#?}\nInternal state after \
           calling complicate() {attempts} times:\n{complicated:#?}"
        )
        .into(),
      );
    }
  }
  Ok(())
}

/// Verify that repeated `simplify()` calls stay fixed after reaching the
/// fixed point.
#[allow(
  clippy::single_call_fn,
  reason = "name the simplify fixed-point rule enforced by check_strategy_sanity"
)]
fn verify_simplify_fixed_point<V>(state: &mut V, before_simplified: &V) -> Result<(), Reason>
where
  V: ValueTree + Clone + fmt::Debug,
  V::Value: PartialEq,
{
  for iter in 0_u32..16 {
    let left = before_simplified.current();
    let right = state.current();
    if !sanity_values_match(&left, &right) {
      return Err(
        format!(
          "simplify() returned false but changed the output value anyway. Previous internal state:\n{before_simplified:#?}\nNew internal \
           state after calling simplify() {iter} times:\n{state:#?}"
        )
        .into(),
      );
    }

    if state.simplify() {
      let attempts = iter.saturating_add(1);
      return Err(
        format!(
          "simplify() returned true after having returned false. Previous internal state:\n{before_simplified:#?}\nNew internal state \
           after calling simplify() {attempts} times:\n{state:#?}"
        )
        .into(),
      );
    }
  }
  Ok(())
}

/// Run some tests on the given `Strategy` to ensure that it upholds the
/// simplify/complicate contracts.
///
/// This is used to internally test proptest, but is made generally available
/// for external implementations to use as well.
///
/// `options` can be passed to configure the test; if `None`, the defaults are
/// used. Note that the defaults check for certain properties which are **not**
/// actually required by the `Strategy` and `ValueTree` contracts; if you think
/// your code is right but it fails the test, consider whether a non-default
/// configuration is necessary.
///
/// This can work with fallible strategies, but limits how many times it will
/// retry failures.
///
/// ## Errors
///
/// Returns [`Reason`] if the strategy violates the `simplify`/`complicate`
/// contract (any of the internal consistency checks fail), if it fails to
/// generate a value 100 times in a row, or if shrinking fails to converge,
/// meaning `simplify()` or `complicate()` keep reporting a change more than
/// 65536 times in a row.
pub fn check_strategy_sanity<S: Strategy>(strategy: S, options: Option<CheckStrategySanityOptions>) -> Result<(), Reason>
where
  S::Tree: Clone + fmt::Debug,
  S::Value: PartialEq,
{
  let sanity_options = options.unwrap_or_default();
  let mut config = Config {
    failure_persistence: None,
    ..Config::default()
  };
  if sanity_options.error_on_local_rejects {
    config.max_local_rejects = 0;
  }
  let mut runner = TestRunner::new(config);

  for _ in 0..1024 {
    let state = generate_sanity_state(&strategy, &mut runner)?;
    check_sanity_state(state, sanity_options)?;
  }
  Ok(())
}

#[cfg(test)]
mod test {
  use std::string::ToString as _;

  use strict_test_support::TestFailure;
  use strict_test_support::ensure;
  use strict_test_support::ensure_contains;
  use strict_test_support::ensure_some;

  use crate::strict::ensure_property;

  // The blanket `impl Strategy for &S` / `&mut S` is selected only when the
  // reference is itself the `Strategy` type parameter, not when a reference
  // is merely the method receiver (that resolves to the pointee). Because
  // `ensure_property` is generic over `S: Strategy` and takes `&S`, passing
  // `&by_ref` binds `S = &U` and passing `&by_mut` binds `S = &mut U`, so
  // `new_tree` dispatches through the blanket delegate. The pointee here is a
  // numeric range, whose value tree does the actual generation and shrinking.

  #[test]
  fn shared_reference_strategy_generates_through_the_blanket_impl() -> Result<(), TestFailure> {
    let base = 0_u32..10;
    let by_ref = &base;
    ensure_property(&by_ref, "a shared reference to a strategy generates like the pointee", |value| {
      ensure(value < 10, "the generated value keeps the bound")
    })
  }

  #[test]
  fn mut_reference_strategy_generates_through_the_blanket_impl() -> Result<(), TestFailure> {
    let mut base = 0_u32..10;
    let by_mut = &mut base;
    ensure_property(&by_mut, "a mutable reference to a strategy generates like the pointee", |value| {
      ensure(value < 10, "the generated value keeps the bound")
    })
  }

  #[test]
  fn shared_reference_strategy_falsifies_and_shrinks() -> Result<(), TestFailure> {
    let base = 1_u32..32;
    let by_ref = &base;
    let failure = ensure_some(
      ensure_property(&by_ref, "a false property through a shared reference still falsifies", |value| {
        ensure(value < 1, "the value stays below one")
      })
      .err(),
      "a false property must falsify through the reference impl",
    )?;
    let rendered = failure.to_string();
    ensure_contains(
      &rendered,
      "property falsified",
      "the reference-impl failure names the falsified family",
    )?;
    ensure_contains(
      &rendered,
      "minimal failing input: 1",
      "shrinking through the reference impl reaches the minimal input",
    )
  }

  #[test]
  fn mut_reference_strategy_falsifies_and_shrinks() -> Result<(), TestFailure> {
    let mut base = 1_u32..32;
    let by_mut = &mut base;
    let failure = ensure_some(
      ensure_property(&by_mut, "a false property through a mutable reference still falsifies", |value| {
        ensure(value < 1, "the value stays below one")
      })
      .err(),
      "a false property must falsify through the mut reference impl",
    )?;
    let rendered = failure.to_string();
    ensure_contains(
      &rendered,
      "property falsified",
      "the mut-reference-impl failure names the falsified family",
    )?;
    ensure_contains(
      &rendered,
      "minimal failing input: 1",
      "shrinking through the mut reference impl reaches the minimal input",
    )
  }
}
