//-
// Copyright 2017, 2018 The proptest developers
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

//! Arbitrary implementations for `std::str`.

use crate::std_facade::Vec;
use core::iter::repeat_n;
use core::str::{ParseBoolError, Utf8Error, from_utf8};

use crate::arbitrary::{StrategyFor, any};
use crate::strategy::{
    FilterMap, Just, Strategy as _, TupleUnion, WeightedStrategy,
};

arbitrary!(ParseBoolError; {
    loop {
        if let Err(error) = "".parse::<bool>() {
            break error;
        }
    }
});

/// One weighted arm of the `gen_el_seqs` union: a `Just` of a fixed
/// invalid-UTF-8 tail byte slice.
type ELSeq = WeightedStrategy<Just<&'static [u8]>>;
/// The union over the four candidate invalid-UTF-8 tail sequences that
/// `gen_el_seqs` picks between.
type ELSeqs = TupleUnion<(ELSeq, ELSeq, ELSeq, ELSeq)>;
/// Source strategy used to construct checked `Utf8Error` values.
type Utf8ErrorSource = (StrategyFor<u16>, ELSeqs);
/// Checked mapping from generated invalid bytes to their `Utf8Error`.
type Utf8ErrorMapper = fn((u16, &'static [u8])) -> Option<Utf8Error>;
/// Strategy for `Utf8Error` that rejects impossible valid UTF-8 candidates.
type Utf8ErrorStrategy = FilterMap<Utf8ErrorSource, Utf8ErrorMapper>;

arbitrary!(Utf8Error, Utf8ErrorStrategy;
    {
        let mapper: Utf8ErrorMapper = |(vut, elseq)| {
            let bytes = repeat_n(b'_', usize::from(vut))
                .chain(elseq.iter().copied())
                .collect::<Vec<u8>>();
            from_utf8(&bytes).err()
        };
        let error_len_sequences: ELSeqs = prop_oneof![
            Just(&[0xC2]),                   // None
            Just(&[0x80]),                   // Some(1)
            Just(&[0xE0, 0xA0, 0x00]),       // Some(2)
            Just(&[0xF0, 0x90, 0x80, 0x00])  // Some(3)
        ];
        (any::<u16>(), error_len_sequences).prop_filter_map(
            "generated bytes must contain an invalid UTF-8 tail",
            mapper,
        )
    }
);

#[cfg(test)]
mod test {
    use super::*;

    no_panic_test!(
        parse_bool_error => ParseBoolError,
        utf8_error => Utf8Error
    );
}
