//-
// Copyright 2023 The proptest developers
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

//! Strategies used for abstract state machine testing.

use std::sync::Arc;
use std::sync::atomic::{self, AtomicUsize};

use proptest::bits::{BitSetLike as _, VarBitSet};
use proptest::collection::SizeRange;
use proptest::num::sample_uniform_incl;
use proptest::std_facade::Vec;
use proptest::std_facade::fmt::{Debug, Formatter, Result};
use proptest::strategy::BoxedStrategy;
use proptest::strategy::{NewTree, Strategy, ValueTree};
use proptest::test_runner::TestRunner;

/// Default sequential state-machine strategy type.
pub type SequentialStrategy<State, Transition> = Sequential<
    State,
    Transition,
    BoxedStrategy<State>,
    BoxedStrategy<Transition>,
>;

/// Shared callback that builds a strategy for the initial reference state.
type InitStateFn<StateStrategy> = Arc<dyn Fn() -> StateStrategy + Send + Sync>;
/// Shared predicate that decides whether a transition is valid in a state.
type PreconditionsFn<State, Transition> =
    Arc<dyn Fn(&State, &Transition) -> bool + Send + Sync>;
/// Shared callback that builds candidate transition strategies for a state.
type TransitionsFn<State, TransitionStrategy> =
    Arc<dyn Fn(&State) -> TransitionStrategy + Send + Sync>;
/// Shared callback that advances the reference state after a transition.
type NextFn<State, Transition> =
    Arc<dyn Fn(State, &Transition) -> State + Send + Sync>;

/// This trait is used to model system under test as an abstract state machine.
///
/// The key to how this works is that the set of next valid transitions depends
/// on its current state (it's not the same as generating a random sequence of
/// transitions) and just like other prop strategies, the state machine strategy
/// attempts to shrink the transitions to find the minimal reproducible example
/// when it encounters a case that breaks any of the defined properties.
///
/// This is achieved with the [`ReferenceStateMachine::transitions`] that takes
/// the current state as an argument and can be used to decide which transitions
/// are valid from this state, together with the
/// [`ReferenceStateMachine::preconditions`], which are checked during generation
/// of transitions and during shrinking.
///
/// Hence, the `preconditions` only needs to contain checks for invariants that
/// depend on the current state and may be broken by shrinking and it doesn't
/// need to cover invariants that do not depend on the current state.
///
/// The reference state machine generation runs before the generated transitions
/// are attempted to be executed against the SUT (the concrete state machine)
/// as defined by [`crate::StateMachineTest`].
pub trait ReferenceStateMachine: 'static {
    /// The reference state machine's state type. This should contain the minimum
    /// required information needed to implement the state machine. It is used
    /// to drive the generations of transitions to decide which transitions are
    /// valid for the current state.
    type State: Clone + Debug;

    /// The reference state machine's transition type. This is typically an enum
    /// with its variants containing the parameters required to apply the
    /// transition, if any.
    type Transition: Clone + Debug;

    // TODO Instead of the boxed strategies, this could use
    // <https://github.com/rust-lang/rust/issues/63063> once stabilized:
    // type StateStrategy = impl Strategy<Value = Self::State>;
    // type TransitionStrategy = impl Strategy<Value = Self::Transition>;

    /// The initial state may be generated by any strategy. For a constant
    /// initial state, use [`proptest::strategy::Just`].
    fn init_state() -> BoxedStrategy<Self::State>;

    /// Generate the initial transitions.
    fn transitions(state: &Self::State) -> BoxedStrategy<Self::Transition>;

    /// Apply a transition in the reference state.
    fn apply(state: Self::State, transition: &Self::Transition) -> Self::State;

    /// Pre-conditions may be specified to control which transitions are valid
    /// from the current state. If not overridden, this allows any transition.
    /// The pre-conditions are checked in the generated transitions and during
    /// shrinking.
    ///
    /// The pre-conditions checking relies on proptest global rejection
    /// filtering, which comes with some [disadvantages](https://altsysrq.github.io/proptest-book/proptest/tutorial/filtering.html).
    /// This means that pre-conditions that are hard to satisfy might slow down
    /// the test or even fail by exceeding the maximum rejection count.
    #[allow(
        clippy::single_call_fn,
        reason = "default reference-state-machine precondition gate that accepts every transition unfiltered"
    )]
    fn preconditions(
        _state: &Self::State,
        _transition: &Self::Transition,
    ) -> bool {
        true
    }

    /// A sequential strategy runs the state machine transitions generated from
    /// the reference model sequentially in a test over a concrete state, which
    /// can be implemented with the help of
    /// [`crate::StateMachineTest`] trait.
    ///
    /// You typically never need to override this method.
    fn sequential_strategy(
        size: impl Into<SizeRange>,
    ) -> SequentialStrategy<Self::State, Self::Transition> {
        Sequential::new(
            size.into(),
            Self::init_state,
            Self::preconditions,
            Self::transitions,
            Self::apply,
        )
    }
}

/// A sequential state machine strategy generates an acceptable transition
/// sequence.
///
/// The sequence satisfies the given pre-conditions. The acceptability of each
/// transition depends on the current state of the state machine, which is
/// updated by the transitions with the `next` function.
///
/// The shrinking strategy is to iteratively apply `Shrink::InitialState`,
/// `Shrink::DeleteTransition` and `Shrink::Transition`.
///
/// 1. We start by trying to delete transitions from the back of the list that
///    were never seen by the test, if any. Note that because proptest expects
///    deterministic results in for reproducible issues, unlike the following
///    steps this step will not be undone on `complicate`. If there were any
///    unseen transitions, then the next step will start at trying to delete
///    the transition before the last one seen as we know that the last
///    transition cannot be deleted as it's the one that has failed.
/// 2. Then, we keep trying to delete transitions from the back of the list, until
///    we can do so no further (reached the beginning of the list)..
/// 3. Then, we again iteratively attempt to shrink the individual transitions,
///    but this time starting from the front of the list - i.e. from the first
///    transition to be applied.
/// 4. Finally, we try to shrink the initial state until it's not possible to
///    shrink it any further.
///
/// For `complicate`, we attempt to undo the last shrink operation, if there was
/// any.
pub struct Sequential<State, Transition, StateStrategy, TransitionStrategy> {
    /// Number of transitions generated for each state-machine case.
    size: SizeRange,
    /// Strategy factory for the initial reference state.
    init_state: InitStateFn<StateStrategy>,
    /// Predicate that guards generated and shrunken transitions.
    preconditions: PreconditionsFn<State, Transition>,
    /// Strategy factory for transitions available from a reference state.
    transitions: TransitionsFn<State, TransitionStrategy>,
    /// Reference-state transition function.
    next: NextFn<State, Transition>,
}

impl<State, Transition, StateStrategy, TransitionStrategy>
    Sequential<State, Transition, StateStrategy, TransitionStrategy>
where
    State: 'static,
    Transition: 'static,
    StateStrategy: 'static,
    TransitionStrategy: 'static,
{
    /// Constructs a sequential strategy from the reference model's building
    /// blocks.
    ///
    /// `size` is the number or range of transitions to generate per case;
    /// `init_state` produces the strategy for the initial reference state;
    /// `preconditions` is the predicate a candidate transition must satisfy
    /// in the current state; `transitions` produces the strategy for the next
    /// transition given the current state; and `next` applies a transition to
    /// advance the reference state.
    #[allow(
        clippy::single_call_fn,
        reason = "constructs the Sequential strategy from the reference models generation and transition callbacks"
    )]
    pub fn new(
        size: SizeRange,
        init_state: impl Fn() -> StateStrategy + 'static + Send + Sync,
        preconditions: impl Fn(&State, &Transition) -> bool + 'static + Send + Sync,
        transitions: impl Fn(&State) -> TransitionStrategy + 'static + Send + Sync,
        next: impl Fn(State, &Transition) -> State + 'static + Send + Sync,
    ) -> Self {
        Self {
            size,
            init_state: Arc::new(init_state),
            preconditions: Arc::new(preconditions),
            transitions: Arc::new(transitions),
            next: Arc::new(next),
        }
    }
}

impl<State, Transition, StateStrategy, TransitionStrategy> Debug
    for Sequential<State, Transition, StateStrategy, TransitionStrategy>
{
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        f.debug_struct("Sequential")
            .field("size", &self.size)
            .field("init_state", &"<init_state callback>")
            .field("preconditions", &"<preconditions callback>")
            .field("transitions", &"<transitions callback>")
            .field("next", &"<next callback>")
            .finish()
    }
}

impl<
    State: Clone + Debug,
    Transition: Clone + Debug,
    StateStrategy: Strategy<Value = State>,
    TransitionStrategy: Strategy<Value = Transition>,
> Strategy
    for Sequential<State, Transition, StateStrategy, TransitionStrategy>
{
    type Tree = SequentialValueTree<
        State,
        Transition,
        StateStrategy::Tree,
        TransitionStrategy::Tree,
    >;
    type Value = (State, Vec<Transition>, Option<Arc<AtomicUsize>>);

    fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
        // Generate the initial state value tree
        let initial_state = (self.init_state)().new_tree(runner)?;
        let last_valid_initial_state = initial_state.current();

        let (min_size, end) = self.size.start_end_incl();
        // Sample the maximum number of the transitions from the size range
        let max_size = sample_uniform_incl(runner, min_size, end)?;
        let mut transitions = Vec::with_capacity(max_size);
        let mut acceptable_transitions = Vec::with_capacity(max_size);
        let included_transitions = VarBitSet::saturated(max_size);
        let shrinkable_transitions = VarBitSet::saturated(max_size);

        // Sample the transitions until we reach the `max_size`
        let mut state = initial_state.current();
        while transitions.len() < max_size {
            // Apply the current state to find the current transition
            let transition_tree =
                (self.transitions)(&state).new_tree(runner)?;
            let transition = transition_tree.current();

            // If the pre-conditions are satisfied, use the transition
            if (self.preconditions)(&state, &transition) {
                transitions.push(transition_tree);
                state = (self.next)(state, &transition);
                acceptable_transitions.push((Accepted, transition));
            } else {
                runner.reject_local("Pre-conditions were not satisfied")?;
            }
        }

        // The maximum index into the vectors and bit sets
        let max_ix = max_size.saturating_sub(1);

        Ok(SequentialValueTree {
            initial_state,
            is_initial_state_shrinkable: true,
            last_valid_initial_state,
            preconditions: Arc::clone(&self.preconditions),
            next: Arc::clone(&self.next),
            transitions,
            acceptable_transitions,
            included_transitions,
            shrinkable_transitions,
            max_ix,
            // On a failure, we start by shrinking transitions from the back
            // which is less likely to invalidate pre-conditions
            shrink: DeleteTransition(max_ix),
            last_shrink: None,
            seen_transitions_counter: Some(Arc::default()),
        })
    }
}

/// A shrinking operation
#[derive(Clone, Copy, Debug)]
enum Shrink {
    /// Shrink the initial state
    InitialState,
    /// Delete a transition at given index
    DeleteTransition(usize),
    /// Shrink a transition at given index
    Transition(usize),
}
use Shrink::{DeleteTransition, InitialState, Transition};

/// The state of a transition in the model
#[derive(Clone, Copy, Debug)]
enum TransitionState {
    /// The transition that is equal to the result of `ValueTree::current()`
    /// and satisfies the pre-conditions
    Accepted,
    /// The transition has been simplified, but rejected by pre-conditions
    SimplifyRejected,
    /// The transition has been complicated, but rejected by pre-conditions
    ComplicateRejected,
}
use TransitionState::{Accepted, ComplicateRejected, SimplifyRejected};

/// The generated value tree for a sequential state machine.
pub struct SequentialValueTree<
    State,
    Transition,
    StateValueTree,
    TransitionValueTree,
> {
    /// The initial state value tree
    initial_state: StateValueTree,
    /// Can the `initial_state` be shrunk any further?
    is_initial_state_shrinkable: bool,
    /// The last initial state that has been accepted by the pre-conditions.
    /// We have to store this every time before attempt to shrink to be able
    /// to back to it in case the shrinking is rejected.
    last_valid_initial_state: State,
    /// The pre-conditions predicate
    preconditions: PreconditionsFn<State, Transition>,
    /// The function from current state and a transition to an updated state
    next: NextFn<State, Transition>,
    /// The list of transitions' value trees
    transitions: Vec<TransitionValueTree>,
    /// The sequence of included transitions with their shrinking state
    acceptable_transitions: Vec<(TransitionState, Transition)>,
    /// The bit-set of transitions that have not been deleted by shrinking
    included_transitions: VarBitSet,
    /// The bit-set of transitions that can be shrunk further
    shrinkable_transitions: VarBitSet,
    /// The maximum index in the `transitions` vector (its size - 1)
    max_ix: usize,
    /// The next shrink operation to apply
    shrink: Shrink,
    /// The last applied shrink operation, if any
    last_shrink: Option<Shrink>,
    /// The number of transitions that were seen by the test runner.
    /// On a test run this is shared with `StateMachineTest::test_sequential`
    /// which increments the inner counter value on every transition. If the
    /// test fails, the counter is used to remove any unseen transitions before
    /// shrinking and this field is set to `None` as it's no longer needed for
    /// shrinking.
    seen_transitions_counter: Option<Arc<AtomicUsize>>,
}

impl<State, Transition, StateValueTree, TransitionValueTree> Debug
    for SequentialValueTree<
        State,
        Transition,
        StateValueTree,
        TransitionValueTree,
    >
{
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        f.debug_struct("SequentialValueTree")
            .field(
                "is_initial_state_shrinkable",
                &self.is_initial_state_shrinkable,
            )
            .field("transitions", &self.transitions.len())
            .field("included_transitions", &self.included_transitions.count())
            .field(
                "shrinkable_transitions",
                &self.shrinkable_transitions.count(),
            )
            .field("max_ix", &self.max_ix)
            .field("shrink", &self.shrink)
            .field("last_shrink", &self.last_shrink)
            .finish_non_exhaustive()
    }
}

impl<
    State: Clone + Debug,
    Transition: Clone + Debug,
    StateValueTree: ValueTree<Value = State>,
    TransitionValueTree: ValueTree<Value = Transition>,
> SequentialValueTree<State, Transition, StateValueTree, TransitionValueTree>
{
    /// The one-shot unseen-transition deletion: when the test runner saw
    /// fewer transitions than are included (the failure cut the run short),
    /// drop the never-executed tail from both bit-sets and jump the shrink
    /// phase to the deepest still-meaningful point. Runs at most once, on
    /// the first `simplify()`, while the seen counter is still attached;
    /// the counter is detached afterwards so shrinking runs pass `None`.
    fn drop_unseen_transitions(&mut self) {
        let Some(seen_transitions_counter) =
            self.seen_transitions_counter.as_ref()
        else {
            return;
        };
        let seen_count =
            seen_transitions_counter.load(atomic::Ordering::SeqCst);

        let included_count = self.included_transitions.count();

        if seen_count >= included_count {
            // every included transition was executed; nothing to drop.
            // Remove the seen transitions counter for shrinking runs.
            self.seen_transitions_counter = None;
            return;
        }

        // the test runner did not see all the transitions so we can delete
        // the transitions that were not seen because they were not executed

        let mut kept_count = 0;
        for ix in 0..self.transitions.len() {
            if !self.included_transitions.test(ix) {
                // transition at ix was already deleted from the test
                continue;
            }
            if kept_count < seen_count {
                // transition at ix was seen by the test or we are
                // still below minimum size for the test
                kept_count = kept_count.saturating_add(1);
                continue;
            }
            // transition at ix was never seen
            self.included_transitions.clear(ix);
            self.shrinkable_transitions.clear(ix);
        }
        // Set the next shrink based on how many transitions were seen:
        // - If 0 seen: go directly to shrinking the initial state.
        // - If 1 seen: can't delete any more, so shrink individual transitions.
        // - If >1 seen: delete the transition before the last seen transition.
        //   (subtract 2 from `kept_count` because the last seen transition
        //   caused the failure).
        self.shrink = match kept_count {
            0 => InitialState,
            1 => Transition(0),
            _ => DeleteTransition(kept_count.saturating_sub(2)),
        };

        // Remove the seen transitions counter for shrinking runs
        self.seen_transitions_counter = None;
    }

    /// Return the current generated transition at `ix`, if the transition
    /// tree vector still contains that slot.
    fn current_transition(&self, ix: usize) -> Option<Transition> {
        self.transitions.get(ix).map(ValueTree::current)
    }

    /// Store the current generated transition at `ix` as the accepted value.
    fn set_accepted_transition(&mut self, ix: usize) -> bool {
        let Some(current) = self.current_transition(ix) else {
            return false;
        };
        let Some(entry) = self.acceptable_transitions.get_mut(ix) else {
            return false;
        };
        *entry = (Accepted, current);
        true
    }

    /// Mark an accepted-transition slot with the given rejection state.
    fn mark_transition_state(
        &mut self,
        ix: usize,
        state: TransitionState,
    ) -> bool {
        let Some(entry) = self.acceptable_transitions.get_mut(ix) else {
            return false;
        };
        entry.0 = state;
        true
    }

    /// Try to apply the next `self.shrink`. Returns `true` if a shrink has been
    /// applied.
    fn try_simplify(&mut self) -> bool {
        self.drop_unseen_transitions();

        if let DeleteTransition(ix) = self.shrink {
            // Delete the index from the included transitions
            self.included_transitions.clear(ix);

            self.last_shrink = Some(self.shrink);
            self.shrink = if ix == 0 {
                // Reached the beginning of the list, move on to shrinking
                Transition(0)
            } else {
                // Try to delete the previous transition next
                DeleteTransition(ix.saturating_sub(1))
            };
            // If this delete is not acceptable, undo it and try again
            if !self
                .check_acceptable(None, self.last_valid_initial_state.clone())
            {
                self.included_transitions.set(ix);
                self.last_shrink = None;
                return self.try_simplify();
            }
            // If the delete was accepted, remove this index from shrinkable
            // transitions
            self.shrinkable_transitions.clear(ix);
            return true;
        }

        while let Transition(ix) = self.shrink {
            if self.shrinkable_transitions.count() == 0 {
                // Move on to shrinking the initial state
                self.shrink = InitialState;
                break;
            }

            if !self.included_transitions.test(ix) {
                // No use shrinking something we're not including
                self.shrink = self.next_shrink_transition(ix);
                continue;
            }

            if self
                .acceptable_transitions
                .get(ix)
                .is_some_and(|entry| matches!(entry.0, SimplifyRejected))
            {
                // This transition is already simplified and rejected
                self.shrink = self.next_shrink_transition(ix);
                continue;
            }

            let Some(transition) = self.transitions.get_mut(ix) else {
                self.shrinkable_transitions.clear(ix);
                self.shrink = self.next_shrink_transition(ix);
                continue;
            };

            if !transition.simplify() {
                // Nothing simpler to try for this transition
                self.shrinkable_transitions.clear(ix);
                self.shrink = self.next_shrink_transition(ix);
                continue;
            }

            self.last_shrink = Some(self.shrink);
            if self.commit_simplified_transition(ix) {
                return true;
            }
            return self.simplify();
        }

        if matches!(self.shrink, InitialState) {
            return self.simplify_initial_state();
        }

        false
    }

    /// Commit the just-simplified value of the transition at `ix` if the
    /// whole included sequence still satisfies the preconditions from the
    /// last valid initial state; otherwise mark the slot `SimplifyRejected`,
    /// drop it from the shrinkable set, and advance the shrink cursor.
    /// Returns whether the simplification was accepted.
    fn commit_simplified_transition(&mut self, ix: usize) -> bool {
        if self
            .check_acceptable(Some(ix), self.last_valid_initial_state.clone())
            && self.set_accepted_transition(ix)
        {
            return true;
        }
        if !self.mark_transition_state(ix, SimplifyRejected) {
            return false;
        }
        self.shrinkable_transitions.clear(ix);
        self.shrink = self.next_shrink_transition(ix);
        false
    }

    /// The final shrink phase: simplify the initial state itself. The shrunk
    /// state is accepted only if the whole included sequence still satisfies
    /// the preconditions when replayed from it. Once the initial state cannot
    /// shrink further, shrinking as a whole is done.
    fn simplify_initial_state(&mut self) -> bool {
        if self.initial_state.simplify() {
            if self.check_acceptable(None, self.initial_state.current()) {
                self.last_valid_initial_state = self.initial_state.current();
                self.last_shrink = Some(self.shrink);
                return true;
            }
            // If the shrink is not acceptable, clear it out
            self.last_shrink = None;

            // `initial_state` is "dirty" here but we won't ever use it again
            // because it is unshrinkable from here.
        }
        self.is_initial_state_shrinkable = false;
        // Nothing left to do
        false
    }

    /// Undo the last simplification of the transition at `ix`: if the
    /// complicated value keeps the included sequence acceptable, commit it;
    /// otherwise mark the slot `ComplicateRejected`. Returns whether the
    /// complication was accepted.
    fn commit_complicated_transition(&mut self, ix: usize) -> bool {
        let Some(transition) = self.transitions.get_mut(ix) else {
            return false;
        };

        if !transition.complicate() {
            return false;
        }
        if self
            .check_acceptable(Some(ix), self.last_valid_initial_state.clone())
            && self.set_accepted_transition(ix)
        {
            return true;
        }
        if !self.mark_transition_state(ix, ComplicateRejected) {
            return false;
        }
        false
    }

    /// Find if there's any acceptable included transition that is not current,
    /// starting from the given index. Expects that all the included transitions
    /// are currently being rejected (when `can_simplify` returns `false`).
    fn try_to_find_acceptable_transition(&mut self, ix: usize) -> bool {
        let mut ix_to_check = ix;
        loop {
            if self.included_transitions.test(ix_to_check)
                && self.check_acceptable(
                    Some(ix_to_check),
                    self.last_valid_initial_state.clone(),
                )
                && self.set_accepted_transition(ix_to_check)
            {
                return true;
            }
            // Move on to the next transition
            if ix_to_check == self.max_ix {
                ix_to_check = 0;
            } else {
                ix_to_check = ix_to_check.saturating_add(1);
            }
            // We're back to where we started, there nothing left to do
            if ix_to_check == ix {
                return false;
            }
        }
    }

    /// Check if the sequence of included transitions is acceptable by the
    /// pre-conditions. When `ix` is not `None`, the transition at the given
    /// index is taken from its current value.
    fn check_acceptable(&self, ix: Option<usize>, mut state: State) -> bool {
        let Some(transitions) = self.get_included_acceptable_transitions(ix)
        else {
            return false;
        };
        for transition in &transitions {
            let is_acceptable = (self.preconditions)(&state, transition);
            if is_acceptable {
                state = (self.next)(state, transition);
            } else {
                return false;
            }
        }
        true
    }

    /// The currently included and acceptable transitions. When `ix` is not
    /// `None`, the transition at this index is taken from its current value
    /// which may not be acceptable by the pre-conditions, instead of its
    /// acceptable value.
    fn get_included_acceptable_transitions(
        &self,
        ix: Option<usize>,
    ) -> Option<Vec<Transition>> {
        self.acceptable_transitions
            .iter()
            .enumerate()
            // Filter out deleted transitions
            .filter(|&(this_ix, _)| self.included_transitions.test(this_ix))
            // Map the indices to the values
            .map(|(this_ix, entry)| match ix {
                Some(target_ix) if this_ix == target_ix => {
                    self.current_transition(target_ix)
                }
                _ => Some(entry.1.clone()),
            })
            .collect()
    }

    /// Find if the initial state is still shrinkable or if any of the
    /// simplifications and complications of the included transitions have not
    /// yet been rejected.
    fn can_simplify(&self) -> bool {
        self.is_initial_state_shrinkable ||
             // If there are some transitions whose shrinking has not yet been
             // rejected, we can try to shrink them further
             !self
                .acceptable_transitions
                .iter()
                .enumerate()
                // Filter out deleted transitions
                .filter(|&(ix, _)| self.included_transitions.test(ix))
                .all(|(_, entry)| {
                    matches!(entry.0, SimplifyRejected | ComplicateRejected)
                })
    }

    /// Find the next shrink transition. Loops back to the front of the list
    /// when the end is reached, because sometimes a transition might become
    /// acceptable only after a transition that comes before it in the sequence
    /// gets shrunk.
    const fn next_shrink_transition(&self, current_ix: usize) -> Shrink {
        if current_ix == self.max_ix {
            // Either loop back to the start of the list...
            Transition(0)
        } else {
            // ...or move on to the next transition
            Transition(current_ix.saturating_add(1))
        }
    }
}

impl<
    State: Clone + Debug,
    Transition: Clone + Debug,
    StateValueTree: ValueTree<Value = State>,
    TransitionValueTree: ValueTree<Value = Transition>,
> ValueTree
    for SequentialValueTree<
        State,
        Transition,
        StateValueTree,
        TransitionValueTree,
    >
{
    type Value = (State, Vec<Transition>, Option<Arc<AtomicUsize>>);

    fn current(&self) -> Self::Value {
        (
            self.last_valid_initial_state.clone(),
            // The current included acceptable transitions
            self.get_included_acceptable_transitions(None)
                .unwrap_or_default(),
            self.seen_transitions_counter.clone(),
        )
    }

    fn simplify(&mut self) -> bool {
        let was_simplified = if self.can_simplify() {
            self.try_simplify()
        } else if let Some(Transition(ix)) = self.last_shrink {
            self.try_to_find_acceptable_transition(ix)
        } else {
            false
        };

        // reset seen transactions counter for next run
        self.seen_transitions_counter = Option::default();

        was_simplified
    }

    fn complicate(&mut self) -> bool {
        // reset seen transactions counter for next run
        self.seen_transitions_counter = Option::default();

        match self.last_shrink {
            None => false,
            Some(DeleteTransition(ix)) => {
                // Undo the last item we deleted. Can't complicate any further,
                // so unset prev_shrink.
                self.included_transitions.set(ix);
                self.shrinkable_transitions.set(ix);
                self.last_shrink = None;
                true
            }
            Some(Transition(ix)) => {
                if self.commit_complicated_transition(ix) {
                    // Don't unset prev_shrink; we may be able to complicate
                    // it again
                    return true;
                }
                // Can't complicate the last element any further
                self.last_shrink = None;
                false
            }
            Some(InitialState) => {
                if self.initial_state.complicate()
                    && self.check_acceptable(None, self.initial_state.current())
                {
                    self.last_valid_initial_state =
                        self.initial_state.current();
                    // Don't unset prev_shrink; we may be able to complicate
                    // it again
                    return true;
                }
                // Can't complicate the initial state any further
                self.last_shrink = None;
                false
            }
        }
    }
}

#[cfg(test)]
mod test {
    use super::*;

    use proptest::collection::hash_set;
    use proptest::strict::{self, TestFailure};
    use strict_test_support::{
        ensure, ensure_contains, ensure_eq, ensure_some,
    };

    use heap_state_machine::*;
    use std::collections::HashSet;
    // `use super::*` drags in the library's `fmt::Result` alias, which would
    // otherwise shadow the prelude `Result` in the test signatures below.
    use std::result::Result;

    #[test]
    fn sequential_value_tree_debug_reports_shrink_state()
    -> Result<(), TestFailure> {
        let value_tree = deterministic_sequential_value_tree()?;
        let rendered = format!("{value_tree:?}");
        ensure_contains(
            &rendered,
            "SequentialValueTree",
            "the debug rendering names the value-tree type",
        )?;
        ensure_contains(
            &rendered,
            "shrink",
            "the debug rendering exposes the current shrink cursor",
        )?;
        ensure_contains(
            &rendered,
            "included_transitions",
            "the debug rendering exposes the included-transition count",
        )
    }

    /// A number of simplifications that can be applied in the `ValueTree`
    /// produced by [`deterministic_sequential_value_tree`]. It depends on the
    /// [`TRANSITIONS`] given to its `sequential_strategy`.
    ///
    /// This constant can be determined from the test
    /// `number_of_sequential_value_tree_simplifications`.
    const SIMPLIFICATIONS: usize = 32;
    /// Number of transitions in the [`deterministic_sequential_value_tree`].
    const TRANSITIONS: usize = 32;

    #[test]
    fn number_of_sequential_value_tree_simplifications()
    -> Result<(), TestFailure> {
        let mut value_tree = deterministic_sequential_value_tree()?;
        ensure_some(
            value_tree.seen_transitions_counter.as_mut(),
            "the fresh value tree carries a seen-transitions counter",
        )?
        .store(TRANSITIONS, atomic::Ordering::SeqCst);

        let mut i = 0;
        loop {
            let simplified = value_tree.simplify();
            if simplified {
                i += 1;
            } else {
                break;
            }
        }
        ensure_eq(
            &i,
            &SIMPLIFICATIONS,
            "the deterministic value tree yields the pinned simplification count",
        )
    }

    /// Test the simplifications and complication of the
    /// `SequentialValueTree` produced by
    /// `deterministic_sequential_value_tree`.
    ///
    /// The indices of simplification on which we'll attempt to complicate
    /// after simplification are selected from the randomly generated
    /// `complicate_ixs`.
    ///
    /// Every simplification and complication must satisfy pre-conditions of
    /// the state-machine.
    #[test]
    fn test_state_machine_sequential_value_tree() -> Result<(), TestFailure> {
        strict::ensure_property(
            &hash_set(0..SIMPLIFICATIONS, 0..SIMPLIFICATIONS),
            "every simplification and complication satisfies the preconditions",
            |complicate_ixs| {
                test_state_machine_sequential_value_tree_aux(&complicate_ixs)
            },
        )
    }

    #[allow(
        clippy::single_call_fn,
        reason = "test body driving repeated simplify and complicate cycles while preconditions hold"
    )]
    fn test_state_machine_sequential_value_tree_aux(
        complicate_ixs: &HashSet<usize>,
    ) -> Result<(), TestFailure> {
        let mut value_tree = deterministic_sequential_value_tree()?;

        let mut ix = 0_usize;
        loop {
            let simplified = value_tree.simplify();

            check_heap_preconditions(&value_tree)?;

            if !simplified {
                break;
            }
            ix = ix.saturating_add(1);

            if complicate_ixs.contains(&ix) {
                complicate_while_heap_preconditions_hold(&mut value_tree)?;
            }
        }
        Ok(())
    }

    fn check_heap_preconditions(
        candidate_tree: &TestValueTree,
    ) -> Result<(), TestFailure> {
        let (mut state, transitions, _seen_counter) = candidate_tree.current();
        for transition in transitions {
            // Every transition must satisfy the pre-conditions
            ensure(
                <HeapStateMachine as ReferenceStateMachine>::preconditions(
                    &state,
                    &transition,
                ),
                "every kept transition satisfies the preconditions",
            )?;

            // Apply the transition to update the state for the next transition
            state = <HeapStateMachine as ReferenceStateMachine>::apply(
                state,
                &transition,
            );
        }
        Ok(())
    }

    #[allow(
        clippy::single_call_fn,
        reason = "the value-tree test names the complication replay that must preserve heap preconditions"
    )]
    fn complicate_while_heap_preconditions_hold(
        value_tree: &mut TestValueTree,
    ) -> Result<(), TestFailure> {
        loop {
            let complicated = value_tree.complicate();
            check_heap_preconditions(value_tree)?;

            if !complicated {
                break;
            }
        }
        Ok(())
    }

    /// Test the initial simplifications of the `SequentialValueTree` produced
    /// by `deterministic_sequential_value_tree`.
    ///
    /// We want to make sure that we initially remove the transitions that
    /// where not seen.
    #[test]
    fn test_value_tree_initial_simplification() -> Result<(), TestFailure> {
        strict::ensure_property(
            &(10_usize..100),
            "the first simplification removes the unseen transitions",
            test_value_tree_initial_simplification_aux,
        )
    }

    #[allow(
        clippy::single_call_fn,
        reason = "test body verifying the first simplification prunes the unseen transitions"
    )]
    fn test_value_tree_initial_simplification_aux(
        len: usize,
    ) -> Result<(), TestFailure> {
        let sequential =
            <HeapStateMachine as ReferenceStateMachine>::sequential_strategy(
                ..len,
            );

        let mut runner = TestRunner::deterministic();
        let mut value_tree = ensure_some(
            sequential.new_tree(&mut runner).ok(),
            "the deterministic runner builds the sized value tree",
        )?;

        let (_, transitions, mut seen_counter) = value_tree.current();

        let num_seen = transitions.len().div_euclid(2);
        ensure_some(
            seen_counter.as_mut(),
            "the fresh value tree carries a seen-transitions counter",
        )?
        .store(num_seen, atomic::Ordering::SeqCst);

        let mut seen_before_complication =
            transitions.into_iter().take(num_seen).collect::<Vec<_>>();

        ensure(value_tree.simplify(), "the first simplification applies")?;

        let (_, remaining_transitions, _seen_counter) = value_tree.current();

        let seen_after_first_complication =
            remaining_transitions.into_iter().collect::<Vec<_>>();

        // After the unseen transitions are removed, the shrink behavior depends
        // on how many transitions were seen:
        // - If > 1 seen: delete the transition before the last seen one
        // - If = 1 seen: can't delete any more, may start individual transition shrinking
        if seen_before_complication.len() > 1 {
            let last = ensure_some(
                seen_before_complication.pop(),
                "more than one seen transition leaves a last element",
            )?;
            let _removed_before_last = ensure_some(
                seen_before_complication.pop(),
                "more than one seen transition leaves a predecessor to remove",
            )?;
            seen_before_complication.push(last);
            ensure(
                seen_before_complication == seen_after_first_complication,
                "only seen transitions should be present after first simplification",
            )?;
        } else {
            // When there's only 1 seen transition, we expect it to be preserved.
            ensure(
                !seen_after_first_complication.is_empty(),
                "When only 1 transition was seen, at least 1 should remain after simplification",
            )?;
            ensure(
                matches!(value_tree.shrink, Transition(0)),
                "When only 1 transition was seen, shrink should be set to Transition(0)",
            )?;
        }
        Ok(())
    }

    /// Pins the non-panicking `current()` contract for an already-observed
    /// sequential value tree.
    #[test]
    fn current_with_non_zero_seen_counter_preserves_state()
    -> Result<(), TestFailure> {
        let value_tree = deterministic_sequential_value_tree()?;

        let (_, transitions_before, mut seen_counter) = value_tree.current();
        ensure_some(
            seen_counter.as_mut(),
            "the fresh value tree carries a seen-transitions counter",
        )?
        .store(1, atomic::Ordering::SeqCst);
        drop(seen_counter);

        let (_, transitions_after, current_seen_counter) = value_tree.current();
        ensure(
            transitions_before == transitions_after,
            "current() does not mutate the transition view",
        )?;
        let preserved_seen_counter = ensure_some(
            current_seen_counter.as_ref(),
            "current() preserves the seen-transitions counter",
        )?;
        ensure_eq(
            &1,
            &preserved_seen_counter.load(atomic::Ordering::SeqCst),
            "current() preserves the observed transition count",
        )
    }

    /// The following is a definition of an reference state machine used for the
    /// tests.
    mod heap_state_machine {
        use std::vec::Vec;

        use crate::{ReferenceStateMachine, SequentialValueTree};
        use proptest::prelude::*;
        use proptest::test_runner::TestRunner;

        use super::TRANSITIONS;

        pub(super) struct HeapStateMachine;

        pub(super) type TestValueTree = SequentialValueTree<
            TestState,
            TestTransition,
            <BoxedStrategy<TestState> as Strategy>::Tree,
            <BoxedStrategy<TestTransition> as Strategy>::Tree,
        >;

        pub(super) type TestState = Vec<i32>;

        #[derive(Clone, Debug, PartialEq)]
        pub(super) enum TestTransition {
            PopNonEmpty,
            PopEmpty,
            Push(i32),
        }

        #[allow(
            clippy::single_call_fn,
            reason = "the heap model names state-dependent transition choices separately from the trait adapter"
        )]
        fn heap_transition_choices(
            state: &TestState,
        ) -> BoxedStrategy<TestTransition> {
            if state.is_empty() {
                return prop_oneof![
                    1 => Just(TestTransition::PopEmpty),
                    2 => (any::<i32>()).prop_map(TestTransition::Push),
                ]
                .boxed();
            }

            prop_oneof![
                1 => Just(TestTransition::PopNonEmpty),
                2 => (any::<i32>()).prop_map(TestTransition::Push),
            ]
            .boxed()
        }

        #[allow(
            clippy::single_call_fn,
            reason = "the heap model names the pop transition's effect on reference state"
        )]
        fn pop_model_state(state: &mut TestState) {
            let _popped = state.pop();
        }

        pub(super) fn deterministic_sequential_value_tree()
        -> Result<TestValueTree, strict_test_support::TestFailure> {
            let sequential =
                <HeapStateMachine as ReferenceStateMachine>::sequential_strategy(
                    TRANSITIONS,
                );
            let mut runner = TestRunner::deterministic();
            strict_test_support::ensure_some(
                sequential.new_tree(&mut runner).ok(),
                "the deterministic runner builds the sequential value tree",
            )
        }

        impl ReferenceStateMachine for HeapStateMachine {
            type State = TestState;
            type Transition = TestTransition;

            fn init_state() -> BoxedStrategy<Self::State> {
                Just(vec![]).boxed()
            }

            fn transitions(
                state: &Self::State,
            ) -> BoxedStrategy<Self::Transition> {
                heap_transition_choices(state)
            }

            fn apply(
                mut state: Self::State,
                transition: &Self::Transition,
            ) -> Self::State {
                use TestTransition::{PopEmpty, PopNonEmpty, Push};

                match *transition {
                    PopEmpty | PopNonEmpty => pop_model_state(&mut state),
                    Push(value) => state.push(value),
                }
                state
            }

            fn preconditions(
                state: &Self::State,
                transition: &Self::Transition,
            ) -> bool {
                match *transition {
                    TestTransition::PopEmpty => state.is_empty(),
                    TestTransition::PopNonEmpty => !state.is_empty(),
                    TestTransition::Push(_) => true,
                }
            }
        }
    }

    /// A tests that verifies that the strategy finds a simplest failing case, and
    /// that this simplest failing case is ultimately reported by the test runner,
    /// as opposed to reporting input that actually passes the test.
    ///
    /// This module defines a state machine test that is designed to fail.
    /// The reference state machine consists of a lower bound the acceptable value
    /// of a transition. And the test fails if an unacceptably low transition
    /// value is observed, given the reference state's limit.
    ///
    /// This intentionally-failing state machine test is then run inside a proptest
    /// to verify that it reports a simplest failing input when it fails.
    mod find_simplest_failure {
        use proptest::prelude::*;
        use proptest::strategy::BoxedStrategy;
        use proptest::strict::{self, TestFailure};
        use proptest::test_runner::{RngAlgorithm, TestRng};
        use proptest::{
            collection,
            test_runner::{TestCaseError, TestError, TestRunner},
        };
        use strict_test_support::{ensure, ensure_eq, ensure_some};

        use crate::{
            ReferenceStateMachine, StateMachineTest,
            strict_state_machine_config,
        };

        const MIN_TRANSITION: u32 = 10;
        const MAX_TRANSITION: u32 = 20;

        const MIN_LIMIT: u32 = 2;
        const MAX_LIMIT: u32 = 50;

        #[derive(Debug, Default, Clone)]
        struct FailIfLessThan(u32);
        impl ReferenceStateMachine for FailIfLessThan {
            type State = Self;
            type Transition = u32;

            fn init_state() -> BoxedStrategy<Self> {
                (MIN_LIMIT..MAX_LIMIT).prop_map(FailIfLessThan).boxed()
            }

            fn transitions(_: &Self::State) -> BoxedStrategy<u32> {
                (MIN_TRANSITION..MAX_TRANSITION).boxed()
            }

            fn apply(state: Self::State, _: &Self::Transition) -> Self::State {
                state
            }
        }

        /// Defines a test that is intended to fail, so that we can inspect the
        /// failing input.
        struct FailIfLessThanTest;
        impl StateMachineTest for FailIfLessThanTest {
            type SystemUnderTest = ();
            type Reference = FailIfLessThan;

            fn init_test(_ref_state: &FailIfLessThan) {}

            fn apply(
                (): Self::SystemUnderTest,
                ref_state: &FailIfLessThan,
                transition: u32,
            ) -> Result<Self::SystemUnderTest, TestFailure> {
                // Fail on any transition that is less than the ref state's limit.
                let &FailIfLessThan(limit) = ref_state;
                ensure(
                    transition >= limit,
                    "transition is at least the reference limit",
                )
            }
        }

        /// Run the intentionally-failing state machine seeded with `seed` and
        /// return the minimal falsified input `(limit, transitions)`, or
        /// `None` when the run passes or aborts (a limit at or below the
        /// smallest possible transition can never fail). Deterministic in
        /// `seed`, so the precondition filter and the property body observe
        /// the same outcome.
        fn minimal_failure(seed: &[u8]) -> Option<(u32, Vec<u32>)> {
            // We need to explicitly create a runner so that we can inspect
            // the output, and determine if it does return an input that
            // should fail, and is minimal.
            let mut runner = TestRunner::new_with_rng(
                strict_state_machine_config(),
                TestRng::from_seed(RngAlgorithm::default(), seed),
            );
            let result = runner.run(
                &FailIfLessThan::sequential_strategy(10..50_usize),
                |(ref_state, transitions, seen_counter)| {
                    // The strict TestFailure is this manual runner's
                    // failure signal: convert it exactly the way the
                    // strict runner does, so shrinking still drives.
                    FailIfLessThanTest::test_sequential(
                        strict_state_machine_config(),
                        ref_state,
                        transitions,
                        seen_counter,
                    )
                    .map_err(|failure| TestCaseError::fail(failure.to_string()))
                },
            );
            match result {
                Err(TestError::Fail(
                    _,
                    (FailIfLessThan(limit), transitions, _seen_counter),
                )) => Some((limit, transitions)),
                _ => None,
            }
        }

        #[test]
        fn test_returns_simplest_failure() -> Result<(), TestFailure> {
            // A seed is only meaningful when the seeded inner state machine
            // actually fails, so that precondition lives in the strategy as
            // a filter rather than an in-body rejection; `minimal_failure`
            // is deterministic per seed, so the property body re-runs the
            // same failure the filter observed.
            let failing_seeds =
                collection::vec(any::<u8>(), 32).no_shrink().prop_filter(
                    "the seeded state machine must fail as intended",
                    |seed| minimal_failure(seed).is_some(),
                );
            strict::ensure_property(
                &failing_seeds,
                "the runner reports the simplest failing transition sequence",
                |seed| {
                    let (limit, transitions) = ensure_some(
                        minimal_failure(&seed),
                        "a filtered seed reproduces the inner failure",
                    )?;
                    ensure_eq(
                        &transitions.len(),
                        &1,
                        "the minimal failing case is a single transition",
                    )?;
                    ensure_eq(
                        &limit,
                        &(MIN_TRANSITION + 1),
                        "shrinking drives the limit to the smallest failing bound",
                    )?;
                    let transition = ensure_some(
                        transitions.into_iter().next(),
                        "the minimal failing case carries its transition",
                    )?;
                    ensure(
                        transition < limit,
                        "the reported transition violates the limit",
                    )
                },
            )
        }
    }

    /// Dual-polarity coverage for the strict runner path: the negative case
    /// proves a threshold-crossing model falsifies with the minimal
    /// transition sequence, and the positive case proves precondition-gated
    /// generation keeps a mirrored SUT aligned.
    mod strict_runner_behavior {
        use proptest::strategy::BoxedStrategy;
        use proptest::strict::{self, TestFailure, TestResult};
        use strict_test_support::{
            ensure, ensure_contains, ensure_eq, ensure_some,
        };

        use super::heap_state_machine::{HeapStateMachine, TestTransition};
        use crate::{
            ReferenceStateMachine, StateMachineTest,
            strict_state_machine_config,
        };

        /// Model transition: a counter that only increments. The
        /// single-variant enum keeps the reported minimal sequence's
        /// `Debug` rendering stable for the assertions below.
        #[derive(Clone, Debug)]
        enum Tick {
            Increment,
        }

        struct CountingModel;

        impl ReferenceStateMachine for CountingModel {
            type State = u32;
            type Transition = Tick;

            fn init_state() -> BoxedStrategy<u32> {
                use proptest::strategy::{Just, Strategy as _};
                Just(0).boxed()
            }

            fn transitions(_: &u32) -> BoxedStrategy<Tick> {
                use proptest::strategy::{Just, Strategy as _};
                Just(Tick::Increment).boxed()
            }

            fn apply(state: u32, _: &Tick) -> u32 {
                state.saturating_add(1)
            }
        }

        /// SUT that violates its invariant once the counter reaches three,
        /// so the shortest failing sequence is exactly three increments.
        struct FailsAtThree;

        impl StateMachineTest for FailsAtThree {
            type SystemUnderTest = u32;
            type Reference = CountingModel;

            fn init_test(ref_state: &u32) -> u32 {
                *ref_state
            }

            fn apply(state: u32, _: &u32, _: Tick) -> Result<u32, TestFailure> {
                Ok(state.saturating_add(1))
            }

            fn check_invariants(state: &u32, _: &u32) -> TestResult {
                ensure(*state < 3, "the counter stays below three")
            }
        }

        struct MirroredHeap;

        #[allow(
            clippy::single_call_fn,
            reason = "the mirrored heap SUT names the PopEmpty post-condition separately from transition dispatch"
        )]
        fn apply_mirrored_pop_empty(
            state: &mut Vec<i32>,
        ) -> Result<(), TestFailure> {
            ensure(
                state.is_empty(),
                "PopEmpty is only generated on an empty heap",
            )?;
            ensure(
                state.pop().is_none(),
                "PopEmpty leaves an empty heap unchanged",
            )
        }

        #[allow(
            clippy::single_call_fn,
            reason = "the mirrored heap SUT names the PopNonEmpty post-condition separately from transition dispatch"
        )]
        fn apply_mirrored_pop_non_empty(
            state: &mut Vec<i32>,
        ) -> Result<(), TestFailure> {
            ensure(
                !state.is_empty(),
                "PopNonEmpty is only generated on a non-empty heap",
            )?;
            let _popped = ensure_some(
                state.pop(),
                "PopNonEmpty removes an element from a non-empty heap",
            )?;
            Ok(())
        }

        impl StateMachineTest for MirroredHeap {
            type SystemUnderTest = Vec<i32>;
            type Reference = HeapStateMachine;

            fn init_test(ref_state: &Vec<i32>) -> Vec<i32> {
                ref_state.clone()
            }

            fn apply(
                mut state: Vec<i32>,
                ref_state: &Vec<i32>,
                transition: TestTransition,
            ) -> Result<Vec<i32>, TestFailure> {
                use TestTransition::{PopEmpty, PopNonEmpty, Push};

                match transition {
                    PopEmpty => apply_mirrored_pop_empty(&mut state)?,
                    PopNonEmpty => apply_mirrored_pop_non_empty(&mut state)?,
                    Push(value) => state.push(value),
                }
                ensure(
                    state == *ref_state,
                    "the SUT mirrors the model after every transition",
                )?;
                Ok(state)
            }
        }

        #[test]
        fn falsified_model_reports_the_minimal_transition_sequence()
        -> Result<(), TestFailure> {
            let strategy =
                <CountingModel as ReferenceStateMachine>::sequential_strategy(
                    1..8,
                );
            let outcome = strict::ensure_property(
                &strategy,
                "the counter stays below three",
                |(initial_state, transitions, seen_counter)| {
                    <FailsAtThree as StateMachineTest>::test_sequential(
                        strict_state_machine_config(),
                        initial_state,
                        transitions,
                        seen_counter,
                    )
                },
            );
            let failure = ensure_some(
                outcome.err(),
                "a threshold-crossing model must falsify the property",
            )?;
            let rendered = failure.to_string();
            ensure(
                matches!(failure, TestFailure::PropertyFalsified { .. }),
                "the strict runner reports the falsified-property variant",
            )?;
            ensure_contains(
                &rendered,
                "minimal failing input:",
                "the report carries the engine's minimal-input banner",
            )?;
            // The report renders the minimal triple with alternate Debug
            // (`{:#?}`), one transition per line, so pin the sequence by
            // counting transitions: exactly three increments reach the
            // threshold, and no never-executed tail transition survives the
            // seen-transition shrink phase.
            ensure_eq(
                &rendered.matches("Increment").count(),
                &3,
                "shrinking lands on the three increments reaching the threshold",
            )
        }

        #[test]
        fn precondition_gated_generation_keeps_a_mirrored_sut_aligned()
        -> Result<(), TestFailure> {
            let strategy = <HeapStateMachine as ReferenceStateMachine>::sequential_strategy(
                1..12,
            );
            strict::ensure_property(
                &strategy,
                "precondition-gated transitions keep the mirrored SUT aligned",
                |(initial_state, transitions, seen_counter)| {
                    <MirroredHeap as StateMachineTest>::test_sequential(
                        strict_state_machine_config(),
                        initial_state,
                        transitions,
                        seen_counter,
                    )
                },
            )
        }
    }

    #[test]
    fn test_zero_seen_transitions_optimization() -> Result<(), TestFailure> {
        // Test that when 0 transitions are seen, we go directly to InitialState shrinking
        let mut value_tree = deterministic_sequential_value_tree()?;

        // Simulate that no transitions were seen (kept_count = 0)
        ensure_some(
            value_tree.seen_transitions_counter.as_mut(),
            "the fresh value tree carries a seen-transitions counter",
        )?
        .store(0, atomic::Ordering::SeqCst);

        // Call simplify - this should trigger the optimization
        let simplified = value_tree.simplify();

        ensure_eq(
            &value_tree.included_transitions.count(),
            &0,
            "All transitions should be removed when none were seen",
        )?;
        ensure(
            matches!(value_tree.shrink, InitialState),
            "Shrink should be set to InitialState when kept_count == 0",
        )?;

        // The HeapStateMachine uses Just(vec![]) for initial state, which is not shrinkable
        // So simplify() should return false, but the optimization still works correctly
        ensure(
            !simplified,
            "Simplification should return false since initial state (Just(vec![])) is not shrinkable",
        )?;

        let (_, transitions, _) = value_tree.current();
        ensure(
            transitions.is_empty(),
            "No transitions should remain when none were seen",
        )
    }
}
